// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that provides optimized service provider recommendations.
 *
 * - optimizeServiceProviderRecommendations - A function that handles the recommendation process.
 * - OptimizeServiceProviderRecommendationsInput - The input type for the optimizeServiceProviderRecommendations function.
 * - OptimizeServiceProviderRecommendationsOutput - The return type for the optimizeServiceProviderRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OptimizeServiceProviderRecommendationsInputSchema = z.object({
  location: z.string().describe('The location of the client.'),
  serviceType: z.string().describe('The type of NDT service needed.'),
  specialization: z.string().describe('The specialization required for the service.'),
});
export type OptimizeServiceProviderRecommendationsInput = z.infer<
  typeof OptimizeServiceProviderRecommendationsInputSchema
>;

const OptimizeServiceProviderRecommendationsOutputSchema = z.object({
  providerRecommendations: z
    .string()
    .describe(
      'A list of recommended service providers based on the client’s location, service type, and required specialization.'
    ),
});
export type OptimizeServiceProviderRecommendationsOutput = z.infer<
  typeof OptimizeServiceProviderRecommendationsOutputSchema
>;

export async function optimizeServiceProviderRecommendations(
  input: OptimizeServiceProviderRecommendationsInput
): Promise<OptimizeServiceProviderRecommendationsOutput> {
  return optimizeServiceProviderRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'optimizeServiceProviderRecommendationsPrompt',
  input: {schema: OptimizeServiceProviderRecommendationsInputSchema},
  output: {schema: OptimizeServiceProviderRecommendationsOutputSchema},
  prompt: `You are an AI assistant designed to provide optimized service provider recommendations for NDT (Non-Destructive Testing) services.

  Based on the client's location, the type of NDT service they need, and their specialization, provide a list of recommended service providers.

  Location: {{{location}}}
  Service Type: {{{serviceType}}}
  Specialization: {{{specialization}}}

  Provide a detailed recommendation with specific details for each provider, that will be used directly in the application.
  Example:
  ```json
  {
    "providerRecommendations": "[{\"providerName\": \"Provider A\", \"contactInfo\": \"(123) 456-7890\", \"rating\": 4.5, \"description\": \"Specializes in Ultrasonic Testing\"}, {\"providerName\": \"Provider B\", \"contactInfo\": \"(987) 654-3210\", \"rating\": 4.2, \"description\": \"Expert in Radiographic Testing\"}]"
  }
  ```
  Ensure the response is a valid JSON format. The service providers should be different each time.
  `,
});

const optimizeServiceProviderRecommendationsFlow = ai.defineFlow(
  {
    name: 'optimizeServiceProviderRecommendationsFlow',
    inputSchema: OptimizeServiceProviderRecommendationsInputSchema,
    outputSchema: OptimizeServiceProviderRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
