
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that provides optimized service provider recommendations.
 *
 * - optimizeServiceProviderRecommendations - A function that handles the recommendation process.
 * - OptimizeServiceProviderRecommendationsInput - The input type for the optimizeServiceProviderRecommendations function.
 * - OptimizeServiceProviderRecommendationsOutput - The return type for the optimizeServiceProviderRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import type { OptimizeServiceProviderRecommendationsInput as PublicInputType } from '@/lib/types'; // Import from lib/types

// Use the type from lib/types for the schema definition
const OptimizeServiceProviderRecommendationsInputSchema = z.object({
  location: z.string().describe('The location of the client.'),
  serviceType: z.string().describe('The type of NDT service needed.'),
  specialization: z.string().describe('The specialization required for the service (e.g., industry, material).'),
  standard: z.string().optional().describe('The inspection standard to be followed (e.g., ASME, API, ISO).'),
  assetToBeInspected: z.string().optional().describe('The specific asset or component that needs inspection (e.g., pipeline, pressure vessel, bridge component).'),
});
export type OptimizeServiceProviderRecommendationsInput = PublicInputType; // Export the type from lib/types


const OptimizeServiceProviderRecommendationsOutputSchema = z.object({
  providerRecommendations: z
    .string()
    .describe(
      'A list of recommended service providers based on the client’s location, service type, required specialization, standard, and asset. The list should be a JSON formatted string.'
    ),
});
export type OptimizeServiceProviderRecommendationsOutput = z.infer<
  typeof OptimizeServiceProviderRecommendationsOutputSchema
>;

export async function optimizeServiceProviderRecommendations(
  input: OptimizeServiceProviderRecommendationsInput
): Promise<OptimizeServiceProviderRecommendationsOutput> {
  return optimizeServiceProviderRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'optimizeServiceProviderRecommendationsPrompt',
  input: {schema: OptimizeServiceProviderRecommendationsInputSchema},
  output: {schema: OptimizeServiceProviderRecommendationsOutputSchema},
  prompt: `You are an AI assistant designed to provide optimized service provider recommendations for NDT (Non-Destructive Testing) services.

  Based on the client's requirements, provide a list of recommended service providers. Consider all provided details.

  Client Requirements:
  Location: {{{location}}}
  Service Type: {{{serviceType}}}
  Specialization/Industry: {{{specialization}}}
  {{#if standard}}
  Inspection Standard: {{{standard}}}
  {{/if}}
  {{#if assetToBeInspected}}
  Asset to be Inspected: {{{assetToBeInspected}}}
  {{/if}}

  Provide a detailed recommendation with specific details for each provider, that will be used directly in the application.
  The output must be a JSON formatted string. The key "providerRecommendations" should contain an array of provider objects.
  Each provider object should have "referenceId" (a unique mock ID like "ai-rec-1", "ai-rec-2"), "providerName", "contactInfo", "rating" (a number between 3.5 and 5.0), and "description".
  Example:
  {
    "providerRecommendations": "[{\"referenceId\": \"ai-rec-1\", \"providerName\": \"Advanced NDT Experts\", \"contactInfo\": \"(555) 123-4567\", \"rating\": 4.7, \"description\": \"Specializes in {{{serviceType}}} for {{{specialization}}} adhering to {{{standard}}} standards.\"}, {\"referenceId\": \"ai-rec-2\", \"providerName\": \"Precision Integrity Services\", \"contactInfo\": \"(555) 987-6543\", \"rating\": 4.3, \"description\": \"Expert in {{{serviceType}}} for inspecting {{{assetToBeInspected}}} in the {{{specialization}}} sector.\"}]"
  }
  Ensure the response is a valid JSON string. The service providers should be different and sound plausible for the given inputs. Generate 2 to 3 recommendations.
  `,
});

const optimizeServiceProviderRecommendationsFlow = ai.defineFlow(
  {
    name: 'optimizeServiceProviderRecommendationsFlow',
    inputSchema: OptimizeServiceProviderRecommendationsInputSchema,
    outputSchema: OptimizeServiceProviderRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
        throw new Error("AI failed to generate recommendations.");
    }
    // Ensure the output is valid by trying to parse it, though the final return is the string
    try {
      const parsedRecs = JSON.parse(output.providerRecommendations);
      // Basic validation for referenceId in the first recommendation if it exists
      if (Array.isArray(parsedRecs) && parsedRecs.length > 0 && typeof parsedRecs[0].referenceId === 'undefined') {
        console.warn("Generated recommendations are missing 'referenceId'.");
        // Potentially throw error or adjust data if referenceId is critical for all use cases
      }
    } catch (e) {
      console.error("Generated invalid JSON for recommendations:", output.providerRecommendations);
      throw new Error("AI generated invalid JSON. Please try again.");
    }
    return output;
  }
);

