
export type ClientProfileData = {
  companyName?: string;
  industry?: string;
  primaryLocation?: string;
  contactNumber?: string;
};

export type ServiceOffering = {
  id: string; // Unique key for UI lists (e.g., generated by Date.now() or a UUID)
  name: string; // Selected from a predefined list or "Other"
  rate: string; // Stored as string for input flexibility, parsed to number on save
  unit: string;
};

export type PersonnelQualification = {
  id: string; // For unique key
  quantity: number | string; // Allow string for flexible input
  certificationBody: string;
  level: string;
};

export type ProviderProfileData = {
  location?: string;
  lat?: number;
  lng?: number;
  servicesOffered?: ServiceOffering[];
  contactNumber?: string;
  pricingDetails?: string;
  procedureInfo?: string;
  acceptanceCriteriaInfo?: string;
  companyLogoUrl?: string;
  dataAiHint?: string; // Added for consistency if used with companyLogoUrl
  baseRate?: number;
  certifications?: string[];
  personnelQualifications?: PersonnelQualification[];
  isVerified?: boolean;
  availableDocuments?: string[];
};

export type User = {
  id: string;
  email: string;
  role: 'client' | 'provider' | 'admin';
  name?: string;
  isDemo?: boolean;
  clientProfile?: ClientProfileData;
  providerProfile?: ProviderProfileData;
};

export type ServiceProvider = {
  id:string;
  name: string; // This will be generic like "NDT Provider" initially for clients
  location: string;
  lat?: number;
  lng?: number;
  services: ServiceOffering[];
  specialization: string;
  rating: number;
  contactInfo: string; // Hidden from clients initially
  description?: string;
  imageUrl?: string;
  dataAiHint?: string;
  baseRate?: number;
  certifications?: string[];
  personnelQualifications?: PersonnelQualification[];
  isVerified?: boolean;
  availableDocuments?: string[];
};

export type OptimizeServiceProviderRecommendationsInput = {
  location: string;
  serviceType: string;
  specialization: string;
  standard?: string;
  assetToBeInspected?: string;
};

// For AI-generated recommendations, actual provider names/contacts are initially masked
export type Recommendation = {
  referenceId: string; // Mock ID like "ai-rec-1"
  providerName: string; // AI-generated plausible name, or "Recommended Provider X"
  contactInfo: string; // Generic or placeholder, or removed if too sensitive
  rating: number;
  description:string; // Detailed description from AI including hinted service, specialization
};

export type ServiceRequest = {
  id: string;
  clientId: string;
  providerId?: string;
  providerName?: string; // Name of provider if selected/assigned
  serviceType: string;
  location: string;
  description: string;
  requestedDate: string;
  estimatedCost?: number;
  status: 'Pending' | 'Confirmed' | 'In Progress' | 'Completed' | 'Cancelled';
};
