import type { PillarHubContent } from '../types';

const pillar: PillarHubContent = {
  slug: 'mfl-pipeline-inspection-pillar',
  metaTitle: 'MFL Pipeline Inspection [2026]: ILI Tool, Coverage, Cost, API 1163',
  metaDescription:
    'The complete magnetic flux leakage (MFL) pipeline inspection cluster — ILI tool physics, axial vs circumferential field, metal-loss sizing, API 1163 ILI validation, mileage cost ranges, and how MFL fits next to UT crawler and EMAT runs.',
  heroLede:
    'Magnetic flux leakage (MFL) is the workhorse in-line inspection (ILI) tool of the world\'s liquid and gas transmission pipelines — the technology behind roughly 75% of all integrity-management metal-loss runs operated by US pipeline companies under 49 CFR 195 (hazardous liquid) and 49 CFR 192 (natural gas). An MFL tool, run as part of a smart-pig train through a pipeline at typical line pressure, magnetises the pipe wall to near saturation and senses the flux that "leaks" past corrosion, gouges, or manufacturing defects. A typical MFL run on a 24-inch crude line covers 100–200 miles per launch, sizes wall-loss features down to 10% nominal wall thickness at 80% probability of detection (POD), and produces the call list the operator uses to schedule dig-and-verify excavations under API 1163. This hub maps the full MFL inspection cluster — the tool physics, the axial vs circumferential field debate, the API 1163 ILI validation framework, the per-mile cost ranges, and where MFL sits next to ultrasonic crawler runs (UT-CD) and EMAT for crack detection.',
  topicOverview:
    'MFL works by saturating the pipe wall with a strong axial magnetic field (typically generated by neodymium-iron-boron permanent magnets in the tool body) and reading the flux leakage with an array of hall-effect or coil sensors against the pipe ID. A corroded region has less ferrous material, so the flux re-routes out of the wall and into the sensor — the magnitude and shape of the leakage signal correlates to the depth, length, and width of the metal loss. There are three generations of MFL tooling in regular service. (1) Standard-resolution MFL — single axial field, calls metal loss but with ±15% depth sizing tolerance, used on lines where the operator already knows the dominant threat is general corrosion. (2) High-resolution MFL (HR-MFL) — denser sensor arrays, finer along-pipe sampling, depth tolerance tightens to ±10% and POD improves to ~80% at 10% wall loss. (3) Triaxial / TFI MFL — adds circumferential (transverse) and radial sensor channels to catch axially-oriented features (long seam corrosion, axial cracks under coating disbondment) that a pure axial-field MFL can miss because the leakage is hidden in the magnetisation axis. Most modern integrity programs spec triaxial HR-MFL as the baseline because the cost premium over single-axis HR-MFL is now in the 15–25% range and the extra confidence in axial-feature detection is decisive for line-pipe with ERW seams (where seam-weld colony corrosion is the dominant axial threat). MFL is one method in a stack — UT-CD (ultrasonic crawler in liquid couplant) detects internal corrosion and laminations with finer sizing; EMAT detects axial and circumferential cracks that MFL geometry cannot see; geometry / caliper tools catch dents and ovality; and the integrity-management plan (per API 1160 or ASME B31.8S) sequences these tools across a 5–10 year reassessment cycle. The output of an MFL run is fed through an ILI-vendor analysis package, validated against dig-and-verify confirmations per API 1163, and converted into a corrosion-rate model that drives the next inspection interval.',
  subPages: [
    {
      href: '/pillars/pipeline-inspection-pillar',
      label: 'Pipeline Integrity Inspection (parent)',
      description:
        'The wider pipeline-integrity cluster — ILI tool selection across MFL/UT/EMAT, API 1160/1163/1176, ASME B31.8S risk-based assessment, and the regulatory framework under 49 CFR 192/195.',
    },
    {
      href: '/pillars/corrosion-monitoring-pillar',
      label: 'Corrosion Monitoring & RBI',
      description:
        'How MFL run output feeds corrosion-rate trending, cathodic protection (CP) evaluation, and the risk-based inspection cycle.',
    },
    {
      href: '/methods/ultrasonic-testing',
      label: 'UT for Pipeline Wall Verification',
      description:
        'Above-ground UT verification of MFL call sites — the dig-and-confirm step that anchors MFL sizing per API 1163 §6.',
    },
    {
      href: '/standards/api-1104',
      label: 'API 1104 (Pipeline Welding Code)',
      description:
        'The companion welding code — pipeline construction and repair welds inspected to API 1104, often paired with MFL re-inspection after repair sleeves are installed.',
    },
    {
      href: '/tools/weld-cost',
      label: 'Weld Inspection Cost Calculator',
      description:
        'Per-joint cost estimator for the repair-weld inspection that follows an MFL dig-and-verify excavation.',
    },
    {
      href: '/tools/ut-coverage-grid',
      label: 'UT Coverage Grid (CML Sizing)',
      description:
        'For above-ground tie-ins where MFL cannot run, the API 570 CML grid sizing for piping UT thickness surveys.',
    },
  ],
  expertCommentary:
    'Three things separate a well-executed MFL program from one that leaves the operator surprised at a release. First, tool selection is a colony-vs-general-corrosion decision, not a default. Single-axis HR-MFL is genuinely fine for a clean pipeline whose dominant threat is uniform soil-side general corrosion; it is a liability on an ERW pipeline with selective seam corrosion, where axially-aligned features hide in the magnetisation axis and only a triaxial / TFI tool will see them. Second, API 1163 ILI validation is not paperwork. The standard requires a minimum number of dig-and-verify excavations per run (typically 12–20 depending on tool generation and pipeline length) and a statistical comparison of MFL-called depth to field-measured depth using the unity-line goodness-of-fit. Operators who run MFL without funding the validation excavations get a corrosion-rate model with no calibration — the next reassessment interval is built on a number nobody has tested. Third, MFL is blind to cracks. A pipeline with strain-induced cracking, SCC (stress-corrosion cracking), or fatigue cracking at girth welds needs EMAT or transverse-field-mode tooling — running pure MFL on that pipeline and seeing "no actionable findings" is a false-clean that gets quoted in the post-incident report. The integrity manager who sequences MFL with EMAT and UT-CD across a 5-year cycle, and who funds API 1163 validation on every run, produces a defensible inspection program. The one who runs MFL alone every five years and ticks the box is gambling.',
  externalResources: [
    { label: 'API 1163 — In-Line Inspection Systems Qualification, 3rd ed.', url: 'https://www.api.org/products-and-services/standards' },
    { label: 'API 1160 — Managing System Integrity for Hazardous Liquid Pipelines', url: 'https://www.api.org/products-and-services/standards' },
    { label: 'ASME B31.8S — Managing System Integrity of Gas Pipelines', url: 'https://www.asme.org/codes-standards' },
    { label: 'NACE SP0102 — In-Line Inspection of Pipelines', url: 'https://www.ampp.org/standards' },
    { label: 'PHMSA Pipeline Integrity Management Rules (49 CFR 192 / 195)', url: 'https://www.phmsa.dot.gov/regulations' },
  ],
  faqs: [
    {
      q: 'What does MFL pipeline inspection cost per mile in 2026?',
      a: 'Single-axis HR-MFL runs $4,500–$9,000 per mile in the US for 16-inch and larger lines, including launch/receive station mobilisation, cleaning pig passes, and the inline analysis report. Triaxial / TFI HR-MFL runs $6,000–$13,000 per mile. Smaller-diameter lines (8 inch and below) and short single-run isolations push per-mile cost up to $15,000–$25,000 because the fixed mobilisation cost amortises across fewer miles. International projects (Middle East, Australia) typically sit 25–60% higher due to logistics and equipment shipping. Combo tools (MFL + caliper + IMU in one train) reduce per-line cost when the operator needs multiple data types on the same run.',
    },
    {
      q: 'What is the difference between MFL and UT pipeline inspection?',
      a: 'MFL magnetises the pipe wall and senses flux leakage — it does not need a liquid couplant, runs in either gas or liquid lines, sizes metal-loss features with ±10% depth tolerance (HR-MFL), and is blind to laminations and cracks. UT crawler / UT-CD uses ultrasonic transducers and a liquid couplant (so it runs only in liquid lines like crude or refined products), sizes wall thickness with ±5% tolerance, and detects laminations and inclusions that MFL cannot see. The operator runs MFL for primary metal-loss inspection because of speed and gas-line compatibility, then runs UT-CD periodically (or as a follow-up validation tool) on critical sections to confirm MFL sizing and catch the lamination class of threats MFL misses. EMAT is the third tool in the stack and is specifically for crack detection.',
    },
    {
      q: 'What POD does an MFL tool achieve?',
      a: 'Probability of Detection (POD) for HR-MFL on metal-loss features in the 10–30% wall-loss range typically reports as 80–90% per ILI vendor specifications (BJ ROSEN, ROSEN, Baker Hughes, NDT Global, Quest Integrity), with the qualifying caveat that POD is a statistical claim against an idealised pull-test data set, not a field-validated number on the operator\'s line until API 1163 dig-and-verify cycles confirm it. Field-measured POD on a real pipeline with coating disbondment, complex geometry, and varying line pressure can sit 10–15 percentage points lower than the vendor lab number. Operators should report POD from their own validated runs in the integrity-management plan, not the vendor data sheet.',
    },
    {
      q: 'How often should a pipeline be MFL inspected?',
      a: 'The reassessment interval is set by the integrity-management program under API 1160 (liquid) or ASME B31.8S (gas), and is a function of measured corrosion rate, line-pressure operating envelope (the maximum allowable operating pressure / MAOP), and the risk category of the segment (High Consequence Area / HCA per 49 CFR). Typical intervals run 5–7 years for HCA segments on lines with measured general corrosion in the 1–3 mpy range, dropping to 3–4 years if corrosion is active or if a previous run found near-immediate-repair features. Lines outside HCAs and with low corrosion rates can extend to 10 years on operator-specific justification, but PHMSA audits these intervals carefully.',
    },
    {
      q: 'What does a typical MFL ILI report contain?',
      a: 'A standards-compliant MFL report (per API 1163 §5) includes: (a) the tool data set with run conditions (speed, magnetisation level, sensor health); (b) a feature list with location (chainage from launcher, girth-weld reference, clock position), feature type (metal loss / weld anomaly / geometry), and dimensions (length / width / depth as a percentage of nominal wall); (c) a severity ranking against ASME B31G or ModB31G burst-pressure criteria; (d) an immediate-repair feature list (those exceeding 80% wall loss or those that fail B31G); (e) a dig-and-verify excavation candidate list for API 1163 validation; and (f) the integrity-management input — a corrosion-rate distribution and a remaining-life prediction. The operator\'s integrity engineer then converts the report into excavation work orders, repair sleeves where required, and the next reassessment interval.',
    },
    {
      q: 'When should triaxial / TFI MFL be specified instead of single-axis HR-MFL?',
      a: 'Any line with ERW (electric resistance welded) or LF-ERW seams that has not been previously inspected for selective seam corrosion. Any line with documented history of axial-feature defects (long seam cracking, selective corrosion at the bond line). Any line where MFL is the ONLY ILI tool that will be run in the assessment cycle (because triaxial closes the axial-feature blind spot that justifies adding a UT-CD or EMAT run on a single-axis program). The cost premium for triaxial over single-axis HR-MFL is typically 15–25% in 2026 — small relative to the cost of missing an axial colony that fails the line.',
    },
  ],
  internalLinks: [
    { href: '/pillars/pipeline-inspection-pillar', label: 'Pipeline integrity inspection hub', context: 'pillar' },
    { href: '/pillars/corrosion-monitoring-pillar', label: 'Corrosion monitoring & RBI', context: 'pillar' },
    { href: '/methods/ultrasonic-testing', label: 'Ultrasonic testing method', context: 'method' },
    { href: '/standards/api-1104', label: 'API 1104 pipeline welding code', context: 'standard' },
    { href: '/standards/api-1163', label: 'API 1163 ILI qualification', context: 'standard' },
    { href: '/tools/ut-coverage-grid', label: 'UT coverage grid calculator', context: 'tool' },
    { href: '/tools/weld-cost', label: 'Weld inspection cost calculator', context: 'tool' },
  ],
  citations: [
    { id: 'api-1163', source: 'API 1163 — In-Line Inspection Systems Qualification, 3rd ed., 2021', url: 'https://www.api.org/products-and-services/standards' },
    { id: 'api-1160', source: 'API 1160 — Managing System Integrity for Hazardous Liquid Pipelines, 4th ed., 2021' },
    { id: 'asme-b31-8s', source: 'ASME B31.8S — Managing System Integrity of Gas Pipelines, 2022 ed.' },
    { id: 'nace-sp0102', source: 'NACE SP0102-2017 — In-Line Inspection of Pipelines' },
    { id: 'asme-b31g', source: 'ASME B31G-2012 — Manual for Determining the Remaining Strength of Corroded Pipelines' },
    { id: '49-cfr-195', source: 'US 49 CFR 195 — Transportation of Hazardous Liquids by Pipeline', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-D/part-195' },
    { id: '49-cfr-192', source: 'US 49 CFR 192 — Transportation of Natural and Other Gas by Pipeline', url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-D/part-192' },
  ],
};

export default pillar;
