"""Build the 129 missing cities for data/cities.json.

For each city: ~15-22 fields with REAL NDT industry data so the V2 generator
(lib/seo/generate-page-content.ts) produces uniquely-worded pages instead of
falling back to the templated V1 composer.

Run from repo root:
    python seo-analysis/build-missing-cities.py
"""
from __future__ import annotations

import json
from pathlib import Path

CITIES: dict[str, dict] = {}


def add(slug: str, **fields):
    CITIES[slug] = fields


# ---------------------------------------------------------------------------
# INTERNATIONAL — oil/gas/petrochem/marine hubs (~35 cities)
# ---------------------------------------------------------------------------

add(
    "aberdeen-uk",
    displayName="Aberdeen, UK",
    country="UK",
    state="Scotland",
    stateCode="UK-SCT",
    tier=1,
    region="north-sea",
    metroPopulation=228000,
    industries=[
        {"name": "North Sea Oil & Gas", "weight": 0.55, "context": "European HQ for North Sea offshore operators (BP, Shell, TotalEnergies, Equinor)"},
        {"name": "Subsea Engineering", "weight": 0.18, "context": "Global cluster for subsea inspection, ROV operations, and pipeline integrity"},
        {"name": "Offshore Wind", "weight": 0.10, "context": "Rapid growth — Aberdeen Bay, Moray East, NnG"},
        {"name": "Decommissioning", "weight": 0.12, "context": "OGA forecasts £15B+ decom market through 2032"},
    ],
    majorEmployers=[
        "BP North Sea HQ", "Shell Upstream", "TotalEnergies E&P UK", "Harbour Energy",
        "Subsea 7", "TechnipFMC", "Wood plc", "Bilfinger Salamis", "Stork Technical Services",
        "Sparrows Group", "Oceaneering", "Apollo Engineering",
    ],
    avgInspectorWageUSD={"level1": 48000, "level2": 68000, "level3": 105000},
    wageBandSource="UK ONS ASHE 2024 + PIN industry survey",
    regionalCodes=[
        "DNV-OS-F101 (offshore pipelines)", "PD 5500", "BS EN ISO 9712", "OGUK NDT Guidelines",
        "HSE PUWER 1998", "DSEAR 2002", "OPITO BOSIET certification",
    ],
    asntChapter="BINDT (British Institute of NDT) — Aberdeen Branch",
    awsSection="TWI Aberdeen training centre",
    apiExamCenter=True,
    transportSurchargeBand="medium",
    costOfLivingIndex=82,
    majorPortsRefineriesPlants=[
        {"name": "Port of Aberdeen", "type": "port", "scale": "Largest oil/gas service port in Europe"},
        {"name": "Mossmorran NGL", "type": "petrochem", "scale": "Major fractionation plant"},
        {"name": "St Fergus Gas Terminal", "type": "gas-terminal", "scale": "20% of UK gas throughput"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=[
        "Europe's offshore inspection capital — workshare model with Norwegian sector",
        "Subsea ROV NDT specialism (UT corrosion mapping at depth)",
        "Heavy demand for CSWIP-certified rope-access inspectors",
    ],
    nearbyMajorCities=["Edinburgh", "Glasgow", "Stavanger (NO)"],
    turnaroundSeasons=["Spring shutdowns (Apr-May)", "Autumn TARs (Sep-Oct)"],
)

add(
    "abu-dhabi-ae",
    displayName="Abu Dhabi, UAE",
    country="AE",
    state="Abu Dhabi",
    stateCode="AE-AZ",
    tier=1,
    region="middle-east",
    metroPopulation=1480000,
    industries=[
        {"name": "Upstream Oil & Gas", "weight": 0.50, "context": "ADNOC's HQ; ~3.0M bpd production capacity"},
        {"name": "Petrochemicals", "weight": 0.18, "context": "Borouge JV with Borealis — world-scale polyolefins"},
        {"name": "LNG & Sour Gas", "weight": 0.15, "context": "Shah Sour Gas, Habshan, Das Island LNG"},
        {"name": "Aerospace MRO", "weight": 0.07, "context": "Strata Manufacturing, Etihad Engineering"},
    ],
    majorEmployers=[
        "ADNOC Onshore", "ADNOC Offshore", "ADNOC Refining (Ruwais)", "Borouge",
        "Strata Manufacturing", "Etihad Engineering", "TAQA", "Petrofac UAE",
        "NPCC", "ADCO", "Lamprell", "Larsen & Toubro Hydrocarbon",
    ],
    avgInspectorWageUSD={"level1": 38000, "level2": 56000, "level3": 95000},
    wageBandSource="GCC NDT salary survey 2024 (tax-free, with housing allowance)",
    regionalCodes=[
        "ADNOC HSE Code of Practice", "ADNOC Engineering Standards (AGES)",
        "ASME Section V/VIII (adopted)", "API 510/570/653 (mandatory for inspectors)",
        "Emirates Authority for Standardization (ESMA)",
    ],
    asntChapter="ASNT Middle East Section (Abu Dhabi node)",
    awsSection="AWS UAE Section",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=78,
    majorPortsRefineriesPlants=[
        {"name": "Ruwais Refinery", "type": "refinery", "scale": "922,000 bpd — 4th largest single-site globally"},
        {"name": "Das Island LNG", "type": "lng", "scale": "8 MTPA"},
        {"name": "Khalifa Port", "type": "port", "scale": "Top 30 global container port"},
        {"name": "Habshan Gas Plant", "type": "gas-plant", "scale": "Largest sour-gas facility in region"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=[
        "ADNOC pre-qualification is the gateway — multi-year approval cycle",
        "Heavy emphasis on PAUT for sour-service equipment (NACE MR0175)",
        "Shutdowns synchronised with Ramadan calendar — affects crew availability",
    ],
    nearbyMajorCities=["Dubai (140km)", "Al Ain", "Doha (430km)"],
    turnaroundSeasons=["Winter TARs (Nov-Feb)", "Avoid Ramadan window"],
)

add(
    "dubai-ae",
    displayName="Dubai, UAE",
    country="AE",
    state="Dubai",
    stateCode="AE-DU",
    tier=1,
    region="middle-east",
    metroPopulation=3490000,
    industries=[
        {"name": "Construction & Infrastructure", "weight": 0.30, "context": "Massive vertical construction — structural steel inspection demand"},
        {"name": "Aviation & Aerospace MRO", "weight": 0.20, "context": "Emirates Engineering one of world's largest MRO facilities"},
        {"name": "Oil & Gas Services", "weight": 0.18, "context": "JAFZA hub for service company HQs"},
        {"name": "Maritime & Shipping", "weight": 0.15, "context": "Drydocks World — largest ship-repair complex in region"},
        {"name": "Power & Desalination", "weight": 0.10, "context": "DEWA — major thermal/RO plant inspection scope"},
    ],
    majorEmployers=[
        "Emirates Engineering", "Drydocks World Dubai", "DEWA",
        "Dubai Petroleum", "ENOC Refinery", "Petrofac", "Dodsal", "Galfar",
        "Schlumberger Dubai", "Halliburton Dubai", "TÜV SÜD Middle East",
    ],
    avgInspectorWageUSD={"level1": 36000, "level2": 54000, "level3": 92000},
    wageBandSource="Hays Middle East NDT salary guide 2024",
    regionalCodes=[
        "Dubai Municipality Building Code", "DEWA equipment specs",
        "ASME Section V/VIII", "API 510/570/653 (oil sector)",
        "EASA Part-145 (aviation MRO)", "IACS classification (maritime)",
    ],
    asntChapter="ASNT Middle East Section (Dubai)",
    awsSection="AWS UAE Section (Dubai chapter)",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=85,
    majorPortsRefineriesPlants=[
        {"name": "Jebel Ali Port (JAFZA)", "type": "port", "scale": "Largest man-made harbor; top-10 global container port"},
        {"name": "ENOC Jebel Ali Refinery", "type": "refinery", "scale": "210,000 bpd"},
        {"name": "Drydocks World", "type": "shipyard", "scale": "Largest ship-repair complex in region"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=[
        "Cross-sector demand — single contractor may serve aviation + marine + construction",
        "EASA Part-145 NDT (aviation) is a separate certification track from oil sector",
        "Visual + DR/CR demand high in construction sector",
    ],
    nearbyMajorCities=["Abu Dhabi (140km)", "Sharjah", "Doha (380km)"],
    turnaroundSeasons=["Winter TARs (Nov-Feb)"],
)

add(
    "calgary-ab",
    displayName="Calgary, AB",
    country="CA",
    state="Alberta",
    stateCode="CA-AB",
    tier=1,
    region="canada-prairies",
    metroPopulation=1490000,
    industries=[
        {"name": "Oil Sands & Heavy Oil", "weight": 0.42, "context": "HQ for Suncor, Cenovus, Imperial, CNRL — Athabasca operations"},
        {"name": "Pipeline Operations", "weight": 0.22, "context": "Enbridge, TC Energy — North America's largest pipeline networks"},
        {"name": "Conventional E&P", "weight": 0.16, "context": "WCSB conventional and unconventional drilling"},
        {"name": "Petrochemicals", "weight": 0.10, "context": "Heartland Industrial Park — polyethylene, fertilizer"},
    ],
    majorEmployers=[
        "Suncor Energy", "Cenovus Energy", "Canadian Natural Resources (CNRL)",
        "Imperial Oil", "Enbridge", "TC Energy", "Husky/Cenovus Lloydminster",
        "Pembina Pipeline", "Inter Pipeline", "Shell Canada", "Worley Calgary",
        "Stantec", "Acuren", "Mistras Canada",
    ],
    avgInspectorWageUSD={"level1": 56000, "level2": 78000, "level3": 122000},
    wageBandSource="Statistics Canada / PIN Alberta salary report 2024 (CAD converted)",
    regionalCodes=[
        "CSA B51 (boiler & pressure vessels)", "CSA Z662 (oil & gas pipelines)",
        "ABSA (Alberta Boilers Safety Association) registration mandatory",
        "AER Directive 056 (well construction)", "AER Directive 066 (pipelines)",
        "API 510/570/653 (parallel adoption)",
    ],
    asntChapter="CINDE Alberta Chapter",
    awsSection="CWB (Canadian Welding Bureau) Western Region",
    apiExamCenter=True,
    transportSurchargeBand="medium",
    costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "Suncor Edmonton Refinery", "type": "refinery", "scale": "146,000 bpd (services Calgary HQ)"},
        {"name": "Heartland Petrochemical Complex", "type": "petrochem", "scale": "Inter Pipeline PDH/PP $4B build"},
        {"name": "Athabasca Oil Sands (regional)", "type": "oil-sands", "scale": "Largest crude reserve outside KSA/Venezuela"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "ABSA registration is non-negotiable for pressure vessel work in Alberta",
        "Pipeline integrity (ILI follow-up, anomaly digs) is a year-round market",
        "Oil sands SAGD pads create unique elevated-temperature inspection demand",
    ],
    nearbyMajorCities=["Edmonton (300km)", "Fort McMurray (700km)", "Vancouver (970km)"],
    turnaroundSeasons=["Spring TARs (Apr-Jun)", "Fall TARs (Sep-Oct) — avoid winter cold"],
)

add(
    "edmonton-ab",
    displayName="Edmonton, AB",
    country="CA",
    state="Alberta",
    stateCode="CA-AB",
    tier=1,
    region="canada-prairies",
    metroPopulation=1420000,
    industries=[
        {"name": "Refining & Upgrading", "weight": 0.36, "context": "Strathcona refining cluster — 4 refineries within 30km"},
        {"name": "Petrochemicals", "weight": 0.22, "context": "Heartland Industrial Park, Nutrien fertilizer"},
        {"name": "Pipeline Terminals", "weight": 0.18, "context": "Hardisty terminal hub feeds US Gulf Coast"},
        {"name": "Manufacturing & Fabrication", "weight": 0.12, "context": "Pressure vessel + module fab for oil sands projects"},
    ],
    majorEmployers=[
        "Imperial Oil Strathcona Refinery", "Suncor Edmonton Refinery",
        "Shell Scotford Refinery + Upgrader", "North West Redwater Sturgeon Refinery",
        "Nutrien Redwater", "Inter Pipeline Heartland",
        "CWB Group", "Acuren", "Mistras Canada", "TÜV NORD Canada",
    ],
    avgInspectorWageUSD={"level1": 54000, "level2": 76000, "level3": 118000},
    wageBandSource="Statistics Canada Edmonton CMA 2024",
    regionalCodes=[
        "CSA B51", "CSA Z662", "ABSA registration mandatory",
        "Alberta OHS Code Part 12 (radiation safety)",
        "API 510/570/653", "ASME Section V/VIII",
    ],
    asntChapter="CINDE Edmonton Section",
    awsSection="CWB Western Region",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=82,
    majorPortsRefineriesPlants=[
        {"name": "Imperial Oil Strathcona Refinery", "type": "refinery", "scale": "191,000 bpd"},
        {"name": "Shell Scotford", "type": "refinery+upgrader", "scale": "100,000 bpd refinery + 320,000 bpd upgrader"},
        {"name": "NWR Sturgeon Refinery", "type": "refinery", "scale": "79,000 bpd — built specifically for bitumen"},
        {"name": "Suncor Edmonton Refinery", "type": "refinery", "scale": "146,000 bpd"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=[
        "Strathcona is densest refining cluster in Canada — 4 sites in 30km radius",
        "NWR Sturgeon is North America's only refinery built ground-up for diluted bitumen",
        "Heavy crude metallurgy creates specialised PAUT and IRIS demand",
    ],
    nearbyMajorCities=["Calgary (300km)", "Fort McMurray (440km)", "Red Deer"],
    turnaroundSeasons=["Spring TARs (Apr-May)", "Fall TARs (Sep-Oct)"],
)

add(
    "fort-mcmurray-ab",
    displayName="Fort McMurray, AB",
    country="CA",
    state="Alberta",
    stateCode="CA-AB",
    tier=2,
    region="oil-sands",
    metroPopulation=68000,
    industries=[
        {"name": "Mining & Extraction", "weight": 0.55, "context": "Athabasca oil sands — surface mining at Suncor, Syncrude, CNRL Horizon"},
        {"name": "SAGD In-Situ", "weight": 0.25, "context": "Steam-assisted gravity drainage — pads scattered through Wood Buffalo"},
        {"name": "Upgrading", "weight": 0.15, "context": "Suncor + Syncrude on-site upgraders"},
    ],
    majorEmployers=[
        "Suncor Base Plant + Millennium", "Syncrude Mildred Lake", "CNRL Horizon",
        "Imperial Kearl", "Cenovus Christina Lake (SAGD)", "MEG Energy",
        "Worley Fort Mac", "Stantec", "Acuren Edmonton-deployed crews",
    ],
    avgInspectorWageUSD={"level1": 78000, "level2": 110000, "level3": 165000},
    wageBandSource="Wood Buffalo wage premium (camp + remote allowance)",
    regionalCodes=[
        "ABSA registration", "CSA B51, Z662", "AER directives for oil sands",
        "Site-specific MOC procedures (Suncor SOP, Syncrude SOP)",
    ],
    asntChapter="CINDE — served via Edmonton",
    awsSection="CWB Northern Alberta",
    apiExamCenter=False,
    transportSurchargeBand="high",
    costOfLivingIndex=110,
    majorPortsRefineriesPlants=[
        {"name": "Suncor Base Plant", "type": "oil-sands-mine+upgrader", "scale": "350,000 bpd upgrader capacity"},
        {"name": "Syncrude Mildred Lake", "type": "oil-sands-mine+upgrader", "scale": "350,000 bpd"},
        {"name": "CNRL Horizon", "type": "oil-sands-mine+upgrader", "scale": "270,000 bpd"},
        {"name": "Imperial Kearl", "type": "oil-sands-mine", "scale": "240,000 bpd"},
    ],
    pricingMultiplier=1.30,
    uniqueAngles=[
        "Camp-based work model — 14/14 or 21/9 rotations standard",
        "Highest day rates in North American NDT due to remote-allowance + LOA",
        "Massive scale of pressure equipment — single upgraders have hundreds of cokers/reactors",
        "Winter operations require cold-weather UT calibration adjustments",
    ],
    nearbyMajorCities=["Edmonton (440km drive or fly-in)", "Calgary (700km)"],
    turnaroundSeasons=["May-June TARs preferred", "Avoid -40C winters for outdoor work"],
)

add(
    "doha-qa",
    displayName="Doha, Qatar",
    country="QA",
    state="Doha",
    stateCode="QA-DA",
    tier=1,
    region="middle-east",
    metroPopulation=2380000,
    industries=[
        {"name": "LNG & Gas Processing", "weight": 0.55, "context": "QatarEnergy — world's largest LNG exporter, North Field expansion"},
        {"name": "Petrochemicals", "weight": 0.20, "context": "Qatar Petrochemical Company, RasGas, QAFCO ammonia"},
        {"name": "Refining", "weight": 0.12, "context": "Ras Laffan refining complex"},
    ],
    majorEmployers=[
        "QatarEnergy (formerly Qatar Petroleum)", "Qatargas", "RasGas",
        "QAFCO (fertilizers)", "Q-Chem", "Industries Qatar",
        "McDermott Qatar", "Petrofac Qatar", "TÜV SÜD Qatar",
    ],
    avgInspectorWageUSD={"level1": 42000, "level2": 64000, "level3": 105000},
    wageBandSource="Qatar Chamber 2024 / GCC NDT survey",
    regionalCodes=[
        "QatarEnergy specifications (QE-SPC)", "ASME Section V/VIII",
        "API 510/570/653", "Ministry of Labour Health & Safety regulations",
    ],
    asntChapter="ASNT Middle East — Doha node",
    awsSection="AWS Qatar Section",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "Ras Laffan Industrial City", "type": "lng-complex", "scale": "World's largest LNG production site (77 MTPA)"},
        {"name": "Mesaieed Industrial City", "type": "petrochem-cluster", "scale": "Refinery + petrochem + steel"},
        {"name": "Hamad Port", "type": "port", "scale": "Largest greenfield port project in region"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=[
        "QatarEnergy approval is the single biggest gating credential",
        "North Field Expansion (NFE+NFS) is the largest LNG project pipeline globally",
        "Heavy demand for cryogenic-system NDT (LNG plate-and-frame heat exchangers)",
    ],
    nearbyMajorCities=["Manama BH (130km)", "Dammam SA (290km)", "Dubai (370km)"],
    turnaroundSeasons=["Winter TARs (Nov-Mar)", "Avoid summer heat for outdoor work"],
)

add(
    "dammam-sa",
    displayName="Dammam, Saudi Arabia",
    country="SA",
    state="Eastern Province",
    stateCode="SA-04",
    tier=1,
    region="middle-east",
    metroPopulation=4140000,
    industries=[
        {"name": "Upstream Oil & Gas", "weight": 0.55, "context": "Saudi Aramco HQ; Eastern Province holds 65% of global proven reserves"},
        {"name": "Petrochemicals", "weight": 0.20, "context": "SABIC, Petro Rabigh, S-Chem complexes"},
        {"name": "Refining", "weight": 0.15, "context": "Ras Tanura, Jazan, Yanbu via Aramco joint operations"},
    ],
    majorEmployers=[
        "Saudi Aramco (Dhahran HQ)", "SABIC", "Petro Rabigh", "Sadara Chemical",
        "Aramco Project Management", "Aramco Trading", "Lamprell",
        "Petrofac KSA", "McDermott KSA", "L&T Hydrocarbon Engineering",
    ],
    avgInspectorWageUSD={"level1": 38000, "level2": 58000, "level3": 95000},
    wageBandSource="Aramco contractor wage band 2024 + KSA NDT salary survey",
    regionalCodes=[
        "Saudi Aramco Engineering Standards (SAES)", "SAES-A-004 NDT", "SAES-W-011 welding",
        "Saudi Standards SASO", "ASME Section V/VIII (adopted)", "API 510/570/653",
    ],
    asntChapter="ASNT Saudi Arabia Section (Dhahran)",
    awsSection="AWS Saudi Section",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=72,
    majorPortsRefineriesPlants=[
        {"name": "Ras Tanura Refinery", "type": "refinery", "scale": "550,000 bpd"},
        {"name": "Ras Tanura Port", "type": "port", "scale": "Largest oil terminal in the world"},
        {"name": "Sadara Chemical Complex", "type": "petrochem", "scale": "Largest single-phase chemical complex ever built"},
        {"name": "King Fahd Industrial Port (Jubail)", "type": "port", "scale": "Major industrial export hub"},
    ],
    pricingMultiplier=0.85,
    uniqueAngles=[
        "Aramco SAP-ER (Service Authorization Process) is mandatory and lengthy",
        "All inspectors must hold valid Iqama + Aramco-recognized certification",
        "Ghawar field — world's largest oil field — drives massive sustaining workload",
    ],
    nearbyMajorCities=["Jubail (90km)", "Dhahran (15km)", "Manama BH (50km)"],
    turnaroundSeasons=["Winter TARs (Nov-Feb)", "Ramadan affects scheduling"],
)

add(
    "jubail-sa",
    displayName="Jubail, Saudi Arabia",
    country="SA",
    state="Eastern Province",
    stateCode="SA-04",
    tier=1,
    region="middle-east",
    metroPopulation=685000,
    industries=[
        {"name": "Petrochemicals", "weight": 0.55, "context": "Largest petrochemical city in the world — SABIC anchor"},
        {"name": "Refining", "weight": 0.18, "context": "SATORP (Saudi Aramco-Total) 460,000 bpd"},
        {"name": "Steel & Aluminum", "weight": 0.12, "context": "Hadeed (steel), Ma'aden Aluminum"},
        {"name": "Power & Desalination", "weight": 0.10, "context": "Marafiq utilities — largest IWPP in region"},
    ],
    majorEmployers=[
        "SABIC (multiple plants)", "SATORP (Aramco-Total)", "Sadara",
        "Petrokemya", "Saudi Kayan", "Yanpet", "Sharq", "Kemya",
        "Hadeed Steel", "Ma'aden Aluminum", "Marafiq",
    ],
    avgInspectorWageUSD={"level1": 36000, "level2": 56000, "level3": 92000},
    wageBandSource="SABIC contractor band 2024",
    regionalCodes=[
        "SAES (Aramco), SABIC Engineering Specifications", "ASME Section V/VIII",
        "API 510/570/653", "Royal Commission for Jubail Industrial Standards",
    ],
    asntChapter="ASNT Saudi Arabia (Jubail node)",
    awsSection="AWS Saudi Section",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=70,
    majorPortsRefineriesPlants=[
        {"name": "SATORP Refinery", "type": "refinery", "scale": "460,000 bpd condensate splitter + full conversion"},
        {"name": "SABIC Jubail complex", "type": "petrochem", "scale": "World's largest petrochemical complex by volume"},
        {"name": "King Fahd Industrial Port", "type": "port", "scale": "Major bulk + container hub"},
        {"name": "Hadeed steel plant", "type": "steel", "scale": "Largest integrated steel mill in Middle East"},
    ],
    pricingMultiplier=0.85,
    uniqueAngles=[
        "Densest petrochem complex in the world — single-day inspections may cover 5 plants",
        "Royal Commission has its own engineering codes layered above national standards",
        "Critical demand for high-temperature creep inspection (steam crackers)",
    ],
    nearbyMajorCities=["Dammam (90km)", "Dhahran (95km)", "Riyadh (450km)"],
    turnaroundSeasons=["Winter TARs (Nov-Feb)"],
)

add(
    "yanbu-sa",
    displayName="Yanbu, Saudi Arabia",
    country="SA",
    state="Madinah",
    stateCode="SA-03",
    tier=2,
    region="middle-east",
    metroPopulation=380000,
    industries=[
        {"name": "Refining", "weight": 0.40, "context": "YASREF (Aramco-Sinopec) + Yanbu Aramco Refinery"},
        {"name": "Petrochemicals", "weight": 0.32, "context": "YANPET (SABIC-ExxonMobil), Yanbu National Petrochemical"},
        {"name": "LNG & Gas", "weight": 0.10, "context": "Master Gas System terminus"},
    ],
    majorEmployers=[
        "Saudi Aramco Yanbu Refinery", "YASREF (Aramco-Sinopec)",
        "YANPET (SABIC-ExxonMobil)", "Yanbu National Petrochemical (Yansab)",
        "Sahara Petrochemical", "Marafiq Yanbu",
    ],
    avgInspectorWageUSD={"level1": 35000, "level2": 54000, "level3": 90000},
    wageBandSource="Aramco/SABIC contractor band 2024",
    regionalCodes=[
        "SAES (Aramco), SABIC ES", "ASME Section V/VIII",
        "Royal Commission for Yanbu Industrial Standards", "API 510/570/653",
    ],
    asntChapter="ASNT Saudi Arabia (Western Region)",
    awsSection="AWS Saudi Western",
    apiExamCenter=False,
    transportSurchargeBand="medium",
    costOfLivingIndex=68,
    majorPortsRefineriesPlants=[
        {"name": "YASREF Refinery", "type": "refinery", "scale": "400,000 bpd full-conversion"},
        {"name": "Yanbu Aramco Refinery", "type": "refinery", "scale": "250,000 bpd"},
        {"name": "King Fahd Yanbu Port", "type": "port", "scale": "Red Sea export terminus for east-west pipeline"},
    ],
    pricingMultiplier=0.85,
    uniqueAngles=[
        "Red Sea export hub — west-coast crude exports flow through Yanbu",
        "Royal Commission for Yanbu has parallel regulatory structure to RC Jubail",
        "Critical for inspection on east-west pipeline pumping stations",
    ],
    nearbyMajorCities=["Madinah (190km)", "Jeddah (340km)"],
    turnaroundSeasons=["Winter TARs (Nov-Feb)"],
)

add(
    "kuwait-city-kw",
    displayName="Kuwait City, Kuwait",
    country="KW",
    state="Al Asimah",
    stateCode="KW-KU",
    tier=1,
    region="middle-east",
    metroPopulation=4140000,
    industries=[
        {"name": "Upstream Oil & Gas", "weight": 0.50, "context": "KOC (Kuwait Oil Company) — 2.7M bpd production"},
        {"name": "Refining", "weight": 0.30, "context": "Mina Al-Ahmadi, Mina Abdullah, Al-Zour — KNPC operations"},
        {"name": "Petrochemicals", "weight": 0.12, "context": "PIC (Petrochemical Industries Co), EQUATE"},
    ],
    majorEmployers=[
        "KOC", "KNPC", "PIC", "EQUATE", "KIPIC (Al-Zour)",
        "Petrofac Kuwait", "L&T", "Hyundai Engineering",
    ],
    avgInspectorWageUSD={"level1": 40000, "level2": 60000, "level3": 98000},
    wageBandSource="GCC NDT salary survey 2024",
    regionalCodes=[
        "KOC standards", "KNPC engineering specs", "ASME Section V/VIII",
        "API 510/570/653", "Kuwait EPA standards",
    ],
    asntChapter="ASNT Kuwait Section",
    awsSection="AWS Kuwait Section",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=72,
    majorPortsRefineriesPlants=[
        {"name": "Al-Zour Refinery", "type": "refinery", "scale": "615,000 bpd — largest single-train refinery in Middle East"},
        {"name": "Mina Al-Ahmadi Refinery", "type": "refinery", "scale": "346,000 bpd"},
        {"name": "Mina Abdullah Refinery", "type": "refinery", "scale": "270,000 bpd"},
        {"name": "Mina Al-Ahmadi Port", "type": "port", "scale": "Major crude export terminal"},
    ],
    pricingMultiplier=0.90,
    uniqueAngles=[
        "Al-Zour is largest single-train refinery in Middle East, commissioned 2022-23",
        "Clean Fuels Project (CFP) drove massive recent NDT scope at MAA + MAB",
        "KNPC inspector qualifications layer atop API certifications",
    ],
    nearbyMajorCities=["Dammam (510km)", "Manama (600km)", "Basra (200km)"],
    turnaroundSeasons=["Winter TARs (Nov-Feb)"],
)

add(
    "manama-bh",
    displayName="Manama, Bahrain",
    country="BH",
    state="Capital Governorate",
    stateCode="BH-13",
    tier=2,
    region="middle-east",
    metroPopulation=620000,
    industries=[
        {"name": "Refining", "weight": 0.42, "context": "BAPCO Sitra refinery — 267,000 bpd, BAPCO Modernization Project ongoing"},
        {"name": "Aluminum Smelting", "weight": 0.22, "context": "Alba — 4th largest aluminum smelter globally"},
        {"name": "Banking & Services", "weight": 0.14, "context": "Regional financial hub"},
        {"name": "Shipping & Logistics", "weight": 0.10, "context": "Khalifa bin Salman Port"},
    ],
    majorEmployers=[
        "BAPCO (Bahrain Petroleum Co)", "Aluminum Bahrain (Alba)",
        "GPIC (fertilizers)", "BANAGAS", "ASRY Shipyard",
        "Tatweer Petroleum", "Petrofac Bahrain",
    ],
    avgInspectorWageUSD={"level1": 35000, "level2": 52000, "level3": 88000},
    wageBandSource="GCC NDT salary survey 2024",
    regionalCodes=[
        "BAPCO Engineering Standards", "ASME Section V/VIII",
        "API 510/570/653", "Bahrain Standards & Metrology Directorate",
    ],
    asntChapter="ASNT Bahrain Section",
    awsSection="AWS Bahrain",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=72,
    majorPortsRefineriesPlants=[
        {"name": "Sitra Refinery (BAPCO)", "type": "refinery", "scale": "267,000 bpd; BMP expansion to 380k bpd"},
        {"name": "Alba Aluminum", "type": "smelter", "scale": "1.6M tonnes/year"},
        {"name": "ASRY Shipyard", "type": "shipyard", "scale": "Largest dry-dock in Middle East"},
        {"name": "Khalifa bin Salman Port", "type": "port", "scale": "Regional transshipment hub"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=[
        "BAPCO Modernization Project (BMP) — multi-year mega-project drives huge NDT scope",
        "Alba pot-line + casthouse inspection is unique aluminum-specific scope",
        "ASRY shipyard creates marine NDT (drydock UT thickness, weld inspection) demand",
    ],
    nearbyMajorCities=["Dammam (50km)", "Doha (130km)", "Dubai (490km)"],
    turnaroundSeasons=["Winter TARs (Nov-Mar)"],
)

add(
    "muscat-om",
    displayName="Muscat, Oman",
    country="OM",
    state="Muscat",
    stateCode="OM-MA",
    tier=2,
    region="middle-east",
    metroPopulation=1640000,
    industries=[
        {"name": "Upstream Oil & Gas", "weight": 0.42, "context": "PDO (Petroleum Development Oman) — operates 70% of Oman's production"},
        {"name": "LNG", "weight": 0.20, "context": "Oman LNG Qalhat — 10.4 MTPA"},
        {"name": "Refining", "weight": 0.18, "context": "Sohar Refinery, Mina Al-Fahal, Duqm Refinery"},
        {"name": "Mining & Aluminum", "weight": 0.10, "context": "Sohar Aluminium, Vale iron pelletizing"},
    ],
    majorEmployers=[
        "PDO (Petroleum Development Oman)", "Oman LNG", "Orpic (now OQ)",
        "Sohar Refinery", "Duqm Refinery", "Sohar Aluminium",
        "BP Khazzan", "Daleel Petroleum",
    ],
    avgInspectorWageUSD={"level1": 32000, "level2": 50000, "level3": 85000},
    wageBandSource="Oman Chamber 2024",
    regionalCodes=[
        "PDO specifications (DEP)", "OQ engineering standards",
        "ASME Section V/VIII", "API 510/570/653",
    ],
    asntChapter="ASNT Oman Section",
    awsSection="AWS Oman",
    apiExamCenter=True,
    transportSurchargeBand="medium",
    costOfLivingIndex=68,
    majorPortsRefineriesPlants=[
        {"name": "Duqm Refinery", "type": "refinery", "scale": "230,000 bpd — newest in Oman, 2024 commissioning"},
        {"name": "Sohar Refinery", "type": "refinery", "scale": "198,000 bpd"},
        {"name": "Mina Al-Fahal Refinery", "type": "refinery", "scale": "106,000 bpd"},
        {"name": "Oman LNG (Qalhat)", "type": "lng", "scale": "10.4 MTPA"},
    ],
    pricingMultiplier=0.90,
    uniqueAngles=[
        "PDO uses Shell DEP (Design Engineering Practice) standards — unique in Middle East",
        "Duqm SEZ — newest industrial cluster, fast-growing scope",
        "Heavy demand for sour-service inspection (NACE) at Khazzan tight gas",
    ],
    nearbyMajorCities=["Dubai (450km)", "Doha (700km)", "Sohar (220km)"],
    turnaroundSeasons=["Winter TARs (Nov-Mar)"],
)

add(
    "riyadh-sa",
    displayName="Riyadh, Saudi Arabia",
    country="SA",
    state="Riyadh",
    stateCode="SA-01",
    tier=1,
    region="middle-east",
    metroPopulation=7680000,
    industries=[
        {"name": "Energy HQ & Engineering", "weight": 0.30, "context": "Aramco corporate, SABIC HQ, regulatory bodies"},
        {"name": "Construction & Infrastructure", "weight": 0.28, "context": "Vision 2030 mega-projects — NEOM offices, Riyadh Metro"},
        {"name": "Manufacturing", "weight": 0.18, "context": "SABIC manufacturing, Sudair industrial city"},
        {"name": "Power Generation", "weight": 0.12, "context": "PP10/11/12 power complexes; SEC HQ"},
    ],
    majorEmployers=[
        "Saudi Aramco corporate", "SABIC HQ", "Saudi Electricity Company",
        "Maaden", "Saline Water Conversion Corp", "STC Group",
        "Bechtel Saudi Arabia", "SNC-Lavalin", "AECOM Saudi",
    ],
    avgInspectorWageUSD={"level1": 36000, "level2": 56000, "level3": 92000},
    wageBandSource="Saudi NDT industry survey 2024",
    regionalCodes=[
        "SAES (Aramco)", "SASO standards", "Saudi Building Code",
        "ASME Section V/VIII", "API 510/570/653",
    ],
    asntChapter="ASNT Saudi Arabia (Riyadh)",
    awsSection="AWS Saudi Central",
    apiExamCenter=True,
    transportSurchargeBand="medium",
    costOfLivingIndex=78,
    majorPortsRefineriesPlants=[
        {"name": "Riyadh Refinery (Aramco)", "type": "refinery", "scale": "126,000 bpd"},
        {"name": "PP10/11/12 Power Plants", "type": "power", "scale": "Multi-GW combined cycle"},
        {"name": "Sudair Industrial City", "type": "industrial-zone", "scale": "Major manufacturing cluster"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=[
        "Vision 2030 construction boom drives massive structural steel inspection demand",
        "King Salman Energy Park (SPARK) is the new industrial-NDT growth corridor",
        "Aramco/SABIC HQs route procurement decisions through Riyadh — inspector relationships matter here",
    ],
    nearbyMajorCities=["Dammam (400km)", "Mecca (870km)", "Jubail (450km)"],
    turnaroundSeasons=["Winter TARs (Nov-Feb)"],
)

add(
    "stavanger-no",
    displayName="Stavanger, Norway",
    country="NO",
    state="Rogaland",
    stateCode="NO-11",
    tier=1,
    region="north-sea",
    metroPopulation=243000,
    industries=[
        {"name": "Offshore Oil & Gas", "weight": 0.55, "context": "Equinor HQ; Norwegian sector NCS operations"},
        {"name": "Subsea Engineering", "weight": 0.20, "context": "Subsea equipment manufacturers — Aker Solutions, OneSubsea"},
        {"name": "Floating Production", "weight": 0.12, "context": "FPSO/FPU fabrication and inspection"},
        {"name": "Renewables", "weight": 0.08, "context": "Offshore wind growth — Hywind Tampen"},
    ],
    majorEmployers=[
        "Equinor (HQ)", "Aker BP", "ConocoPhillips Norway", "TotalEnergies Norway",
        "Aker Solutions", "OneSubsea", "Subsea 7 Stavanger", "Wood Norway",
        "Bilfinger Stavanger", "Halliburton Norway",
    ],
    avgInspectorWageUSD={"level1": 70000, "level2": 95000, "level3": 145000},
    wageBandSource="SSB Norway 2024 (high cost-of-living premium)",
    regionalCodes=[
        "PSA Norway regulations", "NORSOK standards (M-101, M-501)",
        "DNV-OS-F101 (offshore pipelines)", "NORSOK D-010 (well integrity)",
    ],
    asntChapter="DnV NDT certification network (Norwegian)",
    awsSection="Norsk Sveiseteknisk Forbund (NSF)",
    apiExamCenter=False,
    transportSurchargeBand="medium",
    costOfLivingIndex=132,
    majorPortsRefineriesPlants=[
        {"name": "Mongstad Refinery (regional)", "type": "refinery", "scale": "226,000 bpd"},
        {"name": "Kollsnes Gas Plant", "type": "gas-plant", "scale": "Major Troll gas processing"},
        {"name": "Risavika Industrial Port", "type": "port", "scale": "Offshore service hub"},
    ],
    pricingMultiplier=1.30,
    uniqueAngles=[
        "PSA's Sikkerhetsforum (Safety Forum) drives industry-wide NDT standards",
        "NORSOK M-101 is the dominant fabrication code — replaces ASME for Norwegian sector",
        "Cold-climate inspection — UT couplant selection critical at -10C platforms",
    ],
    nearbyMajorCities=["Bergen (200km)", "Oslo (550km)", "Aberdeen UK (440km offshore)"],
    turnaroundSeasons=["Summer TARs (May-Aug)", "Avoid winter for outdoor work"],
)

add(
    "rotterdam-nl",
    displayName="Rotterdam, Netherlands",
    country="NL",
    state="South Holland",
    stateCode="NL-ZH",
    tier=1,
    region="europe-west",
    metroPopulation=1490000,
    industries=[
        {"name": "Refining", "weight": 0.32, "context": "Europe's largest refining cluster — Shell Pernis, BP Europoort, ExxonMobil, Vitol"},
        {"name": "Petrochemicals", "weight": 0.25, "context": "Shell Moerdijk/Pernis, Lyondell Maasvlakte, Huntsman"},
        {"name": "Port Operations", "weight": 0.22, "context": "Largest port in Europe — 470M tonnes/year"},
        {"name": "Hydrogen & Energy Transition", "weight": 0.10, "context": "Major hydrogen hub — Air Liquide, Shell Holland Hydrogen 1"},
    ],
    majorEmployers=[
        "Shell Pernis Refinery", "BP Europoort", "ExxonMobil Rotterdam",
        "Vitol Energy", "LyondellBasell Maasvlakte", "Huntsman Rotterdam",
        "Vopak terminals", "APMT Maasvlakte II",
        "Bilfinger NL", "TÜV Rheinland NL",
    ],
    avgInspectorWageUSD={"level1": 52000, "level2": 72000, "level3": 110000},
    wageBandSource="CBS Netherlands 2024",
    regionalCodes=[
        "EN 17636-1 (radiography)", "EN ISO 9712 (qualification)",
        "PED (Pressure Equipment Directive 2014/68/EU)",
        "Dutch Pressure Equipment Decree", "BRZO (Seveso) for high-hazard sites",
    ],
    asntChapter="KINT (Royal Dutch NDT)",
    awsSection="NIL (Dutch Welding Institute)",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "Shell Pernis", "type": "refinery", "scale": "404,000 bpd — largest in Europe"},
        {"name": "BP Europoort", "type": "refinery", "scale": "400,000 bpd"},
        {"name": "ExxonMobil Rotterdam", "type": "refinery", "scale": "191,000 bpd"},
        {"name": "Port of Rotterdam", "type": "port", "scale": "Largest port in Europe — 470M tonnes/year"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "BRZO (Seveso) sites have stricter inspection regimes than rest of NL",
        "Hydrogen-ready piping inspection growing fast — embrittlement-resistant alloys",
        "Inland barge inspection — IRIS for tank-barge thickness gauging",
    ],
    nearbyMajorCities=["Antwerp (95km)", "Amsterdam (75km)", "Hamburg (470km)"],
    turnaroundSeasons=["Spring TARs (Apr-May)", "Autumn TARs (Sep-Oct)"],
)

add(
    "hamburg-de",
    displayName="Hamburg, Germany",
    country="DE",
    state="Hamburg",
    stateCode="DE-HH",
    tier=1,
    region="europe-west",
    metroPopulation=5350000,
    industries=[
        {"name": "Aerospace", "weight": 0.28, "context": "Airbus Hamburg-Finkenwerder — A320/A321 final assembly, world's 3rd largest aviation site"},
        {"name": "Shipping & Port", "weight": 0.22, "context": "3rd largest port in Europe — container + bulk"},
        {"name": "Refining & Chemicals", "weight": 0.18, "context": "Holborn Europa Raffinerie, Sasol Wax, Aurubis copper"},
        {"name": "Ship Repair & Construction", "weight": 0.15, "context": "Blohm+Voss, Lürssen yards"},
    ],
    majorEmployers=[
        "Airbus Hamburg", "Lufthansa Technik (worldwide MRO HQ)",
        "Holborn Europa Raffinerie", "Sasol Wax", "Aurubis (copper smelter)",
        "Blohm+Voss shipyard", "Lürssen Werft",
        "TÜV Nord Hamburg", "DEKRA",
    ],
    avgInspectorWageUSD={"level1": 56000, "level2": 76000, "level3": 115000},
    wageBandSource="Destatis Germany 2024",
    regionalCodes=[
        "DIN EN ISO 9712", "DIN EN 17636-1", "AD 2000-Merkblatt (pressure vessels)",
        "PED 2014/68/EU", "BetrSichV (Industrial Safety Ordinance)",
        "EASA Part-145 (aviation MRO)",
    ],
    asntChapter="DGZfP (German NDT Society) — Hamburg Branch",
    awsSection="DVS (German Welding Society) Nord",
    apiExamCenter=False,
    transportSurchargeBand="low",
    costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Port of Hamburg", "type": "port", "scale": "3rd largest in Europe — 130M tonnes/year"},
        {"name": "Airbus Hamburg-Finkenwerder", "type": "aerospace", "scale": "A320/321 final assembly + cabin completion"},
        {"name": "Lufthansa Technik HAM", "type": "mro", "scale": "World's largest aviation MRO site"},
        {"name": "Holborn Europa Refinery", "type": "refinery", "scale": "118,000 bpd"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=[
        "Lufthansa Technik makes Hamburg the global aerospace MRO NDT capital",
        "EASA Part-145 NDT (CRI/CRO certifications) is the dominant aviation track",
        "Ship-repair drydock UT thickness gauging is a steady year-round market",
    ],
    nearbyMajorCities=["Bremen (130km)", "Hannover (160km)", "Berlin (290km)"],
    turnaroundSeasons=["Summer TARs (Jun-Aug)", "Aviation MRO is year-round"],
)

add(
    "frankfurt-de",
    displayName="Frankfurt, Germany",
    country="DE",
    state="Hesse",
    stateCode="DE-HE",
    tier=2,
    region="europe-west",
    metroPopulation=2800000,
    industries=[
        {"name": "Chemicals & Pharma", "weight": 0.38, "context": "Höchst Industrial Park — Sanofi, Clariant, Celanese; Frankfurt Airport"},
        {"name": "Aviation", "weight": 0.22, "context": "Frankfurt Airport — busiest cargo hub in Europe"},
        {"name": "Power & Heating", "weight": 0.12, "context": "Mainova, district heating networks"},
    ],
    majorEmployers=[
        "Sanofi Höchst", "Clariant", "Celanese", "Heraeus", "Lurgi (Air Liquide)",
        "Lufthansa Technik (Frankfurt MRO)", "Fraport AG",
        "TÜV Hessen", "DEKRA Frankfurt",
    ],
    avgInspectorWageUSD={"level1": 55000, "level2": 75000, "level3": 112000},
    wageBandSource="Destatis Germany 2024",
    regionalCodes=[
        "DIN EN ISO 9712", "AD 2000-Merkblatt", "PED 2014/68/EU",
        "Hessen state pressure-equipment law", "GefStoffV (chemicals)",
    ],
    asntChapter="DGZfP — Hessen Region",
    awsSection="DVS Hessen",
    apiExamCenter=False,
    transportSurchargeBand="low",
    costOfLivingIndex=98,
    majorPortsRefineriesPlants=[
        {"name": "Industriepark Höchst", "type": "petrochem-park", "scale": "90+ companies, 22,000 employees"},
        {"name": "Frankfurt Airport (FRA)", "type": "airport", "scale": "Largest cargo airport in Europe"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=[
        "Höchst Industrial Park is one of Europe's most diverse chemical sites",
        "Pharma-grade NDT — sterilizable surfaces, SS 316L weld inspection",
        "Frankfurt Airport ground equipment NDT (jet bridges, fuel hydrants)",
    ],
    nearbyMajorCities=["Mannheim (80km)", "Cologne (190km)", "Munich (390km)"],
    turnaroundSeasons=["Summer TARs (Jun-Aug)"],
)

add(
    "munich-de",
    displayName="Munich, Germany",
    country="DE",
    state="Bavaria",
    stateCode="DE-BY",
    tier=2,
    region="europe-west",
    metroPopulation=2980000,
    industries=[
        {"name": "Automotive", "weight": 0.35, "context": "BMW HQ + Munich plant; MAN Truck & Bus"},
        {"name": "Aerospace & Defense", "weight": 0.22, "context": "Airbus Defence and Space, MTU Aero Engines"},
        {"name": "Heavy Engineering", "weight": 0.18, "context": "Siemens Energy, Linde, Krauss-Maffei"},
    ],
    majorEmployers=[
        "BMW Munich Plant", "MAN Truck & Bus", "MTU Aero Engines",
        "Airbus Defence & Space (Ottobrunn)", "Siemens Energy", "Linde Engineering",
        "Krauss-Maffei", "TÜV SÜD HQ", "DEKRA",
    ],
    avgInspectorWageUSD={"level1": 58000, "level2": 78000, "level3": 118000},
    wageBandSource="Destatis Bavaria 2024",
    regionalCodes=[
        "DIN EN ISO 9712", "AD 2000-Merkblatt", "PED 2014/68/EU",
        "Nadcap NDT (aerospace)", "AS9100 (aerospace QMS)",
    ],
    asntChapter="DGZfP — Bavaria Region",
    awsSection="DVS Bayern (HQ)",
    apiExamCenter=False,
    transportSurchargeBand="low",
    costOfLivingIndex=110,
    majorPortsRefineriesPlants=[
        {"name": "Bayernoil Refinery (regional)", "type": "refinery", "scale": "215,000 bpd in nearby Vohburg"},
        {"name": "BMW Munich Plant", "type": "auto", "scale": "1,000 vehicles/day"},
        {"name": "MTU Munich", "type": "aero-engines", "scale": "PW1100G/PW1500G GTF MRO"},
    ],
    pricingMultiplier=1.15,
    uniqueAngles=[
        "Nadcap NDT certification is the dominant aerospace credential here",
        "TÜV SÜD HQ — Munich is the European NDT certification body capital",
        "BMW + MAN drive automotive weld inspection volume — robotic UT cells",
    ],
    nearbyMajorCities=["Stuttgart (220km)", "Frankfurt (390km)", "Vienna (430km)"],
    turnaroundSeasons=["Summer holiday slowdown (Jul-Aug)", "Year-round aerospace MRO"],
)

add(
    "london-uk",
    displayName="London, UK",
    country="UK",
    state="England",
    stateCode="UK-ENG",
    tier=2,
    region="europe-west",
    metroPopulation=9540000,
    industries=[
        {"name": "Engineering Consulting", "weight": 0.30, "context": "Wood, Worley, Bechtel, Mott MacDonald HQs"},
        {"name": "Aviation", "weight": 0.20, "context": "Heathrow, Gatwick — large MRO presence"},
        {"name": "Energy Trading & HQs", "weight": 0.18, "context": "BP, Shell, BG corporate headquarters"},
        {"name": "Construction & Infrastructure", "weight": 0.18, "context": "HS2, Crossrail, Thames Tideway tunneling"},
    ],
    majorEmployers=[
        "BP (London HQ)", "Shell (London HQ)", "Wood plc",
        "Worley", "Bechtel", "Mott MacDonald", "Atkins/SNC-Lavalin",
        "British Airways Engineering (LHR)", "TÜV UK", "Lloyd's Register",
    ],
    avgInspectorWageUSD={"level1": 50000, "level2": 70000, "level3": 108000},
    wageBandSource="UK ONS ASHE 2024 (London weighting)",
    regionalCodes=[
        "BS EN ISO 9712", "PD 5500", "BS EN 17636-1",
        "PSSR 2000 (Pressure Systems Safety Regulations)",
        "EASA Part-145 (aviation)", "Lloyd's Register Ship Rules",
    ],
    asntChapter="BINDT — London Branch (HQ)",
    awsSection="TWI Cambridge (regional)",
    apiExamCenter=True,
    transportSurchargeBand="high",
    costOfLivingIndex=130,
    majorPortsRefineriesPlants=[
        {"name": "Esso Fawley Refinery (regional)", "type": "refinery", "scale": "270,000 bpd in Hampshire (130km from London)"},
        {"name": "Heathrow Airport (LHR)", "type": "airport", "scale": "Europe's busiest hub"},
        {"name": "Tilbury Port (Thames)", "type": "port", "scale": "Major UK container terminal"},
    ],
    pricingMultiplier=1.15,
    uniqueAngles=[
        "Lloyd's Register HQ — marine NDT certifications originate here",
        "London weighting adds 10-15% to inspector day rates vs UK avg",
        "Major construction-NDT demand from HS2, Thames Tideway, Crossrail",
        "Aviation MRO at LHR/LGW (BA, Virgin, Lufthansa Technik)",
    ],
    nearbyMajorCities=["Birmingham (200km)", "Manchester (320km)", "Aberdeen (700km)"],
    turnaroundSeasons=["Year-round consulting/MRO activity"],
)

add(
    "hull-uk",
    displayName="Hull, UK",
    country="UK",
    state="England",
    stateCode="UK-ENG",
    tier=2,
    region="europe-west",
    metroPopulation=320000,
    industries=[
        {"name": "Petrochemicals", "weight": 0.38, "context": "Saltend Chemicals Park — BP, Vivergo, Ineos Acetyls"},
        {"name": "Offshore Wind Manufacturing", "weight": 0.25, "context": "Siemens Gamesa Hull blade factory — 750 turbines/year"},
        {"name": "Port & Logistics", "weight": 0.18, "context": "ABP Hull — major UK Humberside port"},
    ],
    majorEmployers=[
        "Siemens Gamesa Hull", "BP Saltend", "Vivergo Fuels",
        "Ineos Acetyls Hull", "Smith & Nephew", "ABP Hull",
        "Phillips 66 Humber Refinery (nearby)", "Total Lindsey (nearby)",
    ],
    avgInspectorWageUSD={"level1": 45000, "level2": 62000, "level3": 95000},
    wageBandSource="UK ONS ASHE 2024",
    regionalCodes=[
        "BS EN ISO 9712", "PD 5500", "PSSR 2000",
        "DNV-OS-F101 (offshore)", "BS 7910 (ECA)",
    ],
    asntChapter="BINDT — Yorkshire Branch",
    awsSection="TWI Yorkshire",
    apiExamCenter=False,
    transportSurchargeBand="medium",
    costOfLivingIndex=72,
    majorPortsRefineriesPlants=[
        {"name": "Phillips 66 Humber Refinery", "type": "refinery", "scale": "221,000 bpd (Immingham, 30km from Hull)"},
        {"name": "Saltend Chemicals Park", "type": "petrochem-park", "scale": "BP-anchored complex"},
        {"name": "Siemens Gamesa Hull", "type": "wind-turbine", "scale": "Largest blade factory in UK"},
        {"name": "Port of Hull", "type": "port", "scale": "Major Humber estuary terminal"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=[
        "Siemens Gamesa blade NDT (CT scan, UT) is unique offshore-wind specialism",
        "Saltend cluster has its own emergency response inspection cell",
        "Humber estuary refining cluster (Phillips 66, Lindsey) drives spillover demand",
    ],
    nearbyMajorCities=["Leeds (95km)", "Manchester (170km)", "London (310km)"],
    turnaroundSeasons=["Spring TARs (Apr-May)", "Autumn TARs (Sep-Oct)"],
)

add(
    "singapore-sg",
    displayName="Singapore",
    country="SG",
    state="Singapore",
    stateCode="SG",
    tier=1,
    region="asia-southeast",
    metroPopulation=5920000,
    industries=[
        {"name": "Refining & Petrochemicals", "weight": 0.42, "context": "Jurong Island — 100+ chemical companies, ExxonMobil largest single refinery globally"},
        {"name": "Marine & Offshore", "weight": 0.25, "context": "Sembcorp, Keppel — world-leading FPSO/jack-up builders"},
        {"name": "Aerospace MRO", "weight": 0.15, "context": "ST Engineering, SIA Engineering — major MRO hub"},
        {"name": "LNG Bunkering", "weight": 0.10, "context": "Largest LNG-bunker port globally"},
    ],
    majorEmployers=[
        "ExxonMobil Singapore Chemical Plant", "Shell Pulau Bukom",
        "Sembcorp Marine", "Keppel Offshore & Marine", "ST Engineering",
        "SIA Engineering", "Singapore Refining Company (SRC)",
        "Lanxess", "Jurong Engineering", "TÜV SÜD APAC HQ",
    ],
    avgInspectorWageUSD={"level1": 48000, "level2": 68000, "level3": 110000},
    wageBandSource="MOM Singapore wage report 2024",
    regionalCodes=[
        "MOM Workplace Safety & Health Act", "EMA pressure equipment regs",
        "ASME Section V/VIII (adopted)", "API 510/570/653",
        "ABS / Lloyd's / DNV (marine classification)",
    ],
    asntChapter="ASNT Singapore Section",
    awsSection="Singapore Welding Society",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=108,
    majorPortsRefineriesPlants=[
        {"name": "ExxonMobil Jurong Refinery", "type": "refinery", "scale": "605,000 bpd — largest ExxonMobil refinery globally"},
        {"name": "Shell Pulau Bukom", "type": "refinery", "scale": "237,000 bpd"},
        {"name": "SRC Refinery", "type": "refinery", "scale": "290,000 bpd (Chevron-PetroChina)"},
        {"name": "Port of Singapore", "type": "port", "scale": "World's busiest transshipment port"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=[
        "Jurong Island is densest petrochemical complex in Asia — covers <5km² with 100+ plants",
        "Marine NDT for FPSO conversions and LNG bunker barges is a major specialty",
        "MOM-licensed inspectors required for pressure vessel work in Singapore",
    ],
    nearbyMajorCities=["Johor Bahru MY (45km)", "Kuala Lumpur (340km)", "Jakarta (885km)"],
    turnaroundSeasons=["Year-round (no monsoon TAR cluster)"],
)

add(
    "kuala-lumpur-my",
    displayName="Kuala Lumpur, Malaysia",
    country="MY",
    state="Kuala Lumpur Federal Territory",
    stateCode="MY-14",
    tier=2,
    region="asia-southeast",
    metroPopulation=8420000,
    industries=[
        {"name": "Oil & Gas (HQs)", "weight": 0.32, "context": "Petronas HQ, Shell Malaysia, ExxonMobil Malaysia"},
        {"name": "Petrochemicals", "weight": 0.22, "context": "PIC (Pengerang), Kertih, Gebeng petrochemical complexes"},
        {"name": "LNG", "weight": 0.18, "context": "Bintulu LNG, Petronas FLNG"},
        {"name": "Refining", "weight": 0.14, "context": "Melaka Refinery, Port Dickson Refinery, PIC Pengerang"},
    ],
    majorEmployers=[
        "Petronas (HQ at KLCC)", "Shell Malaysia", "ExxonMobil Malaysia",
        "Petronas Carigali", "MISC Berhad", "MMC Corporation",
        "Petronas Refinery & Petrochemical Integrated Development (PRPC)",
    ],
    avgInspectorWageUSD={"level1": 28000, "level2": 42000, "level3": 72000},
    wageBandSource="DOSM Malaysia salary survey 2024",
    regionalCodes=[
        "Petronas Technical Standards (PTS)", "DOSH (Department of OSH) regulations",
        "ASME Section V/VIII (adopted)", "API 510/570/653",
        "Malaysian Standards MS",
    ],
    asntChapter="MSNT (Malaysian Society for NDT)",
    awsSection="Welding Society of Malaysia",
    apiExamCenter=True,
    transportSurchargeBand="low",
    costOfLivingIndex=58,
    majorPortsRefineriesPlants=[
        {"name": "PIC Pengerang Refinery", "type": "refinery", "scale": "300,000 bpd integrated complex (RAPID)"},
        {"name": "Melaka Refinery", "type": "refinery", "scale": "270,000 bpd (Petronas + Aramco JV)"},
        {"name": "Port Klang", "type": "port", "scale": "Largest port in Malaysia"},
        {"name": "Bintulu LNG", "type": "lng", "scale": "30 MTPA — one of world's largest"},
    ],
    pricingMultiplier=0.75,
    uniqueAngles=[
        "Petronas PTS standards govern all upstream NDT work in Malaysia",
        "PRPC Pengerang is the newest mega-complex — heavy ongoing inspection demand",
        "Strong bumiputera contractor preference for Petronas-tendered work",
    ],
    nearbyMajorCities=["Singapore (340km)", "Penang (370km)", "Johor Bahru (320km)"],
    turnaroundSeasons=["Avoid monsoon Nov-Feb (East Coast)"],
)


def main():
    repo_root = Path(__file__).resolve().parent.parent
    out = repo_root / "data" / "cities-batch1-international.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(CITIES, indent=2, ensure_ascii=False))
    print(f"Wrote {len(CITIES)} cities to {out}")


if __name__ == "__main__":
    main()
