"""Batch 3: US oil/gas/petrochem cities + smaller refining/industrial markets."""
from __future__ import annotations
import json
from pathlib import Path

CITIES: dict[str, dict] = {}
def add(slug, **f): CITIES[slug] = f


# ---------------------------------------------------------------------------
# Texas oil/gas/petrochem (post-Houston, post-Beaumont, post-Corpus Christi)
# ---------------------------------------------------------------------------

add("port-arthur-tx",
    displayName="Port Arthur, TX", country="US", state="Texas", stateCode="TX",
    tier=1, region="gulf-coast", metroPopulation=395000,
    industries=[
        {"name": "Refining", "weight": 0.55, "context": "Largest US refinery — Motiva Port Arthur 626k bpd"},
        {"name": "Petrochemicals", "weight": 0.25, "context": "BASF Total Petrochemicals, Chevron Phillips, Indorama"},
        {"name": "LNG Export", "weight": 0.12, "context": "Sempra Port Arthur LNG under construction"},
    ],
    majorEmployers=["Motiva Port Arthur Refinery", "Valero Port Arthur Refinery",
        "TotalEnergies Port Arthur Refinery", "BASF Total Petrochemicals",
        "Chevron Phillips Cedar Bayou", "Sempra Port Arthur LNG"],
    avgInspectorWageUSD={"level1": 60000, "level2": 82000, "level3": 124000},
    wageBandSource="BLS OES Beaumont-Port Arthur MSA 2024",
    regionalCodes=["TPSC §757.001", "TCEQ Air Permit Rules", "API 510/570/653", "ASME Section V/VIII"],
    asntChapter="Houston ASNT Section (regional)", awsSection="AWS Beaumont/Port Arthur Section",
    apiExamCenter=True, transportSurchargeBand="low", costOfLivingIndex=82,
    majorPortsRefineriesPlants=[
        {"name": "Motiva Port Arthur", "type": "refinery", "scale": "626,000 bpd — largest US refinery"},
        {"name": "Valero Port Arthur", "type": "refinery", "scale": "395,000 bpd"},
        {"name": "TotalEnergies Port Arthur", "type": "refinery", "scale": "238,000 bpd"},
        {"name": "Sabine Pass LNG (50km)", "type": "lng", "scale": "30 MTPA Cheniere"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "Motiva Port Arthur is largest US refinery (626k bpd) — sustained mega-scope",
        "Sabine Pass LNG just over the river — cross-border crew movement common",
        "Hurricane Harvey/Laura aftermath created surge inspection demand — model for resilience NDT",
    ],
    nearbyMajorCities=["Beaumont (30km)", "Houston (140km)", "Lake Charles LA (95km)"],
    turnaroundSeasons=["Spring TARs Mar-May", "Fall TARs Sep-Nov"],
)

add("texas-city-tx",
    displayName="Texas City, TX", country="US", state="Texas", stateCode="TX",
    tier=1, region="gulf-coast", metroPopulation=51000,
    industries=[
        {"name": "Refining", "weight": 0.50, "context": "Marathon Galveston Bay (was BP) 631k bpd; Valero Texas City"},
        {"name": "Petrochemicals", "weight": 0.30, "context": "Dow, ISP, INEOS"},
        {"name": "Port", "weight": 0.10, "context": "Texas City Terminal — major chemical/petroleum throughput"},
    ],
    majorEmployers=["Marathon Galveston Bay Refinery", "Valero Texas City",
        "Dow Texas Operations", "INEOS Texas City", "ISP Texas City",
        "Praxair (Linde)"],
    avgInspectorWageUSD={"level1": 62000, "level2": 84000, "level3": 126000},
    wageBandSource="BLS OES Houston MSA 2024 (extended)",
    regionalCodes=["TPSC", "TCEQ", "API 510/570/653", "ASME Section V/VIII", "OSHA PSM"],
    asntChapter="Houston ASNT Section", awsSection="AWS Houston",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "Marathon Galveston Bay Refinery", "type": "refinery", "scale": "631,000 bpd — 2nd largest US"},
        {"name": "Valero Texas City Refinery", "type": "refinery", "scale": "260,000 bpd"},
        {"name": "Dow Texas City", "type": "petrochem", "scale": "Major polyethylene, propylene oxide"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "Site of 2005 BP Texas City explosion — heightened OSHA PSM / mechanical integrity scope here",
        "Marathon Galveston Bay is 2nd largest US refinery",
        "Densest single-city petrochemical cluster in Galveston County",
    ],
    nearbyMajorCities=["Houston (60km)", "Galveston (15km)", "Beaumont (130km)"],
    turnaroundSeasons=["Spring TARs", "Avoid summer hurricane season"],
)

add("galveston-tx",
    displayName="Galveston, TX", country="US", state="Texas", stateCode="TX",
    tier=2, region="gulf-coast", metroPopulation=52000,
    industries=[
        {"name": "Port & Cruise", "weight": 0.35, "context": "Port of Galveston — major cruise terminal + cargo"},
        {"name": "Marine Services", "weight": 0.30, "context": "Offshore service vessel base for Gulf operations"},
        {"name": "Petrochem (proximity)", "weight": 0.20, "context": "Adjacent to Texas City refinery cluster"},
    ],
    majorEmployers=["Port of Galveston", "Galveston Wharves",
        "American National Insurance (HQ)", "UTMB Galveston (medical)",
        "Marine survey contractors"],
    avgInspectorWageUSD={"level1": 58000, "level2": 80000, "level3": 120000},
    wageBandSource="BLS OES Houston MSA 2024",
    regionalCodes=["TPSC", "TCEQ", "USCG Subchapter L", "ABS class rules", "API 510/570/653"],
    asntChapter="Houston ASNT Section", awsSection="AWS Houston",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=90,
    majorPortsRefineriesPlants=[
        {"name": "Port of Galveston", "type": "port", "scale": "Major Gulf cruise port"},
        {"name": "Galveston Bay Marine Service Vessels", "type": "marine", "scale": "Gulf offshore support fleet"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=[
        "Cruise ship dry-dock UT thickness gauging is unique service",
        "Offshore Gulf service vessel inspection — HVAC, hull, propulsion shafts",
        "Hurricane impact zone — post-storm structural inspection scope spikes",
    ],
    nearbyMajorCities=["Texas City (15km)", "Houston (75km)"],
    turnaroundSeasons=["Avoid hurricane season Jun-Nov"],
)

add("pasadena-tx",
    displayName="Pasadena, TX", country="US", state="Texas", stateCode="TX",
    tier=1, region="gulf-coast", metroPopulation=152000,
    industries=[
        {"name": "Refining", "weight": 0.42, "context": "Lyondell Houston Refinery, Pasadena Refining (PBF)"},
        {"name": "Petrochemicals", "weight": 0.38, "context": "PEMEX Pasadena (formerly Shell), MEGlobal, Albemarle"},
    ],
    majorEmployers=["LyondellBasell Houston Refinery", "PBF Energy Pasadena Refinery",
        "PEMEX Pasadena", "MEGlobal", "Albemarle", "Kinder Morgan terminals"],
    avgInspectorWageUSD={"level1": 60000, "level2": 82000, "level3": 124000},
    wageBandSource="BLS OES Houston MSA 2024",
    regionalCodes=["TPSC", "TCEQ", "Harris County", "API 510/570/653", "ASME Section V/VIII"],
    asntChapter="Houston ASNT Section", awsSection="AWS Houston",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "LyondellBasell Houston Refinery", "type": "refinery", "scale": "263,000 bpd (winding down)"},
        {"name": "PBF Pasadena Refinery", "type": "refinery", "scale": "112,000 bpd"},
        {"name": "PEMEX Pasadena", "type": "refinery", "scale": "112,000 bpd (acquired from Shell 2021)"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "Lyondell Houston winding down operations — decommissioning NDT increasing",
        "PEMEX Pasadena is sole Mexican-owned refinery in US — distinct procurement style",
        "Heart of Houston Ship Channel — barge + dock inspection scope",
    ],
    nearbyMajorCities=["Houston (20km)", "Texas City (50km)"],
    turnaroundSeasons=["Spring/Fall TARs"],
)

add("odessa-tx",
    displayName="Odessa, TX", country="US", state="Texas", stateCode="TX",
    tier=2, region="permian", metroPopulation=170000,
    industries=[
        {"name": "Permian Oil & Gas", "weight": 0.65, "context": "Heart of Permian Basin — production support"},
        {"name": "Oilfield Services", "weight": 0.20, "context": "Schlumberger, Halliburton, Baker Hughes regional ops"},
        {"name": "Pipeline & Midstream", "weight": 0.10, "context": "Major Permian crude/gas takeaway lines originate here"},
    ],
    majorEmployers=["Schlumberger Odessa", "Halliburton Odessa", "Baker Hughes Odessa",
        "Diamondback Energy", "Pioneer Natural Resources (Midland)",
        "Oxy Permian operations"],
    avgInspectorWageUSD={"level1": 60000, "level2": 82000, "level3": 122000},
    wageBandSource="BLS OES Midland-Odessa MSA 2024 (Permian premium)",
    regionalCodes=["TPSC", "TCEQ", "TX RR Commission Pipeline Safety", "API 510/570/653"],
    asntChapter="Permian Basin ASNT (regional)", awsSection="AWS Permian",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=90,
    majorPortsRefineriesPlants=[
        {"name": "Permian Basin (regional)", "type": "oil-field", "scale": "Largest US oil-producing basin (~6 MMbpd)"},
        {"name": "Pipeline gathering systems", "type": "pipeline", "scale": "Massive midstream buildout"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=[
        "Permian Basin crude oil and gas pipeline NDT — fastest-growing US oil region",
        "Wellhead facility inspection (separators, treaters, dehys) is high-volume scope",
        "Hot-tap and live-line UT for new tie-ins is in-demand specialty",
    ],
    nearbyMajorCities=["Midland (35km)", "Lubbock (220km)", "El Paso (450km)"],
    turnaroundSeasons=["Year-round operations (mild winter)"],
)

add("midland-tx",  # Already exists in main file but let's strengthen with extra fields if needed - skip
    displayName="Midland, TX", country="US", state="Texas", stateCode="TX",
    tier=1, region="permian", metroPopulation=170000,
    industries=[
        {"name": "Permian E&P HQs", "weight": 0.55, "context": "HQs for Pioneer, Diamondback, Centennial, ExxonMobil Permian"},
        {"name": "Pipeline & Midstream", "weight": 0.22, "context": "Plains All American, Energy Transfer Permian operations"},
        {"name": "Oilfield Services", "weight": 0.18, "context": "Service company HQs"},
    ],
    majorEmployers=["Pioneer Natural Resources HQ", "Diamondback Energy HQ",
        "ExxonMobil Permian", "Chevron Permian", "Plains All American",
        "Energy Transfer", "Schlumberger", "Halliburton"],
    avgInspectorWageUSD={"level1": 62000, "level2": 84000, "level3": 124000},
    wageBandSource="BLS OES Midland-Odessa MSA 2024",
    regionalCodes=["TPSC", "TCEQ", "TX RR Commission", "API 510/570/653"],
    asntChapter="Permian Basin ASNT", awsSection="AWS Permian",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Permian Basin (regional)", "type": "oil-field", "scale": "Largest US oil-producing basin"},
        {"name": "Various crude gathering hubs", "type": "midstream", "scale": "Crude takeaway capacity expansion"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=["E&P HQ city — procurement decisions for Permian inspection contracts originate here",
        "Wellsite NDT scaling with horizontal drilling completions",
        "Pressure equipment in the gas plants and processing facilities"],
    nearbyMajorCities=["Odessa (35km)", "Lubbock (190km)", "El Paso (485km)"],
    turnaroundSeasons=["Year-round"],
)

add("tyler-tx",
    displayName="Tyler, TX", country="US", state="Texas", stateCode="TX",
    tier=3, region="east-texas", metroPopulation=235000,
    industries=[
        {"name": "Pipe Manufacturing", "weight": 0.32, "context": "Northwest Pipe Co, US Steel Tubular Tyler"},
        {"name": "Oil Field Services", "weight": 0.22, "context": "East Texas conventional oil + gas service hub"},
        {"name": "Hospital & Medical", "weight": 0.15, "context": "UT Health, ETMC"},
    ],
    majorEmployers=["US Steel Tubular Tyler", "Northwest Pipe", "Trane Tyler",
        "Continental Tyler"],
    avgInspectorWageUSD={"level1": 52000, "level2": 72000, "level3": 108000},
    wageBandSource="BLS OES East Texas region 2024",
    regionalCodes=["TPSC", "TCEQ", "API 510/570/653", "ASME B31.4/B31.8 (pipelines)"],
    asntChapter="East Texas ASNT", awsSection="AWS East Texas",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=84,
    majorPortsRefineriesPlants=[
        {"name": "US Steel Tubular Tyler", "type": "pipe-mill", "scale": "Welded line pipe + OCTG"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=["Pipe-mill UT (longitudinal weld inspection) is dominant local scope",
        "East Texas conventional oil — older infrastructure, more frequent inspection cycles",
        "Tyler Junior College has NDT certification training"],
    nearbyMajorCities=["Dallas (160km)", "Shreveport LA (160km)", "Houston (310km)"],
    turnaroundSeasons=["Year-round"],
)

add("plaquemine-la",
    displayName="Plaquemine, LA", country="US", state="Louisiana", stateCode="LA",
    tier=2, region="gulf-coast", metroPopulation=7000,
    industries=[
        {"name": "Petrochemicals", "weight": 0.85, "context": "Dow Plaquemine — major chlor-alkali, ethylene, propylene"},
    ],
    majorEmployers=["Dow Plaquemine", "Shintech Plaquemine (PVC)",
        "Syngenta Plaquemine"],
    avgInspectorWageUSD={"level1": 58000, "level2": 80000, "level3": 122000},
    wageBandSource="BLS OES Baton Rouge MSA 2024",
    regionalCodes=["LDEQ Air Permits", "API 510/570/653", "ASME Section V/VIII", "OSHA PSM"],
    asntChapter="Baton Rouge ASNT (regional)", awsSection="AWS Baton Rouge",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=82,
    majorPortsRefineriesPlants=[
        {"name": "Dow Plaquemine", "type": "petrochem", "scale": "Major chlor-alkali + ethylene complex"},
        {"name": "Shintech Plaquemine", "type": "petrochem", "scale": "Largest PVC plant in Western Hemisphere"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=["Shintech is largest PVC producer in Western Hemisphere",
        "Chlor-alkali specific corrosion inspection — wet chlorine service",
        "Mississippi River barge access for pressure vessel transport"],
    nearbyMajorCities=["Baton Rouge (25km)", "New Orleans (130km)"],
    turnaroundSeasons=["Spring/Fall TARs", "Avoid hurricane season"],
)

add("lafayette-la",
    displayName="Lafayette, LA", country="US", state="Louisiana", stateCode="LA",
    tier=2, region="gulf-coast", metroPopulation=489000,
    industries=[
        {"name": "Offshore Oil & Gas Services", "weight": 0.50, "context": "Gulf of Mexico offshore operations base"},
        {"name": "Helicopter & Marine", "weight": 0.20, "context": "PHI helicopters, offshore supply vessels"},
        {"name": "Pipeline", "weight": 0.15, "context": "Gulf onshore/offshore pipeline networks"},
    ],
    majorEmployers=["Halliburton", "Schlumberger", "Baker Hughes",
        "Stone Energy", "Hilcorp", "PHI Aviation",
        "Cameron LNG (90km south)", "Sabine Pass LNG (130km south)"],
    avgInspectorWageUSD={"level1": 58000, "level2": 80000, "level3": 122000},
    wageBandSource="BLS OES Lafayette MSA 2024",
    regionalCodes=["LDEQ", "BSEE/BOEM offshore regs", "API 510/570/653", "ASME"],
    asntChapter="Lafayette ASNT", awsSection="AWS Lafayette",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=86,
    majorPortsRefineriesPlants=[
        {"name": "Gulf of Mexico offshore (regional)", "type": "offshore", "scale": "Major US offshore production basin"},
        {"name": "Cameron LNG (Hackberry, 90km)", "type": "lng", "scale": "12 MTPA"},
        {"name": "Sabine Pass LNG (130km)", "type": "lng", "scale": "30 MTPA"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "Lafayette is Gulf of Mexico offshore operations capital — helicopter ops to platforms",
        "BSEE NDT regulations specifically for offshore — distinct from API 510/570/653",
        "Hurricane preparedness pre-storm + post-storm inspection cycles",
    ],
    nearbyMajorCities=["Baton Rouge (95km)", "Lake Charles (120km)", "New Orleans (210km)"],
    turnaroundSeasons=["Avoid hurricane season Jun-Nov"],
)

add("shreveport-la",
    displayName="Shreveport, LA", country="US", state="Louisiana", stateCode="LA",
    tier=3, region="gulf-coast", metroPopulation=395000,
    industries=[
        {"name": "Manufacturing", "weight": 0.32, "context": "Calumet Specialty, Pratt Industries"},
        {"name": "Defense", "weight": 0.20, "context": "Barksdale AFB — strategic bomber base"},
        {"name": "Haynesville Shale Gas", "weight": 0.18, "context": "Major US dry gas play — pipeline scope"},
    ],
    majorEmployers=["Calumet Specialty Products Shreveport", "Barksdale AFB",
        "Pratt Industries", "Caddo Parish operations"],
    avgInspectorWageUSD={"level1": 50000, "level2": 70000, "level3": 105000},
    wageBandSource="BLS OES Shreveport MSA 2024",
    regionalCodes=["LDEQ", "API 510/570/653", "ASME Section V/VIII", "USAF Tech Orders (Barksdale)"],
    asntChapter="Shreveport ASNT", awsSection="AWS Shreveport",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=80,
    majorPortsRefineriesPlants=[
        {"name": "Calumet Shreveport Refinery", "type": "refinery", "scale": "60,000 bpd specialty products"},
        {"name": "Haynesville Shale (regional)", "type": "gas-field", "scale": "Major US dry gas basin"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=["Calumet specialty products refinery — unique product stream metallurgy",
        "Barksdale AFB strategic bomber wing — military aerospace NDT scope",
        "Haynesville pipeline buildout — gathering and takeaway infrastructure"],
    nearbyMajorCities=["Texarkana (110km)", "Tyler TX (160km)", "Dallas (310km)"],
    turnaroundSeasons=["Spring/Fall TARs"],
)

add("mobile-al",
    displayName="Mobile, AL", country="US", state="Alabama", stateCode="AL",
    tier=2, region="gulf-coast", metroPopulation=414000,
    industries=[
        {"name": "Shipbuilding", "weight": 0.30, "context": "Austal USA — Navy LCS + EPF; Ingalls Pascagoula 100km east"},
        {"name": "Aerospace", "weight": 0.22, "context": "Airbus Mobile A320 final assembly line"},
        {"name": "Port & Refining", "weight": 0.20, "context": "Mobile harbor; Chevron Pascagoula nearby"},
        {"name": "Steel & Heavy Manufacturing", "weight": 0.15, "context": "AM/NS Calvert (ArcelorMittal-Nippon Steel)"},
    ],
    majorEmployers=["Austal USA", "Airbus Mobile", "AM/NS Calvert (steel)",
        "Mobile Container Terminal", "Chevron Pascagoula (regional)"],
    avgInspectorWageUSD={"level1": 52000, "level2": 72000, "level3": 110000},
    wageBandSource="BLS OES Mobile MSA 2024",
    regionalCodes=["ADEM", "ABS class rules", "EASA Part-145 (Airbus)",
        "API 510/570/653", "ASME"],
    asntChapter="Gulf Coast ASNT (Mobile section)", awsSection="AWS Mobile",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=82,
    majorPortsRefineriesPlants=[
        {"name": "Austal USA Shipyard", "type": "shipyard", "scale": "US Navy LCS + EPF aluminum hulls"},
        {"name": "Airbus Mobile FAL", "type": "aerospace", "scale": "A320/321 final assembly"},
        {"name": "Mobile Container Terminal", "type": "port", "scale": "Major Gulf container port"},
        {"name": "AM/NS Calvert", "type": "steel", "scale": "5 MTPA flat-rolled steel"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=[
        "Austal aluminum-hull shipbuilding — unique material inspection (vs steel hulls)",
        "Airbus Mobile FAL — only Airbus assembly outside Europe and China; EASA Part-145",
        "AM/NS Calvert — newest integrated steel mill in US",
    ],
    nearbyMajorCities=["Pascagoula MS (60km)", "Pensacola FL (90km)", "New Orleans (235km)"],
    turnaroundSeasons=["Avoid hurricane season Jun-Nov"],
)

add("pascagoula-ms",
    displayName="Pascagoula, MS", country="US", state="Mississippi", stateCode="MS",
    tier=1, region="gulf-coast", metroPopulation=140000,
    industries=[
        {"name": "Refining", "weight": 0.40, "context": "Chevron Pascagoula — 369k bpd"},
        {"name": "Shipbuilding", "weight": 0.30, "context": "HII Ingalls Shipbuilding — destroyers, amphibs"},
        {"name": "LNG", "weight": 0.15, "context": "Gulf LNG terminal"},
    ],
    majorEmployers=["Chevron Pascagoula Refinery", "Ingalls Shipbuilding (HII)",
        "Mississippi Phosphates (closed but inspection scope continues)",
        "VT Halter Marine"],
    avgInspectorWageUSD={"level1": 56000, "level2": 78000, "level3": 118000},
    wageBandSource="BLS OES Pascagoula MSA 2024",
    regionalCodes=["MDEQ", "ABS/Lloyd's class", "API 510/570/653", "USCG Subchapter L (vessels)"],
    asntChapter="Gulf Coast ASNT", awsSection="AWS Mississippi Gulf",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=80,
    majorPortsRefineriesPlants=[
        {"name": "Chevron Pascagoula Refinery", "type": "refinery", "scale": "369,000 bpd"},
        {"name": "Ingalls Shipbuilding", "type": "shipyard", "scale": "DDG-51 Burke-class, LPD-17 San Antonio-class, NSC"},
        {"name": "Gulf LNG Pascagoula", "type": "lng", "scale": "Re-gasification terminal"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "Ingalls Shipbuilding — largest privately-held shipyard in US, builds Navy destroyers",
        "Chevron Pascagoula is one of largest single-train refineries in US",
        "Naval-grade NDT (Mil-Spec) is dominant credential here",
    ],
    nearbyMajorCities=["Mobile AL (60km)", "Biloxi (50km)", "New Orleans (170km)"],
    turnaroundSeasons=["Avoid hurricane season Jun-Nov"],
)

# ---------------------------------------------------------------------------
# Wyoming/North Dakota/Mountain West oil & gas
# ---------------------------------------------------------------------------

add("casper-wy",
    displayName="Casper, WY", country="US", state="Wyoming", stateCode="WY",
    tier=2, region="rockies", metroPopulation=80000,
    industries=[
        {"name": "Oil & Gas (PRB, Niobrara)", "weight": 0.55, "context": "Powder River Basin oil + Niobrara shale"},
        {"name": "Refining", "weight": 0.22, "context": "Sinclair Wyoming Refining — 24k bpd"},
        {"name": "Pipeline", "weight": 0.15, "context": "Major Bakken/PRB takeaway lines"},
    ],
    majorEmployers=["Sinclair Wyoming Refining", "EOG Resources Casper",
        "Devon Energy", "Continental Resources", "ConocoPhillips Wyoming"],
    avgInspectorWageUSD={"level1": 56000, "level2": 78000, "level3": 118000},
    wageBandSource="BLS OES Wyoming 2024",
    regionalCodes=["WY DEQ", "WOGCC pipeline regs", "API 510/570/653"],
    asntChapter="Rocky Mountain ASNT (regional)", awsSection="AWS Rocky Mountain",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "Sinclair Wyoming Refining", "type": "refinery", "scale": "24,000 bpd"},
        {"name": "Powder River Basin", "type": "oil-field", "scale": "Major US oil basin (~500k bpd)"},
        {"name": "Sinclair coker + crude unit", "type": "refinery-unit", "scale": "Recently expanded"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=["Sinclair Wyoming is one of smallest US refineries — every TAR is critical",
        "Powder River + Niobrara well NDT — pad-style scope",
        "Cold-weather inspection — UT couplant + radiation source handling at -20°F"],
    nearbyMajorCities=["Cheyenne (290km)", "Denver (450km)", "Billings MT (450km)"],
    turnaroundSeasons=["Spring/Summer TARs preferred (avoid winter)"],
)

add("cheyenne-wy",
    displayName="Cheyenne, WY", country="US", state="Wyoming", stateCode="WY",
    tier=3, region="rockies", metroPopulation=100000,
    industries=[
        {"name": "Refining", "weight": 0.45, "context": "HF Sinclair Cheyenne Refinery — 52k bpd"},
        {"name": "Wind Power", "weight": 0.20, "context": "Wyoming wind energy buildout"},
        {"name": "Defense", "weight": 0.18, "context": "F.E. Warren AFB — ICBM operations"},
    ],
    majorEmployers=["HF Sinclair Cheyenne Refinery", "F.E. Warren AFB",
        "Magpul Industries", "Wyoming-based wind contractors"],
    avgInspectorWageUSD={"level1": 54000, "level2": 75000, "level3": 115000},
    wageBandSource="BLS OES Wyoming 2024",
    regionalCodes=["WY DEQ", "WOGCC", "API 510/570/653", "USAF Tech Orders"],
    asntChapter="Rocky Mountain ASNT", awsSection="AWS Rocky Mountain",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=86,
    majorPortsRefineriesPlants=[
        {"name": "HF Sinclair Cheyenne Refinery", "type": "refinery", "scale": "52,000 bpd"},
        {"name": "F.E. Warren AFB", "type": "military", "scale": "Minuteman III ICBM wing"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=["F.E. Warren AFB ICBM silos — unique military aerospace inspection",
        "Wyoming wind farm tower foundation NDT is growing scope",
        "HF Sinclair Cheyenne — small refinery with high turnaround intensity"],
    nearbyMajorCities=["Casper (290km)", "Denver (160km)", "Laramie (75km)"],
    turnaroundSeasons=["Spring/Fall TARs (avoid winter cold)"],
)

add("rock-springs-wy",
    displayName="Rock Springs, WY", country="US", state="Wyoming", stateCode="WY",
    tier=3, region="rockies", metroPopulation=42000,
    industries=[
        {"name": "Trona Mining & Soda Ash", "weight": 0.55, "context": "Green River Basin trona — world's largest deposit"},
        {"name": "Coal & Power", "weight": 0.20, "context": "Jim Bridger power complex"},
        {"name": "Oil & Gas", "weight": 0.15, "context": "Wyoming Range gas + coalbed methane"},
    ],
    majorEmployers=["Solvay Green River", "Genesis Alkali", "Tata Chemicals",
        "PacifiCorp Jim Bridger Plant"],
    avgInspectorWageUSD={"level1": 56000, "level2": 78000, "level3": 118000},
    wageBandSource="BLS OES Wyoming 2024",
    regionalCodes=["WY DEQ", "MSHA (mining)", "API 510/570/653"],
    asntChapter="Rocky Mountain ASNT", awsSection="AWS Rocky Mountain",
    apiExamCenter=False, transportSurchargeBand="high", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Trona mines (regional)", "type": "mine", "scale": "World's largest natural soda ash deposit"},
        {"name": "Jim Bridger Power Plant", "type": "power", "scale": "2,120 MW coal-fired"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=["Trona/soda ash mining — unique alkaline corrosion inspection profile",
        "Jim Bridger coal-fired plant tube inspection (boiler, super-heater)",
        "MSHA mining inspection compliance is dominant regulatory layer"],
    nearbyMajorCities=["Casper (320km)", "Salt Lake City (290km)"],
    turnaroundSeasons=["Spring/Summer (avoid harsh winters)"],
)

add("gillette-wy",
    displayName="Gillette, WY", country="US", state="Wyoming", stateCode="WY",
    tier=3, region="rockies", metroPopulation=33000,
    industries=[
        {"name": "Coal Mining", "weight": 0.55, "context": "Powder River Basin — largest US coal-producing region"},
        {"name": "Coalbed Methane", "weight": 0.22, "context": "PRB CBM development"},
        {"name": "Oil (Niobrara)", "weight": 0.15, "context": "Niobrara play extension"},
    ],
    majorEmployers=["Peabody Energy (NARM, Caballo)", "Arch Resources (Black Thunder)",
        "Cloud Peak Energy", "Anadarko / Oxy CBM operations"],
    avgInspectorWageUSD={"level1": 56000, "level2": 78000, "level3": 118000},
    wageBandSource="BLS OES Wyoming 2024",
    regionalCodes=["WY DEQ", "MSHA (mining)", "API 510/570/653"],
    asntChapter="Rocky Mountain ASNT", awsSection="AWS Rocky Mountain",
    apiExamCenter=False, transportSurchargeBand="high", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Black Thunder Mine", "type": "mine", "scale": "Largest US coal mine"},
        {"name": "North Antelope Rochelle Mine", "type": "mine", "scale": "Among largest US coal mines"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=[
        "PRB coal mining — dragline boom NDT is unique high-stress fatigue inspection",
        "Coal-prep plant inspection (rotary breakers, screens, conveyors)",
        "Coalbed methane wellhead and gathering NDT",
    ],
    nearbyMajorCities=["Casper (190km)", "Billings MT (240km)"],
    turnaroundSeasons=["Spring/Summer"],
)

add("dickinson-nd",
    displayName="Dickinson, ND", country="US", state="North Dakota", stateCode="ND",
    tier=3, region="bakken", metroPopulation=24000,
    industries=[
        {"name": "Bakken Oil & Gas", "weight": 0.65, "context": "Heart of Bakken Shale — wellsite inspection"},
        {"name": "Oilfield Services", "weight": 0.20, "context": "Service company operations centers"},
    ],
    majorEmployers=["Continental Resources", "Hess Corporation", "Whiting Petroleum",
        "Schlumberger Bakken", "Halliburton Bakken"],
    avgInspectorWageUSD={"level1": 65000, "level2": 88000, "level3": 130000},
    wageBandSource="BLS OES North Dakota 2024 (Bakken premium)",
    regionalCodes=["ND DMR Pipeline regs", "API 510/570/653", "PHMSA"],
    asntChapter="Northern Plains ASNT", awsSection="AWS Northern Plains",
    apiExamCenter=False, transportSurchargeBand="high", costOfLivingIndex=98,
    majorPortsRefineriesPlants=[
        {"name": "Bakken Shale (regional)", "type": "oil-field", "scale": "Major US tight oil basin (~1.2 MMbpd)"},
    ],
    pricingMultiplier=1.20,
    uniqueAngles=["Bakken wellpad inspection — production tanks, separators, treaters",
        "Cold-weather operations: -40°F not uncommon — equipment + couplant adaptation",
        "DAPL pipeline NDT after 2017 commissioning, ongoing integrity"],
    nearbyMajorCities=["Bismarck (170km)", "Williston (200km)"],
    turnaroundSeasons=["Spring/Summer TARs preferred"],
)

add("williston-nd",
    displayName="Williston, ND", country="US", state="North Dakota", stateCode="ND",
    tier=3, region="bakken", metroPopulation=29000,
    industries=[
        {"name": "Bakken Oil & Gas", "weight": 0.75, "context": "Bakken Shale operations capital — Continental, Hess"},
    ],
    majorEmployers=["Continental Resources Bakken", "Hess Bakken",
        "ONEOK midstream", "Schlumberger Williston", "Halliburton Williston"],
    avgInspectorWageUSD={"level1": 68000, "level2": 92000, "level3": 135000},
    wageBandSource="BLS OES Williston 2024 (highest Bakken premium)",
    regionalCodes=["ND DMR", "API 510/570/653", "PHMSA"],
    asntChapter="Northern Plains ASNT", awsSection="AWS Northern Plains",
    apiExamCenter=False, transportSurchargeBand="high", costOfLivingIndex=104,
    majorPortsRefineriesPlants=[
        {"name": "Bakken Shale (epicenter)", "type": "oil-field", "scale": "Williston Basin — heart of Bakken"},
        {"name": "DAPL origin pump station", "type": "pipeline", "scale": "570,000 bpd takeaway"},
    ],
    pricingMultiplier=1.25,
    uniqueAngles=["Williston is the working capital of Bakken — most contractors stationed here",
        "Mancamp work model — extended rotations during peak activity",
        "Most extreme cold-weather NDT in continental US — operational protocols differ"],
    nearbyMajorCities=["Dickinson (200km)", "Bismarck (370km)", "Minot (200km)"],
    turnaroundSeasons=["May-Sep window for outdoor non-critical work"],
)

add("fargo-nd",
    displayName="Fargo, ND", country="US", state="North Dakota", stateCode="ND",
    tier=3, region="upper-midwest", metroPopulation=250000,
    industries=[
        {"name": "Agricultural Manufacturing", "weight": 0.40, "context": "John Deere, Bobcat, Case New Holland"},
        {"name": "Pipeline Services", "weight": 0.18, "context": "Bakken pipeline ops staging"},
        {"name": "Food Processing", "weight": 0.15, "context": "Cargill, ADM facilities"},
    ],
    majorEmployers=["John Deere Fargo", "Bobcat (Doosan) Gwinner",
        "Case New Holland", "Cargill", "Microsoft Fargo"],
    avgInspectorWageUSD={"level1": 50000, "level2": 70000, "level3": 105000},
    wageBandSource="BLS OES North Dakota 2024",
    regionalCodes=["ND DMR", "FDA food contact", "API 510/570/653"],
    asntChapter="Northern Plains ASNT", awsSection="AWS Northern Plains",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "John Deere Fargo", "type": "manufacturing", "scale": "Air seeders, sprayers"},
        {"name": "Bobcat HQ Gwinner", "type": "manufacturing", "scale": "Compact equipment"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=["Ag equipment manufacturing — weldment NDT for frames, booms, axles",
        "Food-grade SS welding inspection (USDA, FDA contact requirements)",
        "Gateway to Bakken — many service companies stage from Fargo"],
    nearbyMajorCities=["Bismarck (320km)", "Minneapolis (390km)", "Grand Forks (130km)"],
    turnaroundSeasons=["Spring-Fall preferred"],
)

# ---------------------------------------------------------------------------
# Mountain west / oil shale / rocky mountain
# ---------------------------------------------------------------------------

add("vernal-ut",
    displayName="Vernal, UT", country="US", state="Utah", stateCode="UT",
    tier=3, region="rockies", metroPopulation=10000,
    industries=[
        {"name": "Uinta Basin Oil & Gas", "weight": 0.78, "context": "Major oil + gas production in Uinta Basin"},
        {"name": "Oil Shale (R&D)", "weight": 0.10, "context": "Estonian Eesti + others have pilot scope"},
    ],
    majorEmployers=["Crescent Point Energy", "EnerVest", "Newpark Resources",
        "Uintah Basin pipeline operators"],
    avgInspectorWageUSD={"level1": 56000, "level2": 78000, "level3": 118000},
    wageBandSource="BLS OES Utah Uinta region 2024",
    regionalCodes=["Utah DOGM", "Utah DEQ", "API 510/570/653"],
    asntChapter="Utah ASNT (regional)", awsSection="AWS Rocky Mountain",
    apiExamCenter=False, transportSurchargeBand="high", costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "Uinta Basin", "type": "oil-field", "scale": "Major Utah oil play (~150k bpd)"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=["Uinta Basin waxy crude — unique handling for crude oil tanks (paraffin)",
        "Oil shale R&D pilots (Estonian-style retorts) create niche scope",
        "Remote operations — long drive times to wellpads"],
    nearbyMajorCities=["Salt Lake City (240km)", "Grand Junction CO (160km)"],
    turnaroundSeasons=["Spring/Summer"],
)

add("provo-ut",
    displayName="Provo, UT", country="US", state="Utah", stateCode="UT",
    tier=3, region="rockies", metroPopulation=720000,
    industries=[
        {"name": "Tech Manufacturing", "weight": 0.32, "context": "Adobe, Qualtrics, IM Flash"},
        {"name": "Heavy Manufacturing", "weight": 0.22, "context": "Geneva Steel (closed but legacy), Vivint Smart Home"},
        {"name": "Composites & Aerospace", "weight": 0.20, "context": "Northrop Grumman Bacchus, ATK Promontory"},
    ],
    majorEmployers=["Northrop Grumman Bacchus (rocket motors)",
        "ATK Promontory (50km)", "BYU Engineering programs"],
    avgInspectorWageUSD={"level1": 52000, "level2": 72000, "level3": 110000},
    wageBandSource="BLS OES Provo MSA 2024",
    regionalCodes=["Utah DEQ", "AS9100 aerospace", "Nadcap NDT", "ASME"],
    asntChapter="Utah ASNT", awsSection="AWS Salt Lake/Provo",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Northrop Grumman Bacchus", "type": "aerospace", "scale": "Solid rocket motor casings"},
        {"name": "ATK/Northrop Promontory", "type": "aerospace", "scale": "Largest US solid rocket facility"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=["Solid rocket motor case CT scanning + UT — rare specialty NDT",
        "Composite NDT for aerospace (UT C-scan, thermography)",
        "Nadcap NDT certification dominant credential"],
    nearbyMajorCities=["Salt Lake City (75km)", "Ogden (120km)"],
    turnaroundSeasons=["Year-round indoor operations"],
)

add("idaho-falls-id",
    displayName="Idaho Falls, ID", country="US", state="Idaho", stateCode="ID",
    tier=3, region="rockies", metroPopulation=145000,
    industries=[
        {"name": "Nuclear Research", "weight": 0.55, "context": "Idaho National Laboratory (INL) — US nuclear R&D hub"},
        {"name": "Defense", "weight": 0.18, "context": "Naval Reactors Facility"},
        {"name": "Agricultural Processing", "weight": 0.12, "context": "Potato processing, Premier Technology"},
    ],
    majorEmployers=["Idaho National Laboratory (Battelle Energy Alliance)",
        "Naval Reactors Idaho", "Premier Technology",
        "Areva NP (legacy)", "INL contractor pool"],
    avgInspectorWageUSD={"level1": 58000, "level2": 80000, "level3": 122000},
    wageBandSource="BLS OES Idaho Falls 2024 (DOE wage scale)",
    regionalCodes=["DOE 10 CFR 830 (nuclear safety)", "ASME Section III/XI",
        "ANS standards", "API 510/570/653 (limited)"],
    asntChapter="Northwest ASNT (regional)", awsSection="AWS Idaho",
    apiExamCenter=False, transportSurchargeBand="high", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Idaho National Laboratory", "type": "nuclear-r&d", "scale": "DOE national lab — 50+ research reactors historically"},
        {"name": "Naval Reactors Facility", "type": "naval-nuclear", "scale": "Naval prototype reactor program"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=["INL — US's premier nuclear research site, unique reactor inspection scope",
        "DOE clearance often required — adds onboarding time",
        "Decommissioning of legacy reactors creates RVI / underwater UT scope"],
    nearbyMajorCities=["Pocatello (80km)", "Salt Lake City (340km)"],
    turnaroundSeasons=["Year-round"],
)

add("pocatello-id",
    displayName="Pocatello, ID", country="US", state="Idaho", stateCode="ID",
    tier=3, region="rockies", metroPopulation=88000,
    industries=[
        {"name": "Phosphate/Chemical", "weight": 0.40, "context": "Bayer/Monsanto Soda Springs phosphate"},
        {"name": "Heavy Manufacturing", "weight": 0.22, "context": "ON Semiconductor, Allstate Insurance ops"},
        {"name": "Railroad", "weight": 0.18, "context": "Union Pacific division terminal"},
    ],
    majorEmployers=["FMC Idaho Phosphate", "Bayer Pocatello",
        "ON Semiconductor", "Union Pacific Railroad"],
    avgInspectorWageUSD={"level1": 50000, "level2": 70000, "level3": 105000},
    wageBandSource="BLS OES Idaho 2024",
    regionalCodes=["Idaho DEQ", "MSHA (phosphate mining)", "API 510/570/653"],
    asntChapter="Northwest ASNT", awsSection="AWS Idaho",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=84,
    majorPortsRefineriesPlants=[
        {"name": "FMC Idaho phosphate plant", "type": "chemical", "scale": "Major elemental phosphorus historically"},
        {"name": "Bayer Soda Springs", "type": "chemical", "scale": "Phosphate ore processing"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=["Phosphoric acid service inspection — unique corrosion regime",
        "Elemental phosphorus production NDT — fire risk handling",
        "Rail tank car NDT for phosphate transport"],
    nearbyMajorCities=["Idaho Falls (80km)", "Salt Lake City (260km)", "Boise (380km)"],
    turnaroundSeasons=["Spring/Summer/Fall"],
)

add("boise-id",
    displayName="Boise, ID", country="US", state="Idaho", stateCode="ID",
    tier=3, region="rockies", metroPopulation=820000,
    industries=[
        {"name": "Semiconductor Manufacturing", "weight": 0.35, "context": "Micron Technology HQ"},
        {"name": "Construction & Infrastructure", "weight": 0.25, "context": "Major regional construction hub"},
        {"name": "Food Processing", "weight": 0.15, "context": "Simplot HQ, ConAgra"},
    ],
    majorEmployers=["Micron Technology HQ", "Simplot",
        "St. Luke's Health System", "Albertsons HQ"],
    avgInspectorWageUSD={"level1": 52000, "level2": 72000, "level3": 110000},
    wageBandSource="BLS OES Boise MSA 2024",
    regionalCodes=["Idaho DEQ", "Semiconductor Industry Association",
        "FDA (food contact)", "API 510/570/653"],
    asntChapter="Northwest ASNT", awsSection="AWS Idaho",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Micron Boise Fab", "type": "semi", "scale": "DRAM + NAND fabrication"},
        {"name": "Simplot Caldwell", "type": "food", "scale": "Frozen potato processing — largest in US"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=["Semiconductor fab piping — ultra-high purity (UHP) gas line inspection",
        "Food-grade SS weld inspection (3-A Sanitary Standards)",
        "Gateway to Idaho mountain mining + power generation"],
    nearbyMajorCities=["Salt Lake City (550km)", "Spokane (610km)", "Reno (660km)"],
    turnaroundSeasons=["Year-round"],
)


def main():
    repo_root = Path(__file__).resolve().parent.parent
    out = repo_root / "data" / "cities-batch3-us-energy.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(CITIES, indent=2, ensure_ascii=False))
    print(f"Wrote {len(CITIES)} cities to {out}")


if __name__ == "__main__":
    main()
