"""Batch 2: International — India, South America, Africa, remaining Asia/Europe (~22 cities)."""
from __future__ import annotations
import json
from pathlib import Path

CITIES: dict[str, dict] = {}

def add(slug, **fields): CITIES[slug] = fields


add(
    "mumbai-in",
    displayName="Mumbai, India", country="IN", state="Maharashtra", stateCode="IN-MH",
    tier=1, region="india-west", metroPopulation=21670000,
    industries=[
        {"name": "Refining & Petrochemicals", "weight": 0.35, "context": "BPCL Mahul, HPCL Mumbai, ONGC HQ"},
        {"name": "Port Operations", "weight": 0.20, "context": "JNPT — India's busiest container port; Mumbai Port Trust"},
        {"name": "Offshore Oil & Gas", "weight": 0.18, "context": "ONGC Bombay High operations base"},
        {"name": "Heavy Engineering", "weight": 0.12, "context": "L&T Hazira, Godrej & Boyce"},
    ],
    majorEmployers=["ONGC (HQ)", "BPCL Mumbai Refinery", "HPCL Mumbai Refinery",
        "Reliance Industries (corporate HQ)", "L&T Heavy Engineering", "Mazagon Dock Shipbuilders",
        "TCE Engineering", "Tata Consulting Engineers", "Bureau Veritas India"],
    avgInspectorWageUSD={"level1": 14000, "level2": 22000, "level3": 42000},
    wageBandSource="ISNT salary survey 2024 + Naukri benchmark",
    regionalCodes=["IBR (Indian Boiler Regulations) 1950", "OISD-STD-105 (NDT)",
        "PNGRB (downstream)", "ASME Section V/VIII (adopted)", "API 510/570/653"],
    asntChapter="ISNT (Indian Society for NDT) — Mumbai Chapter (oldest)",
    awsSection="Indian Welding Society — Mumbai",
    apiExamCenter=True,
    transportSurchargeBand="medium",
    costOfLivingIndex=42,
    majorPortsRefineriesPlants=[
        {"name": "BPCL Mumbai Refinery", "type": "refinery", "scale": "240,000 bpd"},
        {"name": "HPCL Mumbai Refinery", "type": "refinery", "scale": "190,000 bpd"},
        {"name": "JNPT (Nhava Sheva)", "type": "port", "scale": "India's largest container port"},
        {"name": "Bombay High oil field", "type": "offshore-field", "scale": "India's largest offshore oil field"},
    ],
    pricingMultiplier=0.55,
    uniqueAngles=[
        "ONGC Bombay High offshore inspection — largest Indian offshore market",
        "IBR Form III certification mandatory for boiler-related work",
        "Refinery cluster (Mahul) with 4 large refineries inside city limits",
    ],
    nearbyMajorCities=["Pune (150km)", "Surat (280km)", "Nashik (170km)"],
    turnaroundSeasons=["Avoid monsoon Jun-Sep", "Winter TARs Nov-Feb"],
)

add(
    "ahmedabad-in",
    displayName="Ahmedabad, India", country="IN", state="Gujarat", stateCode="IN-GJ",
    tier=2, region="india-west", metroPopulation=8650000,
    industries=[
        {"name": "Refining & Petrochemicals", "weight": 0.40, "context": "Gujarat refining cluster — RIL Jamnagar, IOC Koyali nearby"},
        {"name": "Pharma & Chemicals", "weight": 0.22, "context": "Largest pharma manufacturing cluster in India"},
        {"name": "Textile & Heavy Industry", "weight": 0.15, "context": "Adani Mundra port, Sanand auto"},
    ],
    majorEmployers=["IOC Koyali Refinery (Vadodara nearby)", "Reliance Petrochemical Hazira (200km)",
        "Cadila Healthcare", "Torrent Pharmaceuticals", "Adani Mundra (port)",
        "Tata Motors Sanand", "Suzuki Motor Gujarat"],
    avgInspectorWageUSD={"level1": 10000, "level2": 17000, "level3": 35000},
    wageBandSource="ISNT salary survey 2024",
    regionalCodes=["IBR 1950", "Gujarat Pollution Control Board", "OISD-STD-105",
        "ASME Section V/VIII", "API 510/570/653"],
    asntChapter="ISNT — Gujarat Chapter",
    awsSection="IIW (Indian Institute of Welding) — Ahmedabad",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=32,
    majorPortsRefineriesPlants=[
        {"name": "IOC Koyali Refinery", "type": "refinery", "scale": "270,000 bpd (60km away in Vadodara)"},
        {"name": "Mundra Port (Adani)", "type": "port", "scale": "India's largest private port"},
        {"name": "Sanand Industrial Estate", "type": "industrial-park", "scale": "Tata + Suzuki + Ford auto cluster"},
    ],
    pricingMultiplier=0.50,
    uniqueAngles=[
        "Gateway to Jamnagar refining cluster (180km west) — largest in world",
        "Pharma-grade NDT (USP, EU GMP) is unique skill demand",
        "Adani Mundra port crane and conveyor inspection scope",
    ],
    nearbyMajorCities=["Vadodara (110km)", "Surat (260km)", "Mumbai (530km)"],
    turnaroundSeasons=["Winter TARs Nov-Feb", "Avoid monsoon Jun-Sep"],
)

add(
    "jamnagar-in",
    displayName="Jamnagar, India", country="IN", state="Gujarat", stateCode="IN-GJ",
    tier=1, region="india-west", metroPopulation=600000,
    industries=[
        {"name": "Refining", "weight": 0.65, "context": "World's largest refining complex — Reliance Jamnagar 1.36M bpd"},
        {"name": "Petrochemicals", "weight": 0.20, "context": "RIL polymer and aromatics complex co-located"},
    ],
    majorEmployers=["Reliance Industries Jamnagar (the refinery)",
        "Essar Oil Vadinar (200,000 bpd)", "Reliance SEZ Jamnagar",
        "Reliance contractor pool: L&T, Petrofac, Bechtel", "Bureau Veritas India"],
    avgInspectorWageUSD={"level1": 13000, "level2": 22000, "level3": 45000},
    wageBandSource="Reliance contractor band 2024",
    regionalCodes=["RIL Engineering Standards", "IBR 1950", "OISD-STD-105",
        "ASME Section V/VIII", "API 510/570/653"],
    asntChapter="ISNT — Gujarat Chapter (Jamnagar node)",
    awsSection="IIW — Jamnagar branch",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=30,
    majorPortsRefineriesPlants=[
        {"name": "Reliance Jamnagar Refinery", "type": "refinery", "scale": "1.36M bpd — largest in world"},
        {"name": "Essar Vadinar Refinery", "type": "refinery", "scale": "405,000 bpd"},
        {"name": "Sikka Port (Reliance)", "type": "port", "scale": "Captive crude import terminal"},
    ],
    pricingMultiplier=0.55,
    uniqueAngles=[
        "Jamnagar holds title of world's largest single-site refining complex",
        "RIL maintains its own inspector qualification scheme above ASNT",
        "Massive demand for IRIS (heat exchanger tube ECT) given complexity",
    ],
    nearbyMajorCities=["Rajkot (90km)", "Ahmedabad (310km)", "Mumbai (700km)"],
    turnaroundSeasons=["Winter TARs Nov-Feb"],
)

add(
    "chennai-in",
    displayName="Chennai, India", country="IN", state="Tamil Nadu", stateCode="IN-TN",
    tier=2, region="india-south", metroPopulation=11500000,
    industries=[
        {"name": "Refining", "weight": 0.30, "context": "CPCL (Chennai Petroleum) — 230,000 bpd"},
        {"name": "Automotive", "weight": 0.25, "context": "Detroit of India — Hyundai, Ford (former), Royal Enfield, BMW"},
        {"name": "Port & Shipping", "weight": 0.18, "context": "Chennai Port + Ennore Port"},
        {"name": "Petrochemicals", "weight": 0.12, "context": "MRL, Manali Industrial Estate"},
    ],
    majorEmployers=["CPCL (Chennai Petroleum Corp)", "Hyundai Motor India",
        "Royal Enfield", "L&T Manapakkam", "Ashok Leyland", "TVS Group",
        "Indian Oil Tanker Terminal Ennore"],
    avgInspectorWageUSD={"level1": 11000, "level2": 18000, "level3": 36000},
    wageBandSource="ISNT South India 2024",
    regionalCodes=["IBR 1950", "Tamil Nadu Pollution Control", "OISD-STD-105",
        "ASME Section V/VIII", "API 510/570/653"],
    asntChapter="ISNT — Chennai Chapter",
    awsSection="IIW — Chennai branch",
    apiExamCenter=True, transportSurchargeBand="low", costOfLivingIndex=34,
    majorPortsRefineriesPlants=[
        {"name": "CPCL Manali Refinery", "type": "refinery", "scale": "230,000 bpd"},
        {"name": "Chennai Port", "type": "port", "scale": "India's 3rd largest"},
        {"name": "Ennore Port", "type": "port", "scale": "LNG terminal + bulk"},
        {"name": "Hyundai Sriperumbudur", "type": "auto", "scale": "750,000 cars/year"},
    ],
    pricingMultiplier=0.55,
    uniqueAngles=[
        "Auto industry weld inspection (resistance + arc) is sizeable scope",
        "CPCL is one of India's older refineries — heavy revamp NDT demand",
        "Ennore LNG terminal commissioned 2019, ongoing cryogenic inspection",
    ],
    nearbyMajorCities=["Bangalore (350km)", "Hyderabad (630km)", "Kochi (700km)"],
    turnaroundSeasons=["Winter TARs Nov-Feb", "Avoid NE monsoon Oct-Dec"],
)

add(
    "kochi-in",
    displayName="Kochi, India", country="IN", state="Kerala", stateCode="IN-KL",
    tier=2, region="india-south", metroPopulation=2580000,
    industries=[
        {"name": "Refining", "weight": 0.42, "context": "BPCL Kochi Refinery — 310,000 bpd, India's 2nd largest single-site"},
        {"name": "Shipbuilding", "weight": 0.22, "context": "Cochin Shipyard — India's largest"},
        {"name": "Port Operations", "weight": 0.18, "context": "Vallarpadam transshipment terminal"},
        {"name": "LNG", "weight": 0.10, "context": "Petronet LNG Kochi terminal"},
    ],
    majorEmployers=["BPCL Kochi Refinery", "Cochin Shipyard Ltd",
        "Petronet LNG Kochi", "FACT (Fertilizers and Chemicals Travancore)",
        "Cochin Port Authority"],
    avgInspectorWageUSD={"level1": 11000, "level2": 18000, "level3": 36000},
    wageBandSource="ISNT South India 2024",
    regionalCodes=["IBR 1950", "Kerala Factories Inspectorate", "OISD-STD-105",
        "IRS classification (Cochin Shipyard)", "ASME Section V/VIII"],
    asntChapter="ISNT — Kochi Chapter",
    awsSection="IIW — Kerala",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=36,
    majorPortsRefineriesPlants=[
        {"name": "BPCL Kochi Refinery", "type": "refinery", "scale": "310,000 bpd"},
        {"name": "Cochin Shipyard", "type": "shipyard", "scale": "Largest in India — built INS Vikrant aircraft carrier"},
        {"name": "Petronet LNG Kochi", "type": "lng", "scale": "5 MTPA"},
        {"name": "Vallarpadam Terminal", "type": "port", "scale": "India's first transshipment terminal"},
    ],
    pricingMultiplier=0.55,
    uniqueAngles=[
        "Cochin Shipyard built INS Vikrant — naval-grade weld inspection capability",
        "BPCL Kochi underwent IREP expansion 2017 — new units still in early service",
        "Backwater geography requires barge access for some inspections",
    ],
    nearbyMajorCities=["Trivandrum (220km)", "Chennai (700km)", "Bangalore (480km)"],
    turnaroundSeasons=["Avoid SW monsoon Jun-Sep", "Winter TARs Nov-Feb"],
)

add(
    "delhi-in",
    displayName="Delhi, India", country="IN", state="Delhi NCR", stateCode="IN-DL",
    tier=2, region="india-north", metroPopulation=32940000,
    industries=[
        {"name": "Engineering Consulting", "weight": 0.32, "context": "EIL HQ, MECON, IGCAR offices"},
        {"name": "Power Generation", "weight": 0.20, "context": "NTPC HQ, Delhi-NCR thermal plants"},
        {"name": "Refining (regional)", "weight": 0.15, "context": "IOC Mathura Refinery 200km south"},
        {"name": "Defense & Aerospace", "weight": 0.15, "context": "HAL Delhi, DRDO labs"},
    ],
    majorEmployers=["Engineers India Ltd (EIL)", "NTPC HQ", "IOC HQ",
        "GAIL HQ", "ONGC corporate office", "L&T Delhi", "Tata Power"],
    avgInspectorWageUSD={"level1": 13000, "level2": 21000, "level3": 40000},
    wageBandSource="ISNT North India 2024",
    regionalCodes=["IBR 1950", "CPCB pollution norms", "OISD-STD-105",
        "ASME Section V/VIII", "API 510/570/653", "IS:822 (welding)"],
    asntChapter="ISNT — Delhi Chapter",
    awsSection="IIW — Delhi",
    apiExamCenter=True, transportSurchargeBand="low", costOfLivingIndex=42,
    majorPortsRefineriesPlants=[
        {"name": "IOC Mathura Refinery", "type": "refinery", "scale": "160,000 bpd (200km south of Delhi)"},
        {"name": "NTPC Dadri", "type": "power", "scale": "1,820 MW (combined cycle + coal)"},
        {"name": "Delhi Metro / Airport infra", "type": "infrastructure", "scale": "Massive structural NDT scope"},
    ],
    pricingMultiplier=0.60,
    uniqueAngles=[
        "EIL Delhi designs most Indian refineries — inspection specs originate here",
        "NTPC HQ approves vendor pre-qualifications for all NTPC plants nationally",
        "Delhi NCR thermal power inspection (boiler, super-heater) is steady scope",
    ],
    nearbyMajorCities=["Gurgaon (30km)", "Noida (25km)", "Mathura (180km)"],
    turnaroundSeasons=["Winter TARs Nov-Feb", "Avoid summer extreme heat May-Jun"],
)

add(
    "kolkata-in",
    displayName="Kolkata, India", country="IN", state="West Bengal", stateCode="IN-WB",
    tier=2, region="india-east", metroPopulation=14850000,
    industries=[
        {"name": "Heavy Engineering", "weight": 0.32, "context": "BHEL Haridwar/Hyderabad operations + GRSE"},
        {"name": "Refining", "weight": 0.22, "context": "IOC Haldia Refinery 130km south"},
        {"name": "Port & Shipping", "weight": 0.20, "context": "Kolkata Port + Haldia Port"},
        {"name": "Steel", "weight": 0.15, "context": "SAIL HQ, Tata Steel Jamshedpur (300km)"},
    ],
    majorEmployers=["IOC Haldia Refinery", "BHEL", "GRSE (Garden Reach Shipbuilders)",
        "SAIL", "Coal India HQ", "Hindustan Copper", "ITC Limited"],
    avgInspectorWageUSD={"level1": 10000, "level2": 16000, "level3": 32000},
    wageBandSource="ISNT East India 2024",
    regionalCodes=["IBR 1950", "WBPCB pollution norms", "OISD-STD-105",
        "ASME Section V/VIII", "API 510/570/653"],
    asntChapter="ISNT — Kolkata Chapter",
    awsSection="IIW — Kolkata",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=30,
    majorPortsRefineriesPlants=[
        {"name": "IOC Haldia Refinery", "type": "refinery", "scale": "190,000 bpd (130km south)"},
        {"name": "Haldia Port", "type": "port", "scale": "Major bulk + container"},
        {"name": "GRSE Shipyard", "type": "shipyard", "scale": "Indian Navy frigates"},
    ],
    pricingMultiplier=0.50,
    uniqueAngles=[
        "Haldia is India's eastern refining anchor — different metallurgy than west coast",
        "GRSE naval shipbuilding requires defense-grade NDT (Indian Navy approvals)",
        "Coal India HQ approves vendor lists for nationwide coal washery inspection",
    ],
    nearbyMajorCities=["Haldia (130km)", "Bhubaneswar (440km)", "Patna (580km)"],
    turnaroundSeasons=["Winter TARs Nov-Feb", "Avoid monsoon Jun-Sep"],
)

add(
    "hyderabad-in",
    displayName="Hyderabad, India", country="IN", state="Telangana", stateCode="IN-TG",
    tier=2, region="india-south", metroPopulation=10800000,
    industries=[
        {"name": "Pharmaceuticals", "weight": 0.32, "context": "Bulk drug capital — Dr Reddy's, Aurobindo, Divis"},
        {"name": "Aerospace & Defense", "weight": 0.25, "context": "HAL + DRDO Hyderabad — Tejas, missile programs"},
        {"name": "Heavy Engineering", "weight": 0.18, "context": "BHEL Hyderabad — turbine generators"},
        {"name": "Petrochemicals", "weight": 0.10, "context": "HPCL Visakh Refinery 500km east"},
    ],
    majorEmployers=["HAL Hyderabad", "DRDL (DRDO Lab)", "BHEL Hyderabad",
        "Bharat Dynamics Ltd (BDL)", "Dr Reddy's Labs", "Aurobindo Pharma",
        "Divi's Labs", "L&T Hyderabad", "Tata Advanced Systems"],
    avgInspectorWageUSD={"level1": 11000, "level2": 18000, "level3": 36000},
    wageBandSource="ISNT South India 2024",
    regionalCodes=["IBR 1950", "Telangana State PCB", "OISD-STD-105",
        "AS9100 (aerospace)", "DGAQA (defense aerospace)"],
    asntChapter="ISNT — Hyderabad Chapter",
    awsSection="IIW — Hyderabad",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=34,
    majorPortsRefineriesPlants=[
        {"name": "BHEL Hyderabad", "type": "manufacturing", "scale": "Turbo-generator manufacturing"},
        {"name": "HAL Hyderabad Division", "type": "aerospace", "scale": "Missile components, avionics"},
        {"name": "Divi's API plant Vizag (500km)", "type": "pharma", "scale": "Largest API site globally"},
    ],
    pricingMultiplier=0.60,
    uniqueAngles=[
        "Aerospace NDT — Tejas fighter, BrahMos missile components",
        "BHEL turbine inspection — rotor balancing UT, blade ECT",
        "Pharma ultra-clean weld inspection (USP Class VI) is niche scope",
    ],
    nearbyMajorCities=["Bangalore (570km)", "Chennai (630km)", "Vijayawada (270km)"],
    turnaroundSeasons=["Winter TARs Nov-Feb"],
)

add(
    "bangalore-in",
    displayName="Bangalore, India", country="IN", state="Karnataka", stateCode="IN-KA",
    tier=2, region="india-south", metroPopulation=13600000,
    industries=[
        {"name": "Aerospace & Defense", "weight": 0.40, "context": "HAL HQ, NAL, ISRO, DRDO labs"},
        {"name": "Heavy Engineering", "weight": 0.20, "context": "BEML, BEL — defense electronics, mining equipment"},
        {"name": "Auto & Industrial", "weight": 0.18, "context": "Toyota Kirloskar, Volvo, Boeing India"},
    ],
    majorEmployers=["HAL HQ", "ISRO Antrix", "BEL (Bharat Electronics)",
        "BEML", "Toyota Kirloskar", "Boeing India", "L&T Bangalore",
        "Honeywell Aerospace India", "GE Aviation Bangalore"],
    avgInspectorWageUSD={"level1": 12000, "level2": 20000, "level3": 38000},
    wageBandSource="ISNT South India 2024",
    regionalCodes=["KSPCB pollution norms", "AS9100 aerospace QMS",
        "DGAQA defense", "Nadcap NDT (US-customer aerospace)",
        "ISRO IS-2102 quality standards"],
    asntChapter="ISNT — Bangalore Chapter (largest in South India)",
    awsSection="IIW — Bangalore",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=42,
    majorPortsRefineriesPlants=[
        {"name": "HAL Bangalore", "type": "aerospace", "scale": "India's largest aerospace manufacturer"},
        {"name": "ISRO Satellite Centre", "type": "aerospace", "scale": "India's space program"},
        {"name": "Toyota Bidadi Plant", "type": "auto", "scale": "300,000 vehicles/year"},
    ],
    pricingMultiplier=0.65,
    uniqueAngles=[
        "Nadcap NDT (US aerospace customers) is the gold standard here — Boeing, GE",
        "ISRO satellite component inspection — unique space-grade requirements",
        "HAL produces LCA Tejas, ALH Dhruv — defense-grade NDT scope",
    ],
    nearbyMajorCities=["Chennai (350km)", "Hyderabad (570km)", "Mysore (140km)"],
    turnaroundSeasons=["Year-round (mild climate)"],
)

add(
    "pune-in",
    displayName="Pune, India", country="IN", state="Maharashtra", stateCode="IN-MH",
    tier=2, region="india-west", metroPopulation=7300000,
    industries=[
        {"name": "Automotive", "weight": 0.42, "context": "Tata Motors, Mahindra, Bajaj, Mercedes-Benz"},
        {"name": "Heavy Engineering", "weight": 0.22, "context": "Cummins India, Forbes Marshall, Bharat Forge"},
        {"name": "IT & Services", "weight": 0.15, "context": "TCS, Infosys, Persistent (some inspection consulting)"},
    ],
    majorEmployers=["Tata Motors", "Mahindra & Mahindra", "Bajaj Auto",
        "Mercedes-Benz India", "Cummins India", "Bharat Forge",
        "Forbes Marshall", "Thermax", "John Deere India"],
    avgInspectorWageUSD={"level1": 11000, "level2": 18000, "level3": 35000},
    wageBandSource="ISNT West India 2024",
    regionalCodes=["MPCB pollution norms", "ASME Section V/VIII",
        "ISO 9712", "AIS standards (auto industry)"],
    asntChapter="ISNT — Pune Chapter",
    awsSection="IIW — Pune",
    apiExamCenter=False, transportSurchargeBand="low", costOfLivingIndex=38,
    majorPortsRefineriesPlants=[
        {"name": "Bharat Forge Mundhwa", "type": "forging", "scale": "World's largest commercial forging plant"},
        {"name": "Tata Motors Pimpri", "type": "auto", "scale": "Trucks + passenger cars"},
        {"name": "Cummins Engine Plant", "type": "manufacturing", "scale": "Diesel engines for global markets"},
    ],
    pricingMultiplier=0.55,
    uniqueAngles=[
        "Bharat Forge — automotive crankshaft UT inspection at scale",
        "Cummins diesel engine castings — RT and MT for ASTM A217 castings",
        "Auto industry weld inspection (resistance, MIG/MAG) — scaled robotic",
    ],
    nearbyMajorCities=["Mumbai (150km)", "Nashik (210km)", "Aurangabad (240km)"],
    turnaroundSeasons=["Winter TARs Nov-Feb", "Avoid monsoon Jun-Sep"],
)

add(
    "visakhapatnam-in",
    displayName="Visakhapatnam, India", country="IN", state="Andhra Pradesh", stateCode="IN-AP",
    tier=2, region="india-east", metroPopulation=2300000,
    industries=[
        {"name": "Refining", "weight": 0.38, "context": "HPCL Visakh Refinery — 300,000 bpd"},
        {"name": "Steel", "weight": 0.22, "context": "RINL Vizag Steel Plant — 7.3 MTPA"},
        {"name": "Port & Shipping", "weight": 0.18, "context": "Vizag Port + Hindustan Shipyard"},
        {"name": "Naval & Defense", "weight": 0.12, "context": "Eastern Naval Command HQ"},
    ],
    majorEmployers=["HPCL Visakh Refinery", "RINL Vizag Steel",
        "Hindustan Shipyard", "Indian Navy Eastern Command",
        "Andhra Pradesh Heavy Machinery", "Petronet LNG (Dahej-Vizag pipeline)"],
    avgInspectorWageUSD={"level1": 10000, "level2": 16000, "level3": 32000},
    wageBandSource="ISNT South India 2024",
    regionalCodes=["IBR 1950", "APPCB pollution norms", "OISD-STD-105",
        "IRS classification (shipyard)", "ASME Section V/VIII"],
    asntChapter="ISNT — Visakhapatnam Chapter",
    awsSection="IIW — Vizag",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=28,
    majorPortsRefineriesPlants=[
        {"name": "HPCL Visakh Refinery", "type": "refinery", "scale": "300,000 bpd"},
        {"name": "RINL Vizag Steel Plant", "type": "steel", "scale": "7.3 MTPA integrated steel"},
        {"name": "Vizag Port", "type": "port", "scale": "Largest port in India by tonnage"},
        {"name": "Hindustan Shipyard", "type": "shipyard", "scale": "Defense + commercial vessels"},
    ],
    pricingMultiplier=0.50,
    uniqueAngles=[
        "RINL Vizag Steel — only major Indian steel plant with all integrated NDT in-house",
        "Eastern Naval Command shipyard — submarine NDT is rare specialty",
        "HPCL Visakh expansion + clean fuels project drives sustained scope",
    ],
    nearbyMajorCities=["Hyderabad (620km)", "Bhubaneswar (440km)", "Chennai (820km)"],
    turnaroundSeasons=["Avoid cyclone season May-Nov", "Winter TARs Dec-Feb"],
)

add(
    "rio-de-janeiro-br",
    displayName="Rio de Janeiro, Brazil", country="BR", state="Rio de Janeiro", stateCode="BR-RJ",
    tier=1, region="latam", metroPopulation=13500000,
    industries=[
        {"name": "Offshore Oil & Gas", "weight": 0.55, "context": "Petrobras HQ; pre-salt Santos Basin operations"},
        {"name": "Refining", "weight": 0.18, "context": "REDUC Refinery 30km north"},
        {"name": "Shipbuilding (offshore)", "weight": 0.12, "context": "Niteroi shipyards — FPSO conversion"},
        {"name": "Petrochemicals", "weight": 0.08, "context": "Comperj (Itaboraí) under construction"},
    ],
    majorEmployers=["Petrobras (HQ at Av. República do Chile)",
        "Shell Brasil", "Equinor Brazil", "TotalEnergies Brasil",
        "REDUC Refinery (Petrobras)", "Yinson FPSO operations",
        "MODEC FPSO", "SBM Offshore"],
    avgInspectorWageUSD={"level1": 22000, "level2": 36000, "level3": 65000},
    wageBandSource="ABENDI Brazil salary survey 2024",
    regionalCodes=["NR-13 (boilers + pressure vessels — mandatory)",
        "Petrobras N-Standards (N-1738, N-2055 NDT)",
        "ANP regulations (oil sector)", "ASME Section V/VIII"],
    asntChapter="ABENDI (Brazilian Association for NDT) — Rio Section (HQ)",
    awsSection="ABS Brazil (welding)",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=58,
    majorPortsRefineriesPlants=[
        {"name": "REDUC Refinery", "type": "refinery", "scale": "242,000 bpd (Duque de Caxias)"},
        {"name": "Pre-Salt Santos Basin (offshore)", "type": "offshore-field", "scale": "World's largest deep-water oil discovery"},
        {"name": "Port of Rio de Janeiro", "type": "port", "scale": "Major container + bulk"},
        {"name": "Niteroi shipyards", "type": "shipyard", "scale": "FPSO conversions"},
    ],
    pricingMultiplier=0.85,
    uniqueAngles=[
        "Petrobras N-1738 is the de facto Brazilian NDT inspector qualification",
        "Pre-salt offshore inspection is the largest sustained market in Brazil",
        "FPSO topsides modules built/inspected in Niteroi/Macae before tow-out",
    ],
    nearbyMajorCities=["Macae (190km)", "Sao Paulo (430km)", "Vitoria (520km)"],
    turnaroundSeasons=["Winter TARs Apr-Oct (avoid summer humidity)"],
)

add(
    "macae-br",
    displayName="Macaé, Brazil", country="BR", state="Rio de Janeiro", stateCode="BR-RJ",
    tier=2, region="latam", metroPopulation=260000,
    industries=[
        {"name": "Offshore Oil & Gas Services", "weight": 0.75, "context": "Brazilian offshore capital — Campos Basin operations base"},
        {"name": "Logistics & Heliports", "weight": 0.15, "context": "Helicopter base for offshore crew change"},
    ],
    majorEmployers=["Petrobras Macae", "Halliburton Brasil", "Schlumberger Brasil",
        "Baker Hughes Brasil", "Subsea 7 Brasil", "TechnipFMC Brasil",
        "Yinson", "MODEC", "BW Offshore"],
    avgInspectorWageUSD={"level1": 25000, "level2": 40000, "level3": 72000},
    wageBandSource="ABENDI Macae rate card 2024",
    regionalCodes=["NR-13 + NR-37 (offshore platforms)",
        "Petrobras N-Standards", "ANP regulations", "ASME Section V/VIII"],
    asntChapter="ABENDI — Macae Branch",
    awsSection="ABS Brazil",
    apiExamCenter=False, transportSurchargeBand="high", costOfLivingIndex=62,
    majorPortsRefineriesPlants=[
        {"name": "Campos Basin (offshore)", "type": "offshore-field", "scale": "Brazil's first major offshore field — declining but still major"},
        {"name": "Macae helibase", "type": "logistics", "scale": "Largest helicopter operation in LatAm"},
        {"name": "Imetame Logística (port)", "type": "port", "scale": "Offshore supply base"},
    ],
    pricingMultiplier=1.00,
    uniqueAngles=[
        "Macae is Brazilian offshore inspector base — most contractors are stationed here",
        "NR-37 (offshore platforms) requires specific Brazilian offshore qualification",
        "Inspector rotation: 14/21 or 21/21 with Petrobras crew change schedules",
    ],
    nearbyMajorCities=["Rio de Janeiro (190km)", "Vitoria (380km)"],
    turnaroundSeasons=["Year-round offshore operations"],
)

add(
    "villahermosa-mx",
    displayName="Villahermosa, Mexico", country="MX", state="Tabasco", stateCode="MX-TAB",
    tier=2, region="latam", metroPopulation=850000,
    industries=[
        {"name": "Oil & Gas (PEMEX upstream)", "weight": 0.60, "context": "PEMEX southern region HQ; Cantarell + Ku-Maloob-Zaap operations"},
        {"name": "Petrochemicals", "weight": 0.18, "context": "PEMEX Petroquímica complex"},
        {"name": "Refining", "weight": 0.10, "context": "PEMEX Cangrejera Reynosa 250km away"},
    ],
    majorEmployers=["PEMEX Exploración y Producción", "PEMEX Logística",
        "Schlumberger Mexico", "Halliburton Mexico", "Baker Hughes Mexico",
        "ICA Fluor", "Subsea 7 Mexico"],
    avgInspectorWageUSD={"level1": 18000, "level2": 30000, "level3": 55000},
    wageBandSource="PEMEX contractor rate card 2024",
    regionalCodes=["NOM-093-STPS (welding + NDT)", "PEMEX P.2.0411.01 (NDT specs)",
        "ASME Section V/VIII (adopted)", "API 510/570/653"],
    asntChapter="MEXNDE (Mexican NDE Society) — Tabasco",
    awsSection="AWS Mexico Section",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=42,
    majorPortsRefineriesPlants=[
        {"name": "Cantarell Field (offshore)", "type": "offshore-field", "scale": "Historically world's 2nd largest oil field"},
        {"name": "Ku-Maloob-Zaap field", "type": "offshore-field", "scale": "Mexico's current largest producing complex"},
        {"name": "Dos Bocas Refinery (200km)", "type": "refinery", "scale": "340,000 bpd new build, commissioning 2024-25"},
    ],
    pricingMultiplier=0.80,
    uniqueAngles=[
        "PEMEX southern region operations base — center for Bay of Campeche offshore work",
        "Heavy/sour crude requires specialized inspection metallurgy",
        "Helicopter logistics from Ciudad del Carmen for offshore platforms",
    ],
    nearbyMajorCities=["Ciudad del Carmen (180km)", "Veracruz (470km)", "Mexico City (790km)"],
    turnaroundSeasons=["Avoid hurricane season Jun-Nov", "Winter TARs Dec-Mar"],
)

add(
    "johannesburg-za",
    displayName="Johannesburg, South Africa", country="ZA", state="Gauteng", stateCode="ZA-GP",
    tier=2, region="africa", metroPopulation=11200000,
    industries=[
        {"name": "Mining & Minerals", "weight": 0.40, "context": "Gold + platinum mining HQs — Anglo American, Sibanye, Gold Fields"},
        {"name": "Petrochemicals", "weight": 0.22, "context": "Sasol Secunda + Sasolburg complexes 100-150km away"},
        {"name": "Power Generation", "weight": 0.15, "context": "Eskom HQ; coal-fired Mpumalanga plants"},
        {"name": "Steel & Heavy Engineering", "weight": 0.12, "context": "ArcelorMittal Vereeniging"},
    ],
    majorEmployers=["Sasol Secunda + Sasolburg", "Anglo American",
        "Sibanye-Stillwater", "Gold Fields", "Eskom",
        "ArcelorMittal South Africa", "PetroSA", "Bureau Veritas SA"],
    avgInspectorWageUSD={"level1": 18000, "level2": 32000, "level3": 58000},
    wageBandSource="SAIW (Southern African Institute of Welding) salary survey 2024",
    regionalCodes=["SANS 347 (pressure vessels)", "OHS Act 85 of 1993",
        "ASME Section V/VIII (adopted)", "API 510/570/653"],
    asntChapter="SAIW NDT Section + SAINT (South African Inst of NDT)",
    awsSection="SAIW (Southern African Institute of Welding) HQ",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=50,
    majorPortsRefineriesPlants=[
        {"name": "Sasol Secunda", "type": "synfuel-refinery", "scale": "Largest single-site synthetic-fuel plant in world"},
        {"name": "Sasolburg complex", "type": "petrochem", "scale": "Sasol original site"},
        {"name": "Eskom Kusile + Medupi", "type": "power", "scale": "Two of world's largest coal-fired plants"},
    ],
    pricingMultiplier=0.75,
    uniqueAngles=[
        "Sasol coal-to-liquid synfuel plants — unique high-temperature inspection regime",
        "Mining headgear and conveyor structural inspection is sizable scope",
        "Eskom power station tube inspection (boiler, super-heater) drives steady demand",
    ],
    nearbyMajorCities=["Pretoria (60km)", "Sasolburg (95km)", "Cape Town (1400km)"],
    turnaroundSeasons=["Winter TARs May-Aug (mild climate)"],
)

add(
    "cape-town-za",
    displayName="Cape Town, South Africa", country="ZA", state="Western Cape", stateCode="ZA-WC",
    tier=2, region="africa", metroPopulation=4900000,
    industries=[
        {"name": "Refining", "weight": 0.30, "context": "Astron Energy (former Caltex) Cape Town Refinery — currently shut, restart pending"},
        {"name": "Port & Shipyard", "weight": 0.25, "context": "Cape Town port — V&A Waterfront, ship repair"},
        {"name": "Wind & Renewables", "weight": 0.15, "context": "Western Cape wind cluster"},
        {"name": "Manufacturing", "weight": 0.18, "context": "Volkswagen Uitenhage 800km, Toyota Durban — regional auto"},
    ],
    majorEmployers=["Astron Energy Cape Town Refinery (status pending)",
        "PetroSA Mossel Bay (380km)", "Saldanha Steel", "Transnet Cape Town Port",
        "Eskom Koeberg Nuclear Plant", "SAIW Cape Town"],
    avgInspectorWageUSD={"level1": 17000, "level2": 30000, "level3": 55000},
    wageBandSource="SAIW Western Cape salary survey 2024",
    regionalCodes=["SANS 347", "OHS Act 85 of 1993", "Nuclear Regulator Act (Koeberg)",
        "ASME Section V/VIII", "API 510/570/653"],
    asntChapter="SAIW Cape Town Section",
    awsSection="SAIW Cape Town",
    apiExamCenter=False, transportSurchargeBand="medium", costOfLivingIndex=52,
    majorPortsRefineriesPlants=[
        {"name": "Astron Energy Refinery", "type": "refinery", "scale": "100,000 bpd (currently idle)"},
        {"name": "Eskom Koeberg Nuclear Plant", "type": "nuclear", "scale": "Africa's only commercial nuclear plant"},
        {"name": "Cape Town Port", "type": "port", "scale": "Major container + ship repair"},
        {"name": "Saldanha iron ore terminal (130km)", "type": "port", "scale": "Largest dry-bulk port in Africa"},
    ],
    pricingMultiplier=0.75,
    uniqueAngles=[
        "Koeberg Nuclear — only nuclear NDT market in Africa, ASME Section XI scope",
        "Saldanha Bay iron ore export terminal — conveyor and stockpile NDT",
        "Wind farm tower foundation inspection (Western Cape onshore wind)",
    ],
    nearbyMajorCities=["Saldanha Bay (130km)", "Mossel Bay (380km)", "Johannesburg (1400km)"],
    turnaroundSeasons=["Year-round (Mediterranean climate)"],
)

add(
    "ulsan-kr",
    displayName="Ulsan, South Korea", country="KR", state="Ulsan", stateCode="KR-26",
    tier=1, region="asia-east", metroPopulation=1140000,
    industries=[
        {"name": "Shipbuilding", "weight": 0.40, "context": "Hyundai Heavy Industries Ulsan — world's largest shipyard"},
        {"name": "Refining & Petrochemicals", "weight": 0.32, "context": "SK Energy Ulsan, S-Oil — major Asian refining hub"},
        {"name": "Automotive", "weight": 0.18, "context": "Hyundai Motor Ulsan plant — largest car factory in world"},
    ],
    majorEmployers=["Hyundai Heavy Industries Ulsan", "SK Energy Ulsan Refinery",
        "S-Oil Onsan Refinery", "Hyundai Motor Ulsan",
        "Korea Shipbuilding & Offshore Engineering (KSOE)",
        "Daewoo Shipbuilding (DSME) Geoje 100km", "Lotte Chemical"],
    avgInspectorWageUSD={"level1": 36000, "level2": 54000, "level3": 88000},
    wageBandSource="KOSHA Korea NDT salary survey 2024",
    regionalCodes=["KS B 0816 (UT)", "KS Industrial Standards",
        "ASME Section V/VIII (adopted)", "API 510/570/653",
        "DNV/ABS/Lloyd's classification (shipbuilding)"],
    asntChapter="KSNT (Korean Society for NDT) — Ulsan Branch",
    awsSection="KWS (Korean Welding Society)",
    apiExamCenter=True, transportSurchargeBand="low", costOfLivingIndex=78,
    majorPortsRefineriesPlants=[
        {"name": "SK Energy Ulsan Refinery", "type": "refinery", "scale": "850,000 bpd — Asia's largest refinery"},
        {"name": "S-Oil Onsan Refinery", "type": "refinery", "scale": "669,000 bpd"},
        {"name": "Hyundai Heavy Industries Ulsan", "type": "shipyard", "scale": "World's largest shipyard"},
        {"name": "Hyundai Motor Ulsan Plant", "type": "auto", "scale": "1.4M vehicles/year — largest car factory"},
    ],
    pricingMultiplier=0.95,
    uniqueAngles=[
        "Hyundai Ulsan shipyard — LNG carrier / FPSO building drives massive NDT scope",
        "SK Energy Ulsan is Asia's largest single-site refinery",
        "Auto + ship + refinery in one city — diverse inspection skill demand",
    ],
    nearbyMajorCities=["Busan (60km)", "Pohang (110km)", "Seoul (350km)"],
    turnaroundSeasons=["Spring TARs Apr-May", "Autumn TARs Sep-Oct"],
)

add(
    "perth-au",
    displayName="Perth, Australia", country="AU", state="Western Australia", stateCode="AU-WA",
    tier=1, region="oceania", metroPopulation=2200000,
    industries=[
        {"name": "LNG & Gas", "weight": 0.35, "context": "Gorgon, Wheatstone, North West Shelf — operations base"},
        {"name": "Iron Ore Mining", "weight": 0.25, "context": "Pilbara mining — Rio Tinto, BHP, FMG HQs"},
        {"name": "Offshore Oil & Gas", "weight": 0.22, "context": "Browse, Greater Sunrise — operations from Perth"},
        {"name": "Refining & Alumina", "weight": 0.10, "context": "Kwinana Industrial Area"},
    ],
    majorEmployers=["Chevron Australia (Gorgon, Wheatstone)", "Woodside Energy",
        "BP Kwinana", "Rio Tinto Iron Ore", "BHP Iron Ore", "Fortescue Metals",
        "Worley Perth", "Wood Australia", "Monadelphous", "Acuren Australia"],
    avgInspectorWageUSD={"level1": 78000, "level2": 105000, "level3": 165000},
    wageBandSource="AINDT Western Australia 2024 (FIFO premium)",
    regionalCodes=["AS 4037 (pressure equipment)", "AS 1554 (welding)",
        "WA Mines Safety & Inspection Act", "AS/NZS 3788 (pressure equipment in-service)",
        "ASME Section V/VIII (adopted)", "API 510/570/653"],
    asntChapter="AINDT (Australian Institute for NDT) — WA Branch",
    awsSection="WTIA (Welding Technology Inst of Australia)",
    apiExamCenter=True, transportSurchargeBand="high", costOfLivingIndex=98,
    majorPortsRefineriesPlants=[
        {"name": "Gorgon LNG (Barrow Island)", "type": "lng", "scale": "15.6 MTPA — Chevron-operated"},
        {"name": "Wheatstone LNG (Onslow)", "type": "lng", "scale": "8.9 MTPA"},
        {"name": "North West Shelf (Karratha)", "type": "lng", "scale": "16.9 MTPA — Woodside-operated"},
        {"name": "Port of Port Hedland", "type": "port", "scale": "Largest iron ore export port in world"},
        {"name": "BP Kwinana Refinery", "type": "refinery", "scale": "Converted to import terminal 2021"},
    ],
    pricingMultiplier=1.30,
    uniqueAngles=[
        "FIFO (Fly-In Fly-Out) work model — Perth is the home base for Pilbara/NW Shelf",
        "Mining infrastructure inspection (conveyor, stacker-reclaimer, train loadout)",
        "LNG cryogenic inspection at Gorgon/Wheatstone — highly specialized",
    ],
    nearbyMajorCities=["Karratha (1500km via FIFO)", "Port Hedland (1600km FIFO)", "Adelaide (2700km)"],
    turnaroundSeasons=["Avoid Pilbara cyclone season Dec-Mar", "Winter TARs Jun-Aug"],
)

add(
    "brisbane-au",
    displayName="Brisbane, Australia", country="AU", state="Queensland", stateCode="AU-QLD",
    tier=2, region="oceania", metroPopulation=2660000,
    industries=[
        {"name": "Coal Mining & Export", "weight": 0.32, "context": "Bowen Basin coal exports via Hay Point, Abbot Point"},
        {"name": "LNG (Gladstone)", "weight": 0.25, "context": "Curtis Island LNG — APLNG, GLNG, QCLNG; 380km north"},
        {"name": "Refining", "weight": 0.14, "context": "Lytton Refinery (Ampol) — 109,000 bpd"},
        {"name": "Construction & Infrastructure", "weight": 0.18, "context": "Cross River Rail, Olympic 2032 prep"},
    ],
    majorEmployers=["BHP Mitsubishi Alliance (BMA)", "Glencore", "Anglo American",
        "Ampol Lytton Refinery", "Origin Energy (APLNG)", "Santos (GLNG)",
        "Shell QGC (QCLNG)", "Hatch", "Worley Brisbane", "AINDT QLD"],
    avgInspectorWageUSD={"level1": 70000, "level2": 95000, "level3": 145000},
    wageBandSource="AINDT QLD 2024",
    regionalCodes=["AS 4037, AS 1554, AS/NZS 3788",
        "QLD Coal Mining Safety & Health Act",
        "ASME Section V/VIII", "API 510/570/653"],
    asntChapter="AINDT — QLD Branch",
    awsSection="WTIA Queensland",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=88,
    majorPortsRefineriesPlants=[
        {"name": "Ampol Lytton Refinery", "type": "refinery", "scale": "109,000 bpd"},
        {"name": "Curtis Island LNG (Gladstone, 380km north)", "type": "lng", "scale": "3 LNG trains: APLNG, GLNG, QCLNG"},
        {"name": "Port of Hay Point", "type": "port", "scale": "World's largest coal export port"},
    ],
    pricingMultiplier=1.20,
    uniqueAngles=[
        "Curtis Island LNG (3 plants in 5km²) is unique inspection cluster",
        "Coal mining infrastructure NDT — train load-out, dragline boom inspection",
        "Coal seam gas (CSG) wellhead and pipeline scope across QLD basin",
    ],
    nearbyMajorCities=["Gold Coast (75km)", "Sunshine Coast (95km)", "Sydney (920km)"],
    turnaroundSeasons=["Avoid summer cyclone season Dec-Mar (Coast)"],
)

add(
    "melbourne-au",
    displayName="Melbourne, Australia", country="AU", state="Victoria", stateCode="AU-VIC",
    tier=2, region="oceania", metroPopulation=5160000,
    industries=[
        {"name": "Refining", "weight": 0.30, "context": "Viva Energy Geelong Refinery — 128,000 bpd"},
        {"name": "Manufacturing", "weight": 0.22, "context": "Boeing Melbourne, Saab Australia, defense industry hub"},
        {"name": "Power Generation", "weight": 0.18, "context": "Loy Yang A/B brown coal plants 150km"},
        {"name": "Construction", "weight": 0.15, "context": "Major rail/road projects — Metro Tunnel"},
    ],
    majorEmployers=["Viva Energy (Geelong Refinery)", "Boeing Melbourne (Fishermans Bend)",
        "Saab Australia", "Origin Energy", "BHP Melbourne offices",
        "Worley Melbourne", "Acuren Australia", "Bilfinger Australia"],
    avgInspectorWageUSD={"level1": 70000, "level2": 92000, "level3": 140000},
    wageBandSource="AINDT VIC 2024",
    regionalCodes=["AS 4037, AS 1554, AS/NZS 3788",
        "Victorian OHS Act", "ASME Section V/VIII", "API 510/570/653"],
    asntChapter="AINDT — VIC Branch (HQ)",
    awsSection="WTIA Victoria (HQ)",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Viva Energy Geelong Refinery", "type": "refinery", "scale": "128,000 bpd (only refinery in Victoria)"},
        {"name": "Loy Yang Power Stations (150km)", "type": "power", "scale": "3,300 MW brown coal"},
        {"name": "Port of Melbourne", "type": "port", "scale": "Australia's busiest container port"},
        {"name": "Boeing Aerostructures Australia", "type": "aerospace", "scale": "787 movable trailing edges"},
    ],
    pricingMultiplier=1.20,
    uniqueAngles=[
        "Geelong Refinery is Victoria's only refinery — strategic importance high",
        "Boeing 787 composite NDT (UT phased array, X-ray CT) is a unique skill set",
        "Brown coal power plants — distinctly different from black coal NDT regime",
    ],
    nearbyMajorCities=["Geelong (75km)", "Adelaide (730km)", "Sydney (880km)"],
    turnaroundSeasons=["Year-round operations"],
)

add(
    "sydney-au",
    displayName="Sydney, Australia", country="AU", state="New South Wales", stateCode="AU-NSW",
    tier=2, region="oceania", metroPopulation=5310000,
    industries=[
        {"name": "Refining", "weight": 0.18, "context": "Kurnell refinery converted to terminal 2014"},
        {"name": "Power & Steel", "weight": 0.20, "context": "Eraring power station, BlueScope Port Kembla 100km"},
        {"name": "Construction", "weight": 0.30, "context": "WestConnex, Sydney Metro, airport — major civil scope"},
        {"name": "Defense & Aerospace", "weight": 0.15, "context": "Sydney shipyards, naval defense"},
    ],
    majorEmployers=["BlueScope Steel (Port Kembla)", "Origin Energy Eraring",
        "Mortlake Power Station", "Sydney Trains", "Transgrid",
        "Worley Sydney", "Wood Australia Sydney", "ABS Australia"],
    avgInspectorWageUSD={"level1": 72000, "level2": 95000, "level3": 142000},
    wageBandSource="AINDT NSW 2024",
    regionalCodes=["AS 4037, AS 1554, AS/NZS 3788",
        "NSW Work Health & Safety Act", "ASME Section V/VIII"],
    asntChapter="AINDT — NSW Branch",
    awsSection="WTIA New South Wales",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=110,
    majorPortsRefineriesPlants=[
        {"name": "BlueScope Port Kembla Steelworks", "type": "steel", "scale": "Australia's largest steel plant"},
        {"name": "Eraring Power Station", "type": "power", "scale": "2,880 MW black coal"},
        {"name": "Port of Botany", "type": "port", "scale": "Sydney's main container port"},
        {"name": "Garden Island Naval Base", "type": "naval", "scale": "Major naval shipyard"},
    ],
    pricingMultiplier=1.25,
    uniqueAngles=[
        "BlueScope Port Kembla integrated steelworks — diverse NDT scope (caster, BOS, hot mill)",
        "Major construction infrastructure — bridges, tunnels structural NDT",
        "Naval NDT at Garden Island — Defence Materiel Organisation specs",
    ],
    nearbyMajorCities=["Wollongong (95km)", "Newcastle (160km)", "Canberra (290km)"],
    turnaroundSeasons=["Spring/Autumn TARs preferred"],
)

add(
    "toronto-on",
    displayName="Toronto, ON", country="CA", state="Ontario", stateCode="CA-ON",
    tier=2, region="canada-east", metroPopulation=6420000,
    industries=[
        {"name": "Manufacturing & Auto", "weight": 0.30, "context": "Ford Oakville, Stellantis Brampton, GM Oshawa"},
        {"name": "Power Generation", "weight": 0.22, "context": "Bruce + Pickering + Darlington nuclear plants 100-300km"},
        {"name": "Refining & Petrochem", "weight": 0.18, "context": "Imperial Sarnia (270km), Suncor Sarnia"},
        {"name": "Aerospace", "weight": 0.15, "context": "Bombardier Downsview, Pratt & Whitney Canada"},
    ],
    majorEmployers=["Ontario Power Generation (OPG)", "Bruce Power",
        "Imperial Oil Toronto HQ", "Bombardier Aviation",
        "Stellantis Brampton", "Ford Oakville", "Pratt & Whitney Canada (Mississauga)",
        "Acuren Canada", "Mistras Canada"],
    avgInspectorWageUSD={"level1": 52000, "level2": 72000, "level3": 115000},
    wageBandSource="Statistics Canada Toronto CMA 2024",
    regionalCodes=["CSA B51 (BPV)", "TSSA (Technical Standards & Safety Authority)",
        "CSA Z662 (pipelines)", "CSA N285 (nuclear)",
        "API 510/570/653", "Nadcap (aerospace)"],
    asntChapter="CINDE — Toronto Section",
    awsSection="CWB (Canadian Welding Bureau) — Eastern Canada",
    apiExamCenter=True, transportSurchargeBand="low", costOfLivingIndex=92,
    majorPortsRefineriesPlants=[
        {"name": "Bruce Nuclear Generating Station", "type": "nuclear", "scale": "World's largest operating nuclear plant"},
        {"name": "Pickering + Darlington Nuclear", "type": "nuclear", "scale": "Combined ~6,000 MW"},
        {"name": "Bombardier Downsview", "type": "aerospace", "scale": "Global 7500 final assembly"},
    ],
    pricingMultiplier=1.10,
    uniqueAngles=[
        "Ontario nuclear inspection — Bruce, Pickering, Darlington — CSA N285 specialty",
        "TSSA registration is the Ontario equivalent of ABSA in Alberta",
        "Aerospace MRO at Pratt & Whitney — Nadcap NDT certification dominant",
    ],
    nearbyMajorCities=["Mississauga (30km)", "Hamilton (70km)", "Ottawa (450km)"],
    turnaroundSeasons=["Spring/Fall TARs", "Avoid winter for outdoor work"],
)

add(
    "montreal-qc",
    displayName="Montréal, QC", country="CA", state="Québec", stateCode="CA-QC",
    tier=2, region="canada-east", metroPopulation=4290000,
    industries=[
        {"name": "Aerospace", "weight": 0.35, "context": "Bombardier, Pratt & Whitney Canada, Bell Helicopter, CAE"},
        {"name": "Refining & Petrochem", "weight": 0.20, "context": "Suncor Montreal Refinery, Valero Saint-Romuald (Lévis)"},
        {"name": "Aluminum", "weight": 0.15, "context": "Rio Tinto Alma + Arvida smelters (450km north)"},
        {"name": "Pulp & Paper", "weight": 0.12, "context": "Major Quebec mills"},
    ],
    majorEmployers=["Bombardier Aviation Montreal", "Pratt & Whitney Canada (Longueuil)",
        "Bell Helicopter Mirabel", "CAE", "Suncor Montreal Refinery",
        "Valero Saint-Romuald", "Rio Tinto Aluminium",
        "Acuren Canada", "Bureau Veritas"],
    avgInspectorWageUSD={"level1": 50000, "level2": 70000, "level3": 110000},
    wageBandSource="Statistics Canada Montreal CMA 2024",
    regionalCodes=["CSA B51", "Régie du bâtiment du Québec (RBQ)",
        "CSA Z662", "Nadcap (aerospace)", "TC CAR Part V (aviation)"],
    asntChapter="CINDE — Quebec Section",
    awsSection="CWB Quebec",
    apiExamCenter=True, transportSurchargeBand="low", costOfLivingIndex=82,
    majorPortsRefineriesPlants=[
        {"name": "Suncor Montreal Refinery", "type": "refinery", "scale": "137,000 bpd"},
        {"name": "Valero Saint-Romuald (Lévis)", "type": "refinery", "scale": "265,000 bpd (300km away)"},
        {"name": "Bombardier Mirabel", "type": "aerospace", "scale": "Global 7500 + CRJ assembly"},
        {"name": "Pratt & Whitney Canada", "type": "aero-engines", "scale": "PW100/PW150 + helicopter engines"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "Aerospace MRO + manufacturing concentration — Nadcap NDT is dominant credential",
        "RBQ certification specific to Quebec — separate from federal CSA",
        "Bilingual inspection reporting (English + French) often required",
    ],
    nearbyMajorCities=["Quebec City (250km)", "Ottawa (200km)", "Toronto (540km)"],
    turnaroundSeasons=["Spring/Fall TARs", "Avoid winter for outdoor work"],
)

add(
    "vancouver-bc",
    displayName="Vancouver, BC", country="CA", state="British Columbia", stateCode="CA-BC",
    tier=2, region="canada-west", metroPopulation=2640000,
    industries=[
        {"name": "Mining Services", "weight": 0.32, "context": "HQ for Teck Resources, Goldcorp/Newmont, Lundin"},
        {"name": "Pulp & Paper", "weight": 0.18, "context": "BC coastal mills"},
        {"name": "Pipeline & LNG", "weight": 0.20, "context": "Trans Mountain Expansion, Coastal GasLink, Kitimat LNG"},
        {"name": "Refining", "weight": 0.10, "context": "Parkland Burnaby Refinery — 55,000 bpd"},
        {"name": "Shipbuilding", "weight": 0.10, "context": "Seaspan Shipyards — National Shipbuilding Strategy"},
    ],
    majorEmployers=["Teck Resources HQ", "Newmont Vancouver",
        "Trans Mountain Pipeline", "Coastal GasLink", "Parkland Refining",
        "Seaspan Shipyards", "BC Hydro", "Worley Vancouver", "Acuren BC"],
    avgInspectorWageUSD={"level1": 56000, "level2": 76000, "level3": 118000},
    wageBandSource="Statistics Canada Vancouver CMA 2024",
    regionalCodes=["CSA B51 + BC Safety Authority Provincial Regs",
        "CSA Z662", "BC OGC (Oil & Gas Commission) regs",
        "API 510/570/653"],
    asntChapter="CINDE — BC Lower Mainland Section",
    awsSection="CWB BC",
    apiExamCenter=True, transportSurchargeBand="medium", costOfLivingIndex=110,
    majorPortsRefineriesPlants=[
        {"name": "Parkland Burnaby Refinery", "type": "refinery", "scale": "55,000 bpd (only BC refinery)"},
        {"name": "Trans Mountain Pipeline", "type": "pipeline", "scale": "Expansion 890,000 bpd"},
        {"name": "Port of Vancouver", "type": "port", "scale": "Largest port in Canada"},
        {"name": "Seaspan Shipyards", "type": "shipyard", "scale": "Royal Canadian Navy supply ships"},
    ],
    pricingMultiplier=1.15,
    uniqueAngles=[
        "Trans Mountain Expansion + Coastal GasLink — major pipeline NDT scope",
        "Mining sector consulting — many global mine inspections originate here",
        "BC OGC regulatory regime distinct from Alberta AER",
    ],
    nearbyMajorCities=["Seattle (230km)", "Calgary (970km)", "Victoria (across strait)"],
    turnaroundSeasons=["Year-round (mild Pacific climate)"],
)

add(
    "sarnia-on",
    displayName="Sarnia, ON", country="CA", state="Ontario", stateCode="CA-ON",
    tier=1, region="canada-east", metroPopulation=98000,
    industries=[
        {"name": "Petrochemicals", "weight": 0.55, "context": "Chemical Valley — densest petrochemical cluster in Canada"},
        {"name": "Refining", "weight": 0.30, "context": "Imperial Sarnia, Suncor Sarnia, Shell Sarnia"},
    ],
    majorEmployers=["Imperial Oil Sarnia Refinery", "Shell Sarnia Refinery",
        "Suncor Energy Sarnia", "Nova Chemicals (Corunna)",
        "Lanxess Sarnia", "Cabot Sarnia", "Ineos Styrolution",
        "Acuren Sarnia", "Mistras Sarnia"],
    avgInspectorWageUSD={"level1": 56000, "level2": 78000, "level3": 122000},
    wageBandSource="Sarnia Construction Association 2024",
    regionalCodes=["CSA B51", "TSSA", "Ontario MOECC regs",
        "API 510/570/653", "ASME Section V/VIII"],
    asntChapter="CINDE — Sarnia/Lambton Section",
    awsSection="CWB Sarnia",
    apiExamCenter=True, transportSurchargeBand="low", costOfLivingIndex=82,
    majorPortsRefineriesPlants=[
        {"name": "Imperial Oil Sarnia Refinery", "type": "refinery", "scale": "121,000 bpd"},
        {"name": "Suncor Sarnia Refinery", "type": "refinery", "scale": "85,000 bpd"},
        {"name": "Shell Sarnia Refinery", "type": "refinery", "scale": "75,000 bpd"},
        {"name": "Nova Chemicals Corunna", "type": "petrochem", "scale": "Major polyethylene complex"},
    ],
    pricingMultiplier=1.05,
    uniqueAngles=[
        "Sarnia 'Chemical Valley' — densest petrochem cluster in Canada (60+ sites in 25km²)",
        "Cross-border (Detroit metro 100km) inspector mobility is significant",
        "First Nations Aamjiwnaang community proximity drives stricter air emissions inspection",
    ],
    nearbyMajorCities=["Detroit MI (100km)", "Toronto (290km)", "London ON (95km)"],
    turnaroundSeasons=["Spring TARs Apr-May", "Fall TARs Sep-Oct"],
)


def main():
    repo_root = Path(__file__).resolve().parent.parent
    out = repo_root / "data" / "cities-batch2-international.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(CITIES, indent=2, ensure_ascii=False))
    print(f"Wrote {len(CITIES)} cities to {out}")


if __name__ == "__main__":
    main()
