import type { StateGuideContent } from '../types';

const state: StateGuideContent = {
  slug: 'ok',
  name: 'Oklahoma',
  abbreviation: 'OK',
  metaTitle: 'Oklahoma NDT Market Guide: Refining, Midstream & SCOOP/STACK',
  metaDescription:
    'Oklahoma is the Cushing oil hub of North America, runs 5 refineries (~535 kbpd), and anchors the SCOOP/STACK shale plays. NDT salaries, top metros, OCC pipeline regulators.',
  heroLede:
    "Cushing, Oklahoma — population under 8,000 — is the price-settlement delivery point for WTI crude futures and the largest crude oil storage terminal in the world (~76 million barrels of working capacity per EIA 2024). The state operates five refineries totaling 535,000 bpd, anchors the SCOOP (South Central Oklahoma Oil Province) and STACK (Sooner Trend, Anadarko, Canadian, Kingfisher) shale plays, and is the corporate home of Phillips 66, Williams Companies, and ONEOK — three of the largest US midstream operators. Pipeline density is the highest per capita in the country: more than 175,000 miles of pipeline cross Oklahoma. The Oklahoma Corporation Commission (OCC) Pipeline Safety Division regulates intrastate pipelines under OAC 165:20, while PHMSA covers interstate. Tornado season (March-June) compresses pre-summer turnaround inspection windows, and the integrity-management workload generated by Cushing tank inspection alone keeps a small army of API 653 inspectors busy year-round.",
  industryMix:
    "Five active refineries: Phillips 66 Ponca City (208,400 bpd, the largest), Valero Ardmore (90,000 bpd), HollyFrontier El Dorado (note: that is Kansas — Oklahoma's HF asset is Tulsa, 145,000 bpd), CHS McPherson (note: also Kansas — Oklahoma has CVR Energy's Wynnewood at 74,500 bpd), and Coffeyville (Kansas). Correct Oklahoma list: Phillips 66 Ponca City, Valero Ardmore, HF Tulsa, CVR Wynnewood, and the small WRB (Phillips 66 + Cenovus JV) at Borger (TX) draws OK crude. Cushing's role as the WTI delivery hub means roughly 13% of US working crude storage sits in one Payne County zip code; API 653 inspection on those tanks runs a continuous calendar through Magellan Midstream, Plains All American, Enbridge, Enterprise, and the Cushing terminal operators. Midstream is the second pillar: Williams Companies (HQ Tulsa) operates 33,000 miles of pipelines including the Transco system; ONEOK (HQ Tulsa) operates 50,000+ miles of NGL and natural gas pipelines; Enable Midstream (now part of Energy Transfer) and Targa Resources operate gathering and processing across the Anadarko and Arkoma basins. Upstream: SCOOP/STACK production (Devon, Continental Resources, Marathon Oil, Ovintiv) drives well-tubular and gathering-line inspection. Aerospace: Tinker Air Force Base (Oklahoma City) is the depot for the B-1B Lancer, B-52, KC-135, and E-3 Sentry — Tinker's Air Logistics Complex employs over 25,000 and runs continuous NAS 410 and military-standard NDT on engines, frames, and structures. Wind energy: Oklahoma is the third-largest wind state by installed capacity (~12 GW) — turbine blade and tower NDT is a growing adjacency. Boeing also operates a major facility in OKC (Tinker AFB co-located maintenance) and Tulsa supports MRO for Spirit AeroSystems and American Airlines' Tulsa base (1980s-era widebody MRO heart of the country).",
  topMetros: [
    { name: 'Tulsa', slug: 'tulsa-ok' },
    { name: 'Oklahoma City', slug: 'oklahoma-city-ok' },
    { name: 'Bartlesville', slug: 'bartlesville-ok' },
    { name: 'Cushing (regional, served from Tulsa)', slug: 'tulsa-ok' },
  ],
  regulatoryNotes: [
    { id: 'occ-pipeline', source: 'Oklahoma Corporation Commission, OAC Title 165 Chapter 20 — Pipeline Safety (intrastate gas and hazardous liquid)', url: 'https://oklahoma.gov/occ/divisions/pipeline-safety.html' },
    { id: 'odeq-air', source: 'Oklahoma Department of Environmental Quality, OAC 252:100 — Air Quality (drives LDAR and refinery tank inspection cadence)' },
    { id: 'occ-oil-gas', source: 'OCC Oil & Gas Conservation Division — well construction and integrity oversight (OAC 165:10)' },
    { id: 'odol-boiler', source: 'Oklahoma Department of Labor, Boiler Inspection Division — Title 40 §141 mandates National Board inservice inspection' },
    { id: 'phmsa-ok', source: 'PHMSA 49 CFR 192/195 — interstate transmission and hazardous liquid pipelines crossing Oklahoma' },
  ],
  majorAssetOwners: [
    { name: 'Phillips 66 (Ponca City refinery, Bartlesville HQ)', sector: 'Refining / Midstream' },
    { name: 'Williams Companies (Tulsa HQ — Transco, gathering)', sector: 'Midstream' },
    { name: 'ONEOK (Tulsa HQ — NGL and gas pipelines)', sector: 'Midstream' },
    { name: 'Magellan Midstream (Tulsa HQ — Cushing terminals)', sector: 'Midstream / Storage' },
    { name: 'Plains All American (Cushing storage and pipelines)', sector: 'Midstream / Storage' },
    { name: 'Enbridge (Cushing terminal)', sector: 'Midstream / Storage' },
    { name: 'Devon Energy (Oklahoma City HQ, SCOOP/STACK)', sector: 'Upstream' },
    { name: 'Continental Resources (Oklahoma City HQ)', sector: 'Upstream' },
    { name: 'Tinker Air Force Base — Oklahoma City Air Logistics Complex', sector: 'Aerospace / Defense MRO' },
    { name: 'American Airlines Tulsa Maintenance Base', sector: 'Aviation MRO' },
    { name: 'Spirit AeroSystems (Tulsa)', sector: 'Aerospace' },
    { name: 'Boeing (Oklahoma City — Tinker co-located)', sector: 'Aerospace / Defense' },
    { name: 'NextEra Energy (Oklahoma wind operations)', sector: 'Renewables' },
  ],
  methodDemand: [
    { method: 'Ultrasonic Testing (UT)', demandLevel: 'high', reason: 'API 653 baseline and follow-up thickness surveys on Cushing tank farms — a single tank can require 200-400 UT locations.' },
    { method: 'Magnetic Flux Leakage (MFL) / Tank Floor Scanning', demandLevel: 'high', reason: 'Bottom-plate inspection on every API 653 internal inspection at Cushing and refinery tankage. The biggest discriminator between OK NDT firms is MFL fleet size.' },
    { method: 'Radiographic Testing (RT)', demandLevel: 'high', reason: 'Midstream pipeline weld inspection on every new gathering system, transmission tie-in, and station retrofit. OCC and PHMSA both reference ASME B31.4 and B31.8 acceptance.' },
    { method: 'Phased Array UT (PAUT)', demandLevel: 'medium', reason: 'In-line and pipeline girth-weld inspection (corrosion mapping and ILI verification) plus refinery turnaround corrosion mapping. Demand growing as PHMSA Mega-Rule integrity programs expand.' },
    { method: 'Magnetic Particle Testing (MT)', demandLevel: 'medium', reason: 'Weld inspection on midstream stations and refinery turnaround weld repairs; oilfield drilling-asset inspection at upstream service yards in Elk City and Woodward.' },
    { method: 'Aerospace FPI / ECT', demandLevel: 'high', reason: 'Tinker AFB Air Logistics Complex runs NAS 410 Level II FPI and ECT inspection on B-1B, B-52, KC-135, and E-3 fleet — depot-level inspection volume is highest in DoD inventory.' },
    { method: 'In-Line Inspection (ILI) Support', demandLevel: 'high', reason: 'PHMSA integrity-management programs at Williams, ONEOK, Magellan, and Enbridge drive ILI tool runs that require follow-up NDT verification (UT, PAUT, MT) in the dig program.' },
    { method: 'Drone / Visual Inspection', demandLevel: 'medium', reason: 'Wind turbine blade inspection (~12 GW installed) is the fastest-growing OK NDT adjacency.' },
  ],
  certificationAvailability:
    "Tulsa Community College and Oklahoma State University Institute of Technology (OSUIT, Okmulgee) run ASNT SNT-TC-1A NDT certificate programs that feed Phillips 66, Williams, and ONEOK contractor pipelines. OSUIT also operates a dedicated aviation maintenance program tied to Tinker and the American Airlines MRO base. Rose State College (Midwest City) and Oklahoma City Community College feed Tinker's NDT inspector pipeline. The Hellier NDT Tulsa campus runs PAUT, TOFD, and ASNT Level III prep. API ICP exams (510, 570, 653) administered through Prometric Tulsa and Oklahoma City. AWS CWI seminars run quarterly in Tulsa and Oklahoma City. Radioactive source licensing is administered by ODEQ Radiation Management Section (Oklahoma is a Section 274b agreement state) under OAC 252:410. Tinker AFB operates internal Air Force NDT training aligned to MIL-HDBK-1823A and NAS 410.",
  salaryBands: [
    { role: 'Level I NDT Trainee', low: 38000, high: 52000 },
    { role: 'Level II UT/MT/PT Technician', low: 56000, high: 86000 },
    { role: 'Level II API 653 Tank Inspector', low: 75000, high: 115000 },
    { role: 'Level II PAUT / TOFD Specialist', low: 78000, high: 120000 },
    { role: 'Level III NDT Engineer', low: 105000, high: 160000 },
    { role: 'Pipeline Integrity Inspector (PHMSA / OCC)', low: 85000, high: 135000 },
    { role: 'Aerospace NDT (Tinker AFB / contractor)', low: 65000, high: 105000 },
  ],
  hiringSeasons:
    "Refining turnaround scheduling at Ponca City and Wynnewood follows Gulf Coast cadence (spring February-May, fall September-November). Cushing tank inspection campaigns are continuous but cluster around 5-year API 653 internal inspection cycles per individual tank — operators stagger to spread crew demand. Midstream pipeline construction and integrity dig programs accelerate in late spring through fall (after frost depth lifts), tapering through winter. Tinker AFB depot inspection is steady-state but expands when fleet retrofit programs (B-52 re-engine, B-1B service-life extension) ramp.",
  faqs: [
    {
      q: 'Why does Cushing dominate Oklahoma NDT demand?',
      a: "Cushing holds roughly 13% of US working crude oil storage capacity (~76 million barrels) across multiple operator terminals (Enbridge, Magellan, Plains All American, NuStar). Each tank operates on an API 653 inspection cycle: external inspection at 5-year intervals and out-of-service internal inspection generally on a 10-year maximum (or extendable based on prior corrosion rate per API 653 §6.4). With several hundred tanks aggregated, that translates into 20-40 internal inspections per year and continuous external inspection work. Each internal inspection drives UT thickness surveys (200-400 points), MFL floor scanning, courses of API 650 weld inspection, and roof structural inspection. A single contractor crew can spend 3-5 weeks on one tank, and there are simply not enough crews to spread the workload — Cushing is a permanent floor under Oklahoma's API 653 inspector market.",
    },
    {
      q: 'How does the Oklahoma Corporation Commission differ from PHMSA for pipeline NDT?',
      a: "The OCC Pipeline Safety Division acts as the state authority that administers federal pipeline safety regulations for intrastate operators under a PHMSA grant agreement, plus enforces state-specific requirements in OAC 165:20. For pipelines wholly within Oklahoma — including most gathering, intrastate transmission, and gas distribution — OCC is the inspector and enforcement authority. Interstate transmission pipelines (Williams Transco mainlines, ONEOK NGL trunklines crossing state lines) remain under direct PHMSA jurisdiction. Operationally, both authorities apply the same ASME B31.4/B31.8 inspection standards and 49 CFR 192/195 personnel qualification rules — the difference is which agency audits the operator's integrity-management program.",
    },
    {
      q: 'Is Tinker Air Force Base NDT work civilian, military, or contractor?',
      a: "All three. Tinker's Oklahoma City Air Logistics Complex employs Air Force civilian NDT inspectors (federal GS-9 to GS-12 grades for journey to senior, GS-13 for Level III) doing depot-level airframe and engine inspection. Military Air Force NDT technicians rotate through for skill maintenance. Contractor NDT (Boeing, Northrop Grumman, BAE Systems, Booz Allen) supports specific weapon-system programs and surge work. Civilian Air Force jobs require US citizenship and a Secret clearance for most roles; contractor jobs commonly require interim Secret with full clearance to follow. Certification is dual-stack: NAS 410 for civilian/contractor work, MIL-HDBK-1823A for military-managed inspection. Salaries on the civilian side track federal locality pay (OKC locality is below national average, partially offset by lower cost of living).",
    },
    {
      q: 'What does Oklahoma wind energy mean for NDT careers?',
      a: "Oklahoma operates ~12 GW of installed wind capacity (third in the US after Texas and Iowa per EIA 2023). Each utility-scale turbine has three blades, a nacelle, a tower, and tens of tons of fastened structure that require periodic inspection. Inspection cadence is operator-driven (Enel, NextEra, Invenergy) but typically follows a 5-year visual and structural baseline plus condition-driven follow-up. NDT methods used are predominantly visual (drone-based), eddy current (gear teeth and bolted joints), and ultrasonic (composite blade structural). Wind blade rope-access technicians earn $35-$60/hr field rate, with drone pilots at $45-$80/hr depending on certifications. The fleet is aging (many turbines were installed 2008-2015) so re-power and structural integrity inspection workload is growing year over year.",
    },
    {
      q: 'Can you build a full NDT career out of Tulsa without traveling?',
      a: "Yes, but it shapes the career path. Tulsa hosts Williams, ONEOK, and Magellan Midstream HQs, plus HF Tulsa refinery and the American Airlines MRO base — so an inspector can rotate between midstream pipeline integrity, refining turnaround, and aviation MRO inside the metro. The trade-off: less exposure to greenfield petrochem or LNG (those are Gulf Coast), and less PAUT specialty work than Houston or Lake Charles. Career-progression typically goes Level II UT/MT/PT → API 653 endorsement (Cushing-relevant) → API 570 endorsement (refining-relevant) → Level III. Aerospace-leaning techs migrate to Tinker (OKC, 90-minute drive) or Wichita (KS, 2.5-hour drive). A Tulsa-based inspection engineer in the integrity-management track can break $150,000 with 10+ years experience and an API 1169 (Pipeline Construction Inspector) credential.",
    },
  ],
  internalLinks: [
    { href: '/states/ks', label: 'Kansas NDT market guide', context: 'Kansas refining (HF El Dorado, CHS McPherson, Coffeyville) and Wichita aerospace share the Mid-Continent NDT contractor pool with Oklahoma.' },
    { href: '/states/tx', label: 'Texas NDT market guide', context: 'Oklahoma upstream and midstream operators frequently flex crews into the Permian (TX) and Eagle Ford during rig-count surges.' },
    { href: '/states/ar', label: 'Arkansas NDT market guide', context: 'Arkansas Mississippi River barge terminals and El Dorado refining create overlap with Oklahoma midstream contractor scheduling.' },
    { href: '/methods/ultrasonic-testing', label: 'Ultrasonic testing (UT)', context: 'UT thickness surveys dominate the Cushing tank inspection workload.' },
    { href: '/methods/magnetic-flux-leakage', label: 'Magnetic flux leakage (MFL) for tank floors', context: 'MFL tank-bottom scanning is the high-throughput method for API 653 internal inspection.' },
    { href: '/industries/midstream-pipelines', label: 'Midstream pipeline NDT', context: 'Oklahoma is the corporate home of three of the largest US midstream operators — Williams, ONEOK, and Magellan.' },
    { href: '/industries/oil-and-gas', label: 'Oil & gas NDT inspection', context: 'SCOOP and STACK upstream activity drives the largest portion of Oklahoma\'s upstream inspection demand.' },
    { href: '/standards/api-653', label: 'API 653 aboveground tank inspection', context: 'Cushing crude oil storage tanks all operate on API 653 inspection cycles.' },
    { href: '/standards/api-570', label: 'API 570 piping inspection', context: 'API 570 governs the refining piping circuits at Phillips 66 Ponca City, Wynnewood, and Tulsa.' },
    { href: '/standards/asme-b31-4', label: 'ASME B31.4 liquid pipeline transportation', context: 'B31.4 is the design and inspection code for hazardous liquid pipelines crossing Oklahoma — Cushing in and out is all B31.4 territory.' },
    { href: '/careers/tulsa-ok', label: 'NDT careers in Tulsa', context: 'Tulsa is the corporate-HQ density anchor for Oklahoma midstream careers.' },
    { href: '/cost-guide/tulsa-ok/ut', label: 'Tulsa UT cost guide', context: 'Tulsa UT rates lag Houston by approximately 8-12% but per-diem on Cushing campaigns can close the gap.' },
  ],
  citations: [
    { id: 'eia-cushing-2024', source: 'EIA Working Crude Oil Storage Capacity Report 2024 — Cushing 76+ MMbbl', url: 'https://www.eia.gov/petroleum/storagecapacity/' },
    { id: 'eia-ok-refining', source: 'EIA Refinery Capacity Report 2023 — Oklahoma 535,000 bpd' },
    { id: 'occ-oac-165', source: 'Oklahoma Corporation Commission OAC Title 165 Chapter 20 — Pipeline Safety', url: 'https://oklahoma.gov/occ/' },
    { id: 'odeq-rad', source: 'ODEQ Radiation Management Section OAC 252:410 — Radioactive Materials Licensing' },
    { id: 'phmsa-ok-mou', source: 'PHMSA-OCC State Agreement for Pipeline Safety Inspection' },
    { id: 'api-653-2014', source: 'API 653 Tank Inspection, Repair, Alteration, and Reconstruction, 5th ed., 2014 (Addendum 2018)' },
    { id: 'api-1169-2020', source: 'API 1169 Pipeline Construction Inspector — Body of Knowledge' },
    { id: 'awea-2023', source: 'American Clean Power Association — Oklahoma 12 GW wind capacity (2023)' },
  ],
};

export default state;
