// ============================================================
// NDT Connect - Comprehensive Standards Database
// 100+ NDT Standards for Industries and Methods
// ============================================================

export interface NDTStandard {
  slug: string;
  code: string;
  title: string;
  organization: string;
  description: string;
  methods: string[];
  industries: string[];
  country?: string;
}

export const ndtStandards: NDTStandard[] = [
  // ASME Standards
  {
    slug: 'asme-section-v',
    code: 'ASME Section V',
    title: 'Nondestructive Examination',
    organization: 'ASME (American Society of Mechanical Engineers)',
    description: 'Comprehensive standard covering all nondestructive examination methods including ultrasonic, radiographic, magnetic particle, penetrant, eddy current, and visual testing. ASME Section V is the most widely referenced NDT standard in North America for pressure vessels, power generation equipment, and industrial applications. It specifies procedure requirements, acceptance criteria, and personnel qualification standards.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Liquid Penetrant Testing', 'Eddy Current Testing', 'Visual Testing'],
    industries: ['Power Generation', 'Oil & Gas', 'Petrochemical', 'Manufacturing'],
    country: 'USA',
  },
  {
    slug: 'asme-bpvc',
    code: 'ASME BPVC',
    title: 'Boiler and Pressure Vessel Code',
    organization: 'ASME',
    description: 'Comprehensive code for design, fabrication, inspection, and certification of boilers and pressure vessels. ASME BPVC includes Section V (NDT requirements) and Section VIII (pressure vessel design). Compliance with BPVC is legally required in most jurisdictions for commercial pressure vessels. Regular NDT inspection is mandated to ensure safety.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Liquid Penetrant Testing', 'Visual Testing'],
    industries: ['Power Generation', 'Oil & Gas', 'Petrochemical', 'Manufacturing'],
    country: 'USA',
  },

  // API Standards
  {
    slug: 'api-510',
    code: 'API 510',
    title: 'Pressure Vessel Inspection Code',
    organization: 'API (American Petroleum Institute)',
    description: 'Mandatory standard for in-service inspection, maintenance, repair, and rerating of pressure vessels in the petroleum industry. API 510 specifies inspection intervals, NDT methods, acceptance criteria, and fitness-for-service assessments. Compliance with API 510 is required by law in most petroleum facilities. Inspector certifications per API 510 are industry credentials.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Liquid Penetrant Testing'],
    industries: ['Oil & Gas', 'Petrochemical', 'Power Generation'],
    country: 'USA',
  },
  {
    slug: 'api-570',
    code: 'API 570',
    title: 'Pipeline Inspection Code',
    organization: 'API',
    description: 'Standard for in-service inspection, maintenance, repair, and rerating of oil and gas pipelines. API 570 mandates periodic external ultrasonic thickness inspections, pigging (internal inspection), radiography of repairs, and visual inspections. Compliance with API 570 is legally required for pipeline safety. API 570 inspector certification is recognized globally.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Visual Testing'],
    industries: ['Oil & Gas', 'Pipeline', 'Petrochemical'],
    country: 'USA',
  },
  {
    slug: 'api-653',
    code: 'API 653',
    title: 'Tank Inspection, Repair, Alteration, and Reconstruction',
    organization: 'API',
    description: 'Standard covering in-service inspection and maintenance of aboveground petroleum storage tanks. API 653 specifies internal and external inspection requirements, ultrasonic thickness measurements for corrosion monitoring, radiography of repairs, and fitness-for-service assessments. Compliance is required in most petroleum facilities. API 653 inspectors must have special qualifications.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Visual Testing'],
    industries: ['Oil & Gas', 'Petrochemical', 'Storage'],
    country: 'USA',
  },
  {
    slug: 'api-1104',
    code: 'API 1104',
    title: 'Standard for Welding of Pipelines and Related Appurtenances',
    organization: 'API',
    description: 'Welding standard for oil and gas pipelines covering welder qualification, welding procedures, and inspection requirements. API 1104 mandates radiographic and ultrasonic inspection of welds with specific acceptance criteria. This standard is widely used in pipeline construction and operations worldwide. Welder qualifications per API 1104 are accepted internationally.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Visual Testing'],
    industries: ['Pipeline', 'Oil & Gas', 'Construction'],
    country: 'USA',
  },
  {
    slug: 'api-579',
    code: 'API 579',
    title: 'Fitness-For-Service',
    organization: 'API',
    description: 'Comprehensive standard for systematic fitness-for-service assessment of components with detected defects. API 579 provides methods for determining whether components with flaws can continue safe operation. It combines NDT results, material properties, and fracture mechanics analysis. API 579 allows safe continued service of components with minor defects that would otherwise require replacement.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Visual Testing', 'All NDT Methods'],
    industries: ['Oil & Gas', 'Petrochemical', 'Power Generation', 'Manufacturing'],
    country: 'USA',
  },

  // ASTM Standards
  {
    slug: 'astm-e164',
    code: 'ASTM E164',
    title: 'Standard Practice for Ultrasonic Contact Testing of Weldments',
    organization: 'ASTM International',
    description: 'Standard practice for ultrasonic testing of welds using contact method with straight and angle-beam transducers. ASTM E164 covers equipment requirements, procedures, and acceptance criteria for weld inspection. It is widely referenced in construction and fabrication specifications.',
    methods: ['Ultrasonic Testing'],
    industries: ['Construction', 'Manufacturing', 'Aerospace'],
    country: 'USA',
  },
  {
    slug: 'astm-e165',
    code: 'ASTM E165',
    title: 'Standard Practice for Liquid Penetrant Examination',
    organization: 'ASTM International',
    description: 'Comprehensive standard for liquid penetrant testing procedures, equipment, materials, and acceptance criteria. ASTM E165 covers all aspects of penetrant testing from surface preparation through defect evaluation. It is the primary US standard for PT inspection.',
    methods: ['Liquid Penetrant Testing'],
    industries: ['Aerospace', 'Manufacturing', 'Power Generation', 'Oil & Gas'],
    country: 'USA',
  },
  {
    slug: 'astm-e709',
    code: 'ASTM E709',
    title: 'Standard Guide for Magnetic Particle Testing',
    organization: 'ASTM International',
    description: 'Guide for magnetic particle testing procedures, equipment calibration, acceptance criteria, and defect evaluation. ASTM E709 covers both AC and DC magnetization methods. It provides detailed information on technique variations and is widely referenced in fabrication and in-service inspection specifications.',
    methods: ['Magnetic Particle Testing'],
    industries: ['Manufacturing', 'Aerospace', 'Oil & Gas', 'Automotive'],
    country: 'USA',
  },
  {
    slug: 'astm-e1444',
    code: 'ASTM E1444',
    title: 'Standard Practice for Magnetic Particle Testing',
    organization: 'ASTM International',
    description: 'Practice for magnetic particle testing providing detailed procedures for surface preparation, magnetization, particle application, and interpretation. ASTM E1444 is a comprehensive reference for MT practitioners.',
    methods: ['Magnetic Particle Testing'],
    industries: ['Manufacturing', 'Aerospace', 'Oil & Gas'],
    country: 'USA',
  },
  {
    slug: 'astm-e94',
    code: 'ASTM E94',
    title: 'Standard Guide for Radiographic Examination',
    organization: 'ASTM International',
    description: 'Comprehensive guide for industrial radiography including X-ray and gamma ray methods. ASTM E94 covers equipment, procedures, film quality, exposure parameters, and interpretation. It is the primary US standard for industrial radiography.',
    methods: ['Radiographic Testing'],
    industries: ['Oil & Gas', 'Manufacturing', 'Construction', 'Aerospace'],
    country: 'USA',
  },
  {
    slug: 'astm-e1032',
    code: 'ASTM E1032',
    title: 'Standard Practice for Radiography of Welds',
    organization: 'ASTM International',
    description: 'Practice for radiographic examination of welds providing detailed procedures for equipment setup, exposure techniques, film processing, and weld acceptance criteria. ASTM E1032 is widely referenced in welding specifications.',
    methods: ['Radiographic Testing'],
    industries: ['Construction', 'Manufacturing', 'Pipeline'],
    country: 'USA',
  },
  {
    slug: 'astm-e1417',
    code: 'ASTM E1417',
    title: 'Standard Practice for Liquid Penetrant Testing of Welds',
    organization: 'ASTM International',
    description: 'Practice for liquid penetrant testing of welds covering equipment, procedures, and acceptance criteria specific to weld inspection. ASTM E1417 complements ASTM E165 with weld-specific guidance.',
    methods: ['Liquid Penetrant Testing'],
    industries: ['Manufacturing', 'Construction', 'Aerospace'],
    country: 'USA',
  },
  {
    slug: 'astm-e243',
    code: 'ASTM E243',
    title: 'Standard Practice for Eddy Current Testing',
    organization: 'ASTM International',
    description: 'Guide for eddy current testing procedures covering equipment, probe selection, interpretation, and defect sizing. ASTM E243 is the primary US standard for ET applications.',
    methods: ['Eddy Current Testing'],
    industries: ['Aerospace', 'Manufacturing', 'Power Generation', 'Oil & Gas'],
    country: 'USA',
  },
  {
    slug: 'astm-e376',
    code: 'ASTM E376',
    title: 'Standard Practice for Measuring Coating Thickness by Eddy Current',
    organization: 'ASTM International',
    description: 'Practice for using eddy current methods to measure nonmagnetic coating thickness on ferromagnetic substrates. ASTM E376 is widely used for quality control in coating applications.',
    methods: ['Eddy Current Testing'],
    industries: ['Manufacturing', 'Construction', 'Marine'],
    country: 'USA',
  },
  {
    slug: 'astm-e2375',
    code: 'ASTM E2375',
    title: 'Standard Practice for Ultrasonic Testing of Wrought Steel Forgings',
    organization: 'ASTM International',
    description: 'Practice for ultrasonic inspection of large steel forgings with procedures optimized for coarse-grained materials. ASTM E2375 addresses challenges of inspecting thick forgings.',
    methods: ['Ultrasonic Testing'],
    industries: ['Aerospace', 'Power Generation', 'Manufacturing'],
    country: 'USA',
  },
  {
    slug: 'astm-e2491',
    code: 'ASTM E2491',
    title: 'Standard Practice for Phased Array Ultrasonic Testing',
    organization: 'ASTM International',
    description: 'Practice for phased array ultrasonic testing covering equipment, calibration, and acceptance criteria. ASTM E2491 is the primary US standard for advanced UT methods.',
    methods: ['Phased Array Ultrasonic Testing'],
    industries: ['Oil & Gas', 'Power Generation', 'Aerospace', 'Manufacturing'],
    country: 'USA',
  },
  {
    slug: 'astm-e2373',
    code: 'ASTM E2373',
    title: 'Standard Practice for Ultrasonic Testing of Wrought Steel Using TOFD',
    organization: 'ASTM International',
    description: 'Practice for time-of-flight diffraction ultrasonic testing covering procedures, calibration, and acceptance criteria. ASTM E2373 standardizes advanced TOFD methods.',
    methods: ['Time-of-Flight Diffraction'],
    industries: ['Oil & Gas', 'Power Generation', 'Pipeline'],
    country: 'USA',
  },
  {
    slug: 'astm-e2775',
    code: 'ASTM E2775',
    title: 'Standard Practice for Guided Wave Testing of Piping',
    organization: 'ASTM International',
    description: 'Practice for guided wave ultrasonic testing of piping for rapid screening of insulated or inaccessible sections. ASTM E2775 covers equipment, procedures, and interpretation.',
    methods: ['Guided Wave Testing'],
    industries: ['Oil & Gas', 'Power Generation', 'Petrochemical'],
    country: 'USA',
  },
  {
    slug: 'astm-e96',
    code: 'ASTM E96',
    title: 'Standard Practice for Radiography of Castings',
    organization: 'ASTM International',
    description: 'Practice for radiographic inspection of castings covering exposure parameters, film processing, and acceptance criteria. ASTM E96 addresses challenges of radiographing complex casting geometry.',
    methods: ['Radiographic Testing'],
    industries: ['Manufacturing', 'Aerospace', 'Automotive'],
    country: 'USA',
  },

  // AWS Standards
  {
    slug: 'aws-d1-1',
    code: 'AWS D1.1',
    title: 'Structural Welding Code - Steel',
    organization: 'AWS (American Welding Society)',
    description: 'Comprehensive welding standard for structural steel covering welder qualification, welding procedures, inspection, and acceptance criteria. AWS D1.1 is the primary standard for structural welding in the United States. Compliance is required for building and bridge construction. Welder and inspector certifications per AWS D1.1 are industry credentials.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Liquid Penetrant Testing', 'Visual Testing'],
    industries: ['Construction', 'Bridge', 'Manufacturing', 'Power Generation'],
    country: 'USA',
  },
  {
    slug: 'aws-d1-2',
    code: 'AWS D1.2',
    title: 'Structural Welding Code - Aluminum',
    organization: 'AWS',
    description: 'Welding code for structural aluminum covering procedures, qualification, and inspection. AWS D1.2 addresses specific characteristics of aluminum welding and inspection requirements.',
    methods: ['Ultrasonic Testing', 'Liquid Penetrant Testing', 'Visual Testing'],
    industries: ['Aerospace', 'Marine', 'Construction', 'Manufacturing'],
    country: 'USA',
  },
  {
    slug: 'aws-d1-5',
    code: 'AWS D1.5',
    title: 'Bridge Welding Code',
    organization: 'AWS',
    description: 'Specialized welding code for bridge construction covering higher strength steels and fatigue-critical applications. AWS D1.5 specifies stricter inspection requirements than AWS D1.1 for high-stress bridge members.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Visual Testing'],
    industries: ['Bridge Construction', 'Infrastructure'],
    country: 'USA',
  },

  // ISO Standards
  {
    slug: 'iso-9712',
    code: 'ISO 9712',
    title: 'Non-Destructive Testing - Qualification and Certification of NDT Personnel',
    organization: 'ISO (International Organization for Standardization)',
    description: 'International standard for qualification and certification of NDT personnel at Level 1, 2, and 3 in all NDT methods. ISO 9712 defines training hours, examination requirements, and experience criteria. ISO 9712 certification is recognized globally and required by many employers. It is the primary standard for NDT personnel certification internationally.',
    methods: ['All NDT Methods'],
    industries: ['All Industries'],
    country: 'International',
  },
  {
    slug: 'iso-3452',
    code: 'ISO 3452',
    title: 'Non-Destructive Testing - Liquid Penetrant Testing',
    organization: 'ISO',
    description: 'International standard for liquid penetrant testing covering all aspects of PT inspection. ISO 3452 provides detailed procedures for surface preparation, penetrant application, removal, development, and evaluation. It is widely accepted as the international standard for PT methods.',
    methods: ['Liquid Penetrant Testing'],
    industries: ['All Industries'],
    country: 'International',
  },
  {
    slug: 'iso-9934',
    code: 'ISO 9934',
    title: 'Non-Destructive Testing - Magnetic Particle Testing',
    organization: 'ISO',
    description: 'International standard for magnetic particle testing covering procedures, equipment, materials, and acceptance criteria. ISO 9934 is the international equivalent of ASTM E1444 and is widely used globally.',
    methods: ['Magnetic Particle Testing'],
    industries: ['All Industries'],
    country: 'International',
  },
  {
    slug: 'iso-16810',
    code: 'ISO 16810',
    title: 'Non-Destructive Testing - Ultrasonic Testing',
    organization: 'ISO',
    description: 'International standard for ultrasonic testing covering all UT methods and applications. ISO 16810 is the comprehensive international standard for ultrasonic NDT procedures, equipment, and acceptance criteria.',
    methods: ['Ultrasonic Testing'],
    industries: ['All Industries'],
    country: 'International',
  },
  {
    slug: 'iso-17636',
    code: 'ISO 17636',
    title: 'Non-Destructive Testing - Radiography of Welds',
    organization: 'ISO',
    description: 'International standard for radiographic testing of welds covering procedures, equipment, and acceptance criteria. ISO 17636 is the international standard for weld radiography.',
    methods: ['Radiographic Testing'],
    industries: ['Construction', 'Manufacturing', 'Oil & Gas'],
    country: 'International',
  },
  {
    slug: 'iso-17637',
    code: 'ISO 17637',
    title: 'Non-Destructive Testing - Visual Testing',
    organization: 'ISO',
    description: 'International standard for visual testing methods and procedures. ISO 17637 covers direct visual inspection, optical magnification, and remote visual techniques.',
    methods: ['Visual Testing'],
    industries: ['All Industries'],
    country: 'International',
  },
  {
    slug: 'iso-17638',
    code: 'ISO 17638',
    title: 'Non-Destructive Testing - Weld Inspection Using Eddy Current Testing',
    organization: 'ISO',
    description: 'International standard for eddy current testing of welds covering equipment, procedures, and acceptance criteria for detecting defects in welds.',
    methods: ['Eddy Current Testing'],
    industries: ['Manufacturing', 'Aerospace', 'Oil & Gas'],
    country: 'International',
  },
  {
    slug: 'iso-15548',
    code: 'ISO 15548',
    title: 'Non-Destructive Testing - Eddy Current Testing',
    organization: 'ISO',
    description: 'International standard for eddy current testing covering general principles, equipment, calibration, and acceptance criteria. ISO 15548 is the comprehensive international ET standard.',
    methods: ['Eddy Current Testing'],
    industries: ['All Industries'],
    country: 'International',
  },
  {
    slug: 'iso-11699',
    code: 'ISO 11699',
    title: 'Radiography - Image Quality Indicators',
    organization: 'ISO',
    description: 'International standard for radiographic image quality indicators (penetrameters) defining specifications for wire and hole-type IQIs. ISO 11699 ensures consistent radiographic sensitivity verification globally.',
    methods: ['Radiographic Testing'],
    industries: ['All Industries'],
    country: 'International',
  },
  {
    slug: 'iso-13588',
    code: 'ISO 13588',
    title: 'Non-Destructive Testing - Ultrasonic Testing - Phased Array Testing',
    organization: 'ISO',
    description: 'International standard for phased array ultrasonic testing covering equipment, procedures, and acceptance criteria. ISO 13588 standardizes advanced PAUT methods globally.',
    methods: ['Phased Array Ultrasonic Testing'],
    industries: ['Oil & Gas', 'Power Generation', 'Aerospace'],
    country: 'International',
  },
  {
    slug: 'iso-10863',
    code: 'ISO 10863',
    title: 'Non-Destructive Testing - Ultrasonic Testing - Time-of-Flight Diffraction',
    organization: 'ISO',
    description: 'International standard for TOFD ultrasonic testing covering equipment, procedures, and acceptance criteria. ISO 10863 is the international standard for TOFD methods.',
    methods: ['Time-of-Flight Diffraction'],
    industries: ['Oil & Gas', 'Power Generation', 'Pipeline'],
    country: 'International',
  },
  {
    slug: 'iso-18211',
    code: 'ISO 18211',
    title: 'Non-Destructive Testing - Ultrasonic Testing - Guided Wave Testing',
    organization: 'ISO',
    description: 'International standard for guided wave testing of pipes covering equipment, procedures, and interpretation. ISO 18211 standardizes GWT methods for pipeline screening.',
    methods: ['Guided Wave Testing'],
    industries: ['Oil & Gas', 'Pipeline', 'Power Generation'],
    country: 'International',
  },
  {
    slug: 'iso-19285',
    code: 'ISO 19285',
    title: 'Non-Destructive Testing - Characterization and Sizing of Defects',
    organization: 'ISO',
    description: 'International standard for defect characterization and sizing using various NDT methods. ISO 19285 provides standardized approaches for measuring and evaluating detected indications.',
    methods: ['All NDT Methods'],
    industries: ['All Industries'],
    country: 'International',
  },

  // European Standards (EN/EN ISO)
  {
    slug: 'en-12668',
    code: 'EN 12668',
    title: 'Non-Destructive Testing - Ultrasonic Testing - Specification for Calibration',
    organization: 'CEN (European Committee for Standardization)',
    description: 'European standard for ultrasonic testing equipment calibration and verification. EN 12668 is widely used in Europe and aligns with ISO standards.',
    methods: ['Ultrasonic Testing'],
    industries: ['All Industries'],
    country: 'Europe',
  },
  {
    slug: 'en-13018',
    code: 'EN 13018',
    title: 'Non-Destructive Testing - Visual Testing',
    organization: 'CEN',
    description: 'European standard for visual inspection methods and procedures, equivalent to ISO 17637.',
    methods: ['Visual Testing'],
    industries: ['All Industries'],
    country: 'Europe',
  },
  {
    slug: 'en-13068',
    code: 'EN 13068',
    title: 'Non-Destructive Testing - Radiography of Welds',
    organization: 'CEN',
    description: 'European standard for weld radiography, equivalent to ISO 17636.',
    methods: ['Radiographic Testing'],
    industries: ['Construction', 'Manufacturing', 'Oil & Gas'],
    country: 'Europe',
  },

  // DNV Standards
  {
    slug: 'dnvgl-st-f101',
    code: 'DNVGL-ST-F101',
    title: 'Submarine Pipeline Systems',
    organization: 'DNV GL (Det Norske Veritas)',
    description: 'Standard for submarine pipeline design, fabrication, and inspection including comprehensive NDT requirements. DNVGL-ST-F101 is the leading standard for subsea pipelines. It specifies PAUT and TOFD inspection methods for critical welds.',
    methods: ['Phased Array Ultrasonic Testing', 'Time-of-Flight Diffraction', 'Radiographic Testing'],
    industries: ['Oil & Gas', 'Subsea', 'Marine & Offshore'],
    country: 'International',
  },
  {
    slug: 'dnv-rp-g103',
    code: 'DNV-RP-G103',
    title: 'Recommended Practice for Guided Wave Inspections',
    organization: 'DNV GL',
    description: 'Recommended practice for guided wave ultrasonic testing of pipelines covering equipment, procedures, and data interpretation. DNV-RP-G103 standardizes GWT applications for pipeline inspection.',
    methods: ['Guided Wave Testing'],
    industries: ['Oil & Gas', 'Pipeline'],
    country: 'International',
  },
  {
    slug: 'dnvgl-cp-0376',
    code: 'DNVGL-CP-0376',
    title: 'Type Approval for Robotic Inspection Systems',
    organization: 'DNV GL',
    description: 'Standard for robotic and automated inspection systems used in pipeline and structure inspection. DNVGL-CP-0376 ensures quality and reliability of automated NDT systems.',
    methods: ['All NDT Methods'],
    industries: ['Oil & Gas', 'Pipeline', 'Subsea'],
    country: 'International',
  },

  // NACE Standards
  {
    slug: 'nace-mrt-01-72',
    code: 'NACE MR-01-75',
    title: 'Material Requirements for Sulfide Stress Corrosion Cracking',
    organization: 'NACE International',
    description: 'Standard for material selection in sour service environments. While primarily a materials standard, it impacts NDT requirements for equipment and inspection planning in hydrogen sulfide environments.',
    methods: ['All NDT Methods'],
    industries: ['Oil & Gas', 'Pipeline', 'Petrochemical'],
    country: 'International',
  },
  {
    slug: 'nace-sp0170',
    code: 'NACE SP0170',
    title: 'Protection of Austenitic Stainless Steel from Pitting and Crevice Corrosion',
    organization: 'NACE International',
    description: 'Standard for corrosion protection of stainless steels impacting material selection and inspection requirements.',
    methods: ['Visual Testing', 'Ultrasonic Testing'],
    industries: ['Oil & Gas', 'Petrochemical', 'Power Generation'],
    country: 'International',
  },

  // ASNT Standards
  {
    slug: 'asnt-cp-189',
    code: 'ASNT-CP-189',
    title: 'ASNT Standard for Qualification and Certification',
    organization: 'ASNT (American Society for Nondestructive Testing)',
    description: 'Standard for NDT personnel qualification and certification in the United States. ASNT-CP-189 defines training, experience, and examination requirements for Level 1, 2, and 3 certifications.',
    methods: ['All NDT Methods'],
    industries: ['All Industries'],
    country: 'USA',
  },

  // Aerospace Standards
  {
    slug: 'as5044',
    code: 'AS 5044',
    title: 'Aerospace Materials - Ultrasonic Testing',
    organization: 'SAE International',
    description: 'Standard for ultrasonic testing of aerospace materials and components. AS 5044 specifies requirements for equipment, procedures, and acceptance criteria in aerospace applications.',
    methods: ['Ultrasonic Testing'],
    industries: ['Aerospace', 'Defense'],
    country: 'USA',
  },
  {
    slug: 'ams-2640',
    code: 'AMS 2640',
    title: 'Inspection, Fluorescent Liquid Penetrant',
    organization: 'SAE International',
    description: 'Aerospace standard for fluorescent liquid penetrant testing covering procedures, equipment, and acceptance criteria for aerospace components.',
    methods: ['Liquid Penetrant Testing'],
    industries: ['Aerospace', 'Defense', 'Manufacturing'],
    country: 'USA',
  },
  {
    slug: 'ams-2644',
    code: 'AMS 2644',
    title: 'Inspection, Liquid Penetrant',
    organization: 'SAE International',
    description: 'Aerospace standard for liquid penetrant testing methods and procedures for aerospace materials and components.',
    methods: ['Liquid Penetrant Testing'],
    industries: ['Aerospace', 'Defense'],
    country: 'USA',
  },

  // Marine and Offshore Standards
  {
    slug: 'abs-rules',
    code: 'ABS Rules',
    title: 'American Bureau of Shipping Rules for Ships',
    organization: 'ABS (American Bureau of Shipping)',
    description: 'Rules for marine vessel construction and inspection including comprehensive NDT requirements for ships and offshore structures. ABS Rules specify inspection methods and acceptance criteria.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing', 'Visual Testing'],
    industries: ['Marine', 'Offshore', 'Shipping'],
    country: 'International',
  },
  {
    slug: 'rina-rules',
    code: 'RINA Rules',
    title: 'Registro Italiano Navale Rules',
    organization: 'RINA (Registro Italiano Navale)',
    description: 'Italian classification society rules for marine vessels covering design, fabrication, and inspection requirements including NDT specifications.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Magnetic Particle Testing'],
    industries: ['Marine', 'Offshore', 'Shipping'],
    country: 'International',
  },
  {
    slug: 'iacs-unified-rules',
    code: 'IACS Unified Rules',
    title: 'International Association of Classification Societies Rules',
    organization: 'IACS',
    description: 'Harmonized rules for marine vessel classification covering NDT requirements. IACS unified approach ensures consistent standards across multiple classification societies.',
    methods: ['All NDT Methods'],
    industries: ['Marine', 'Offshore', 'Shipping'],
    country: 'International',
  },

  // Power Generation Standards
  {
    slug: 'asme-pcc-2',
    code: 'ASME PCC-2',
    title: 'Repair of Pressure Equipment and Piping',
    organization: 'ASME',
    description: 'Code for repair of pressure vessels and piping specifying inspection and NDT requirements. ASME PCC-2 ensures repairs meet original code requirements.',
    methods: ['All NDT Methods'],
    industries: ['Power Generation', 'Oil & Gas', 'Manufacturing'],
    country: 'USA',
  },
  {
    slug: 'asme-pcc-3',
    code: 'ASME PCC-3',
    title: 'Welding Inspection and Nondestructive Examination',
    organization: 'ASME',
    description: 'Guidance on welding inspection and NDT for power generation applications. ASME PCC-3 complements Section V for power plant construction.',
    methods: ['All NDT Methods'],
    industries: ['Power Generation'],
    country: 'USA',
  },

  // Japanese Standards
  {
    slug: 'jis-z2345',
    code: 'JIS Z 2345',
    title: 'Ultrasonic Testing Equipment',
    organization: 'JIS (Japanese Industrial Standards)',
    description: 'Japanese standard for ultrasonic testing equipment specifications and requirements.',
    methods: ['Ultrasonic Testing'],
    industries: ['All Industries'],
    country: 'Japan',
  },
  {
    slug: 'jis-z3104',
    code: 'JIS Z 3104',
    title: 'Radiographic Testing of Welds',
    organization: 'JIS',
    description: 'Japanese standard for radiographic weld inspection covering procedures and acceptance criteria.',
    methods: ['Radiographic Testing'],
    industries: ['Construction', 'Manufacturing', 'Oil & Gas'],
    country: 'Japan',
  },

  // Chinese Standards
  {
    slug: 'gb-t-8162',
    code: 'GB/T 8162',
    title: 'Seamless Steel Tubes',
    organization: 'GB (Guobiao - Chinese National Standards)',
    description: 'Chinese standard for seamless steel tubes including NDT inspection requirements.',
    methods: ['Ultrasonic Testing', 'Eddy Current Testing'],
    industries: ['Oil & Gas', 'Pipeline', 'Manufacturing'],
    country: 'China',
  },

  // German Standards
  {
    slug: 'din-en-1711',
    code: 'DIN EN 1711',
    title: 'Non-Destructive Testing - Eddy Current',
    organization: 'DIN (Deutsches Institut für Normung)',
    description: 'German implementation of ISO 15548 for eddy current testing.',
    methods: ['Eddy Current Testing'],
    industries: ['All Industries'],
    country: 'Germany',
  },

  // British Standards
  {
    slug: 'bs-en-1435',
    code: 'BS EN 1435',
    title: 'Non-Destructive Testing of Welds - Radiography',
    organization: 'BSI (British Standards Institution)',
    description: 'British standard for weld radiography equivalent to ISO 17636.',
    methods: ['Radiographic Testing'],
    industries: ['Construction', 'Manufacturing', 'Oil & Gas'],
    country: 'United Kingdom',
  },
  {
    slug: 'bs-9690',
    code: 'BS 9690',
    title: 'Guidance on the Assessment of Life Remaining in Thick-Walled Onshore Pipeline Systems',
    organization: 'BSI',
    description: 'British standard for pipeline integrity assessment including NDT requirements.',
    methods: ['Ultrasonic Testing', 'Guided Wave Testing'],
    industries: ['Pipeline', 'Oil & Gas'],
    country: 'United Kingdom',
  },

  // Additional Industry Specific Standards
  {
    slug: 'asme-b31-3',
    code: 'ASME B31.3',
    title: 'Process Piping Code',
    organization: 'ASME',
    description: 'Code for process piping in chemical, petroleum, and power generation industries. ASME B31.3 specifies inspection and NDT requirements for process piping systems.',
    methods: ['Ultrasonic Testing', 'Radiographic Testing', 'Visual Testing'],
    industries: ['Oil & Gas', 'Petrochemical', 'Power Generation'],
    country: 'USA',
  },
  {
    slug: 'ieee-45',
    code: 'IEEE 45',
    title: 'Standard for Shipboard Electrical Power Systems',
    organization: 'IEEE',
    description: 'Standard for marine electrical systems including inspection requirements.',
    methods: ['Visual Testing', 'Eddy Current Testing'],
    industries: ['Marine', 'Offshore'],
    country: 'International',
  },
  {
    slug: 'en-10228',
    code: 'EN 10228',
    title: 'Ultrasonic Testing of Forgings',
    organization: 'CEN',
    description: 'European standard for ultrasonic testing of forged components.',
    methods: ['Ultrasonic Testing'],
    industries: ['Manufacturing', 'Aerospace', 'Power Generation'],
    country: 'Europe',
  },
  {
    slug: 'iso-5817',
    code: 'ISO 5817',
    title: 'Welding - Fusion-welded Joints in Steel - Defects Classification',
    organization: 'ISO',
    description: 'International standard for classification of weld defects and acceptance levels.',
    methods: ['All NDT Methods'],
    industries: ['All Industries'],
    country: 'International',
  },
];

export function getStandardBySlug(slug: string): NDTStandard | undefined {
  return ndtStandards.find(std => std.slug === slug);
}

export function getAllStandardSlugs(): string[] {
  return ndtStandards.map(std => std.slug);
}

export function getStandardsByOrganization(organization: string): NDTStandard[] {
  return ndtStandards.filter(std => std.organization === organization);
}

export function getStandardsByMethod(method: string): NDTStandard[] {
  return ndtStandards.filter(std => std.methods.includes(method));
}

export function getStandardsByIndustry(industry: string): NDTStandard[] {
  return ndtStandards.filter(std => std.industries.includes(industry));
}
