// ============================================================
// NDT Connect - Comprehensive Glossary Data
// 200+ NDT Terminology Terms with Definitions
// ============================================================

export interface GlossaryTerm {
  slug: string;
  term: string;
  definition: string;
  relatedTerms: string[];
  category: 'methods' | 'equipment' | 'defects' | 'standards' | 'materials' | 'physics' | 'certifications' | 'safety';
}

export const glossaryTerms: GlossaryTerm[] = [
  // Methods
  {
    slug: 'acoustic-impedance',
    term: 'Acoustic Impedance',
    definition: 'A material property representing the resistance to ultrasonic wave motion, calculated as the product of material density and sound velocity. It determines the amount of acoustic energy reflected at material boundaries. Differences in acoustic impedance between materials cause partial reflection of ultrasonic waves, which is fundamental to ultrasonic testing. High impedance mismatches are why couplants are necessary for efficient energy transfer into materials.',
    relatedTerms: ['sound-velocity', 'couplant', 'reflection', 'transmission'],
    category: 'physics',
  },
  {
    slug: 'a-scan',
    term: 'A-Scan (Amplitude-Scan)',
    definition: 'A one-dimensional ultrasonic display showing signal amplitude (vertical axis) versus time (horizontal axis). In A-scan presentation, the transmitted pulse appears as an initial spike, internal reflections appear as smaller spikes, and the back-wall echo appears at the far right. The technician measures the distance from the initial pulse to internal reflections to determine flaw depth. A-scan is the most basic UT presentation mode and requires significant operator experience to interpret correctly.',
    relatedTerms: ['b-scan', 'c-scan', 'ultrasonic-testing', 'back-wall-echo'],
    category: 'methods',
  },
  {
    slug: 'b-scan',
    term: 'B-Scan (Brightness-Scan)',
    definition: 'A two-dimensional cross-sectional display of ultrasonic data showing depth (vertical axis) and distance along the scanning path (horizontal axis), with signal amplitude represented by brightness. B-scans provide visual representation of internal material structure and defect locations within a vertical plane. This presentation mode is more intuitive than A-scans and helps visualize the exact position and extent of discontinuities within the material thickness.',
    relatedTerms: ['a-scan', 'c-scan', 'cross-section', 'phased-array-ut'],
    category: 'methods',
  },
  {
    slug: 'c-scan',
    term: 'C-Scan (Planar-Scan)',
    definition: 'A two-dimensional top-down view of scanned area showing flaw location and size in a plan view (X-Y coordinates), with signal amplitude represented by color intensity. C-scans create a map of reflectors within the material from a single depth level, making it excellent for visualizing the plan-view extent of defects. This presentation is particularly useful for detecting delaminations in composites and mapping corrosion patterns in flat plate structures.',
    relatedTerms: ['a-scan', 'b-scan', 'phased-array-ut', 'delamination'],
    category: 'methods',
  },
  {
    slug: 'amplitude',
    term: 'Amplitude',
    definition: 'The height or intensity of an ultrasonic signal, measured in decibels or percentage of full screen height. Larger discontinuities typically produce larger amplitude reflections. Amplitude analysis is critical for defect characterization, as it correlates with flaw size and severity. Reference standards with calibrated defects establish baseline amplitude signatures for comparison during inspection. Signal amplitude decreases with material attenuation and distance traveled.',
    relatedTerms: ['decibel', 'attenuation', 'gain', 'reference-standard'],
    category: 'physics',
  },
  {
    slug: 'attenuation',
    term: 'Attenuation',
    definition: 'The progressive loss of ultrasonic wave amplitude as it travels through material, caused by absorption and scattering. Materials with higher grain sizes and damping coefficients exhibit greater attenuation. Attenuation increases with frequency, which is why lower frequencies are used for thick sections and coarse-grained materials. Understanding material attenuation is essential for selecting appropriate test frequencies and gaining during ultrasonic inspections.',
    relatedTerms: ['frequency', 'absorption', 'scatter', 'gain', 'penetration'],
    category: 'physics',
  },
  {
    slug: 'back-wall-echo',
    term: 'Back-Wall Echo',
    definition: 'The ultrasonic echo reflected from the far boundary or back surface of a test piece. In thickness measurement, the delay time of the back-wall echo is used to calculate material thickness. The amplitude of the back-wall echo indicates material continuity and attenuation. When inspecting for internal flaws, the back-wall echo must be visible as a baseline reference. Loss of back-wall echo indicates the presence of a flaw between the transducer and the back surface.',
    relatedTerms: ['a-scan', 'ultrasonic-testing', 'echo', 'reflection'],
    category: 'methods',
  },
  {
    slug: 'beam-spread',
    term: 'Beam Spread (Beam Divergence)',
    definition: 'The angular dispersion of an ultrasonic beam as it travels away from the transducer. Near-field ultrasonic waves travel in a relatively focused beam, but in the far-field, the beam spreads. Beam spread is related to the frequency and transducer diameter. Wider beam spread can cause defects to be detected from the sides of the beam path. Understanding beam spread geometry is important for flaw location accuracy and avoiding false indications.',
    relatedTerms: ['near-field', 'far-field', 'frequency', 'transducer'],
    category: 'physics',
  },
  {
    slug: 'calibration-block',
    term: 'Calibration Block (Reference Standard)',
    definition: 'A specially fabricated test block containing calibrated defects (notches, drilled holes, side-drilled holes) used to calibrate ultrasonic equipment and verify system performance before inspections. Standard calibration blocks like IIW (flat-bottomed hole, side-drilled hole) enable equipment setup and gain establishment. Use of proper calibration blocks ensures consistent, repeatable measurements and reliable flaw detection across multiple inspections and operators.',
    relatedTerms: ['reference-standard', 'side-drilled-hole', 'sensitivity', 'penetrameter'],
    category: 'equipment',
  },
  {
    slug: 'couplant',
    term: 'Couplant',
    definition: 'A substance applied between the transducer and test surface to ensure efficient transmission of ultrasonic waves into the material. Common couplants include water, glycerin, honey, and commercial ultrasonic gels. Couplants eliminate air gaps that would reflect ultrasonic energy back to the transducer. The acoustic impedance of couplants is matched closely to both transducer and material surfaces. Proper couplant application is essential for obtaining reliable ultrasonic test results.',
    relatedTerms: ['acoustic-impedance', 'transmission', 'transducer', 'ultrasonic-testing'],
    category: 'equipment',
  },
  {
    slug: 'crack',
    term: 'Crack',
    definition: 'A linear or branching discontinuity in material caused by stress concentration, thermal cycling, hydrogen embrittlement, or fatigue loading. Cracks are one of the most critical defect types as they can propagate rapidly under loading. Crack detection is a primary focus of NDT inspections, particularly in welds and high-stress components. Cracks must be sized and characterized to determine their fitness-for-service and repair requirements.',
    relatedTerms: ['discontinuity', 'fatigue-crack', 'stress-concentration', 'indication'],
    category: 'defects',
  },
  {
    slug: 'dead-zone',
    term: 'Dead Zone',
    definition: 'A region immediately beneath an ultrasonic transducer where defects cannot be reliably detected due to interference from the initial pulse and near-field effects. The dead zone depth depends on transducer frequency and material velocity. For surface defect detection, special high-frequency transducers with shorter wavelengths reduce dead zone size. Understanding dead zone limitations is critical for establishing inspection specifications for surface-breaking defects and near-surface flaws.',
    relatedTerms: ['near-field', 'surface-breaking', 'frequency', 'resolution'],
    category: 'methods',
  },
  {
    slug: 'decibel',
    term: 'Decibel (dB)',
    definition: 'A logarithmic unit for expressing signal amplitude ratios commonly used in ultrasonic testing to measure gain settings. A 20 dB increase represents a 10-fold increase in voltage amplitude. Ultrasonic instruments typically display gain in decibels from 0 to 100 dB or higher. Decibel notation allows convenient expression of wide amplitude ranges and makes it easier to set consistent sensitivity levels across different test objects and operators.',
    relatedTerms: ['amplitude', 'gain', 'logarithm', 'sensitivity'],
    category: 'physics',
  },
  {
    slug: 'delamination',
    term: 'Delamination',
    definition: 'The separation or splitting of layers in composite materials, laminated structures, or coatings. Delaminations reduce load-bearing capacity and structural integrity, particularly in composites and adhesively-bonded structures. Ultrasonic C-scans are excellent for detecting and mapping delaminations due to the strong reflection from the separated layers. Delaminations in critical aerospace composites must be detected early as they can propagate rapidly under cyclic loading.',
    relatedTerms: ['composite', 'lamination', 'separation', 'disbond'],
    category: 'defects',
  },
  {
    slug: 'dead-zone',
    term: 'Dead Zone (Surface Defect Considerations)',
    definition: 'The region immediately beneath an ultrasonic transducer where defects cannot be reliably detected. The dead zone is caused by the transmitted pulse duration and near-field effects. Modern high-frequency, short pulse transducers minimize dead zone depth, critical for detecting surface-breaking defects. For thickness measurements of very thin materials, special techniques and transducers are required to work within dead zone limitations.',
    relatedTerms: ['near-field', 'transducer', 'pulse', 'resolution'],
    category: 'methods',
  },
  {
    slug: 'defect',
    term: 'Defect',
    definition: 'Any discontinuity or imperfection in material that reduces its service capability or performance. Defects include cracks, porosity, inclusions, lack of fusion, and delaminations. Not all discontinuities are rejectable defects; acceptance criteria in standards determine which indications constitute unacceptable defects. Characterization and sizing of defects through NDT is essential for fitness-for-service decisions and repair planning.',
    relatedTerms: ['discontinuity', 'indication', 'flaw', 'rejectable-indication'],
    category: 'defects',
  },
  {
    slug: 'dye-penetrant',
    term: 'Dye Penetrant Testing',
    definition: 'Liquid penetrant testing method using colored or fluorescent dyes to detect surface-breaking discontinuities. The penetrant is applied to the test surface, allowed to dwell and seep into defects via capillary action, then excess is removed. A developer powder is applied which draws trapped dye back to the surface, creating visible indications of defects. Dye penetrant is cost-effective and suitable for virtually any non-porous material, making it one of the most widely used NDT methods.',
    relatedTerms: ['penetrant-testing', 'fluorescent', 'surface-breaking', 'capillary-action'],
    category: 'methods',
  },
  {
    slug: 'echo',
    term: 'Echo (Ultrasonic)',
    definition: 'The reflection of an ultrasonic wave back to the transducer after striking a boundary or internal discontinuity. Echoes appear as signals (spikes or peaks) in ultrasonic displays. The time delay of an echo is used to calculate distance (depth) to the reflecting surface using the formula: distance = (velocity × time) / 2. Echo amplitude indicates the size and reflectivity of the discontinuity. Proper interpretation of echoes is fundamental to ultrasonic flaw detection.',
    relatedTerms: ['reflection', 'a-scan', 'ultrasonic-testing', 'time-of-flight'],
    category: 'physics',
  },
  {
    slug: 'eddy-current',
    term: 'Eddy Current',
    definition: 'Circular electric currents induced in a conductive material by an alternating magnetic field. These eddy currents generate their own magnetic field, which is detected by eddy current testing equipment. Defects, cracks, conductivity changes, and permeability variations alter eddy current flow patterns. Eddy current testing is one of the fastest NDT methods and requires no couplant, making it ideal for rapid inspection of tubes, fasteners, and thin-walled components.',
    relatedTerms: ['eddy-current-testing', 'magnetic-field', 'conductivity', 'electromagnetic'],
    category: 'physics',
  },
  {
    slug: 'flaw',
    term: 'Flaw',
    definition: 'A discontinuity or defect in material that may affect its service capability. The term "flaw" is sometimes used interchangeably with "defect" and "discontinuity," though flaws specifically refer to undesirable discontinuities that exceed acceptance criteria. In NDT, the goal is to detect all flaws of sufficient size and type to warrant repair or rejection. Flaw characterization and sizing are critical for fitness-for-service assessment.',
    relatedTerms: ['defect', 'discontinuity', 'indication', 'rejectable-indication'],
    category: 'defects',
  },
  {
    slug: 'frequency',
    term: 'Frequency (Ultrasonic)',
    definition: 'The number of ultrasonic wave cycles per second, measured in megahertz (MHz). Higher frequencies (5-25 MHz) provide better resolution and sensitivity to small flaws but have limited penetration due to attenuation. Lower frequencies (0.5-2 MHz) penetrate thicker materials and coarse-grained materials better. Frequency selection is a critical inspection parameter determined by material thickness, grain size, and required resolution. The relationship between frequency and wavelength governs spatial resolution.',
    relatedTerms: ['wavelength', 'attenuation', 'resolution', 'penetration'],
    category: 'physics',
  },
  {
    slug: 'gain',
    term: 'Gain (Amplification)',
    definition: 'The electronic amplification applied to ultrasonic signals to increase their amplitude for better visibility on the display. Gain is typically expressed in decibels and adjusted to bring the back-wall echo to a reference level (80% or 6dB below full screen height). Proper gain setting is critical to avoid missing small flaws (insufficient gain) or false indications (excessive gain). Different materials and thicknesses require different gain settings for consistent inspection results.',
    relatedTerms: ['decibel', 'amplitude', 'sensitivity', 'reference-standard'],
    category: 'methods',
  },
  {
    slug: 'half-value-layer',
    term: 'Half-Value Layer (HVL)',
    definition: 'The thickness of a material through which radiation intensity is reduced to half of its original value. Used in radiography to characterize X-ray beam quality and filter effects. HVL is measured in millimeters of a reference material (aluminum for low-energy X-rays). It determines the penetrating power of the X-ray beam and affects the quality of radiographic images and radiation safety requirements.',
    relatedTerms: ['radiographic-testing', 'x-ray-tube', 'filtration', 'beam-quality'],
    category: 'equipment',
  },
  {
    slug: 'heat-affected-zone',
    term: 'Heat-Affected Zone (HAZ)',
    definition: 'The region of base metal adjacent to a weld bead that has been heated to a temperature high enough to change its microstructure and properties but not melted. The HAZ is susceptible to hardening, brittleness, and cracking, particularly in carbon steels. NDT inspection of the HAZ is critical to detect heat-affected zone cracks and assess weld quality. The HAZ width varies with material composition, heat input, and cooling rate.',
    relatedTerms: ['weld', 'weld-defect', 'crack', 'metallurgical'],
    category: 'materials',
  },
  {
    slug: 'inclusion',
    term: 'Inclusion',
    definition: 'A foreign material (oxide, slag, non-metallic particles) trapped within a weld deposit or casting. Inclusions are undesirable defects that weaken material and can initiate cracks. Slag inclusions from the welding or casting process are the most common types. Inclusions are easily detected by radiography and ultrasonic testing. The size, location, and quantity of inclusions determine rejectable status according to inspection standards.',
    relatedTerms: ['slag-inclusion', 'defect', 'weld-defect', 'porosity'],
    category: 'defects',
  },
  {
    slug: 'indication',
    term: 'Indication',
    definition: 'A signal or response detected by NDT equipment that may or may not represent an actual defect. Not all indications are defects; some are from surface conditions, geometry, or material property variations. Indications must be evaluated to determine if they meet acceptance criteria and constitute rejectable flaws. Proper characterization distinguishes between relevant indications (actual defects) and irrelevant indications (false signals or acceptable conditions).',
    relatedTerms: ['defect', 'flaw', 'relevant-indication', 'rejectable-indication'],
    category: 'methods',
  },
  {
    slug: 'interpretation',
    term: 'Interpretation',
    definition: 'The analysis and evaluation of NDT data to determine if indications represent acceptable or unacceptable conditions. Interpretation requires knowledge of material properties, applicable standards, acceptance criteria, and defect characteristics. Experienced NDT technicians compare indications to reference standards and apply engineering judgment. Proper interpretation separates relevant flaws from irrelevant artifacts and supports fitness-for-service decisions.',
    relatedTerms: ['evaluation', 'acceptance-criteria', 'relevant-indication', 'indication'],
    category: 'methods',
  },
  {
    slug: 'iridium-192',
    term: 'Iridium-192',
    definition: 'A radioactive isotope commonly used as a radiation source in radiographic testing. Ir-192 has a half-life of 73.8 days and emits gamma rays suitable for radiography. It is preferred over cobalt-60 for thin-wall inspections and portable industrial radiography due to its higher density, allowing smaller source capsules. Ir-192 requires less shielding than Co-60 but more safety precautions than X-rays.',
    relatedTerms: ['radiographic-testing', 'cobalt-60', 'gamma-ray', 'isotope'],
    category: 'equipment',
  },
  {
    slug: 'isotropic',
    term: 'Isotropic',
    definition: 'Material property where physical properties are identical in all directions. Most cast and wrought metals exhibit isotropic behavior, allowing relatively simple ultrasonic inspection. In contrast, directionally solidified materials, forgings, and composites can be anisotropic with properties varying by direction. Understanding material isotropy is important for transducer selection and angle beam settings to ensure proper ultrasonic coverage.',
    relatedTerms: ['anisotropic', 'material-properties', 'grain-structure'],
    category: 'materials',
  },
  {
    slug: 'lamination',
    term: 'Lamination',
    definition: 'A discontinuity in rolled or forged material consisting of the separation of internal layers parallel to the surface. Laminations are typically caused by entrapment of non-metallic oxides or voids during rolling. They weaken material through-thickness strength and can trigger cracking under stress. Ultrasonic testing with proper technique is effective for detecting laminations, particularly in high-strength steel plates and forgings used in pressure vessels.',
    relatedTerms: ['delamination', 'segregation', 'rolling-defect', 'defect'],
    category: 'defects',
  },
  {
    slug: 'linear-indication',
    term: 'Linear Indication',
    definition: 'A defect or indication whose length is significantly greater than its width, such as a crack or lack of fusion in a weld. Linear indications are potentially more serious than rounded indications of equivalent area because stress concentrations are more severe. Linear indications in fatigue-critical applications require more stringent acceptance criteria. Proper measurement and characterization of linear indication length is essential for flaw evaluation.',
    relatedTerms: ['indication', 'planar-indication', 'crack', 'elongated'],
    category: 'defects',
  },
  {
    slug: 'magnetic-domain',
    term: 'Magnetic Domain',
    definition: 'A region in ferromagnetic material where magnetic moments align in the same direction, creating net magnetization. During magnetic particle testing, discontinuities disrupt magnetic flux and create magnetic domains that align perpendicular to the surface, attracting ferromagnetic particles. Understanding magnetic domains explains why magnetic particle testing is so effective at detecting surface and near-surface defects in iron and steel.',
    relatedTerms: ['magnetic-particle-testing', 'magnetization', 'ferromagnetic'],
    category: 'physics',
  },
  {
    slug: 'near-field',
    term: 'Near-Field (Fresnel Zone)',
    definition: 'The region immediately in front of an ultrasonic transducer where the sound beam is compressed and interference effects dominate. In the near-field, the beam does not diverge uniformly and sound pressure is non-uniform. The near-field length is calculated as: L = D²/(4λ) where D is transducer diameter and λ is wavelength. Operating within the near-field affects defect detection, so proper transducer selection and inspection geometry are critical.',
    relatedTerms: ['far-field', 'transducer', 'frequency', 'beam-divergence'],
    category: 'physics',
  },
  {
    slug: 'node',
    term: 'Node',
    definition: 'A point in a vibrating material where the amplitude of vibration is minimum or zero. In ultrasonic guided wave testing, nodes in torsional modes occur at the pipe surface, making torsional modes insensitive to external features. Understanding nodal patterns in guided waves is important for proper probe design and mode selection for inspection of insulated or complex geometry pipelines.',
    relatedTerms: ['guided-wave-testing', 'antinode', 'torsional-mode'],
    category: 'physics',
  },
  {
    slug: 'nominal-thickness',
    term: 'Nominal Thickness',
    definition: 'The specified or design thickness of a component before corrosion, erosion, or manufacturing tolerance is considered. Thickness measurements comparing actual thickness to nominal design thickness are used to assess remaining wall thickness and detect corrosion or erosion. Acceptance criteria for continued service are typically based on minimum allowable wall thickness, calculated from the nominal value minus corrosion allowance.',
    relatedTerms: ['thickness-measurement', 'corrosion-allowance', 'wall-thickness'],
    category: 'methods',
  },
  {
    slug: 'parallel-scan',
    term: 'Parallel Scan',
    definition: 'A scanning pattern in ultrasonic testing where the transducer moves parallel to a reference line (such as a weld centerline) while maintaining consistent coupling and transducer position. Parallel scanning is used for longitudinal weld inspection to detect toe cracks and detect lack-of-fusion. The technique provides good sensitivity to defects oriented perpendicular to the scan direction.',
    relatedTerms: ['scanning-sensitivity', 'scan-pattern', 'weld-inspection'],
    category: 'methods',
  },
  {
    slug: 'penetrameter',
    term: 'Penetrameter (IQI - Image Quality Indicator)',
    definition: 'A standardized test piece with calibrated holes or wires placed on radiographs to assess image quality and verify that the radiographic system can detect specified defects. IQIs ensure that radiographs meet sensitivity requirements. The most common penetrameters are wire-type (various wire diameters) and hole-type (drilled holes). Wire penetrameters are the international standard for assessing radiographic sensitivity in accordance with ISO 11699 and ASTM standards.',
    relatedTerms: ['radiographic-testing', 'image-quality', 'sensitivity', 'iqI'],
    category: 'equipment',
  },
  {
    slug: 'porosity',
    term: 'Porosity',
    definition: 'The presence of gas voids or cavities in a weld or casting, appearing as rounded discontinuities. Porosity is caused by gas entrapment during solidification, improper shielding gas coverage (in welds), or excessive moisture in coatings. Scattered porosity of small size may be acceptable, but large or clustered porosity weakens material. Porosity is readily detected by radiography and ultrasonic testing.',
    relatedTerms: ['void', 'cavity', 'gas-pocket', 'weld-defect'],
    category: 'defects',
  },
  {
    slug: 'probe',
    term: 'Probe (Search Unit)',
    definition: 'In ultrasonic testing, the probe contains the transducer, wedge, and damping materials. It converts electrical signals to ultrasonic waves and back. In eddy current testing, the probe (coil) generates the electromagnetic field. Probe design affects frequency response, beam characteristics, and defect detection capability. Proper probe selection and maintenance are essential for consistent, reliable NDT results.',
    relatedTerms: ['transducer', 'search-unit', 'wedge', 'coil'],
    category: 'equipment',
  },
  {
    slug: 'radiograph',
    term: 'Radiograph',
    definition: 'A permanent image produced by transmission of penetrating radiation through an object onto film or a digital detector. Radiographs reveal internal structure, defects, and density variations. They are considered a definitive record of the inspection condition and are often retained for the life of a structure. Radiograph quality and proper interpretation are critical for reliable weld inspection and defect detection.',
    relatedTerms: ['radiographic-testing', 'film', 'digital-radiography', 'image-quality'],
    category: 'methods',
  },
  {
    slug: 'reference-standard',
    term: 'Reference Standard',
    definition: 'A calibrated sample containing known defects used for establishing NDT system parameters, training, and comparison. Reference standards like IIW (International Institute of Welding) blocks contain drilled holes and side-drilled holes of known sizes. Using identical reference standards ensures consistent setup across multiple inspections and operators. Periodic verification against reference standards confirms equipment and operator capability.',
    relatedTerms: ['calibration-block', 'side-drilled-hole', 'sensitivity', 'equipment-verification'],
    category: 'equipment',
  },
  {
    slug: 'rejectable-indication',
    term: 'Rejectable Indication',
    definition: 'An indication (detected defect) that exceeds acceptance criteria and must be repaired or the component rejected. Whether an indication is rejectable depends on material type, component function, applicable standard, and acceptance criteria. Standards like ASME Section V, AWS D1.1, and API standards define acceptance limits for various types of indications. Properly characterized and sized indications enable correct rejection/acceptance decisions.',
    relatedTerms: ['indication', 'acceptance-criteria', 'defect', 'relevant-indication'],
    category: 'methods',
  },
  {
    slug: 'relevant-indication',
    term: 'Relevant Indication',
    definition: 'An indication detected by NDT that represents an actual defect in the material (as opposed to irrelevant indications from geometry, coatings, or instrument artifacts). Distinguishing relevant from irrelevant indications requires proper technique, reference standards, and operator experience. Standards define criteria for determining whether detected indications are relevant flaws requiring evaluation.',
    relatedTerms: ['indication', 'defect', 'irrelevant-indication', 'interpretation'],
    category: 'methods',
  },
  {
    slug: 'scanning-sensitivity',
    term: 'Scanning Sensitivity',
    definition: 'The ability of an NDT method and technique to detect defects of specified size during inspection. Scanning sensitivity depends on transducer selection, gain settings, scan speed, probe angle, and material properties. Standards define required sensitivity levels for different applications. Establishing and verifying proper scanning sensitivity through calibration procedures is fundamental to quality NDT.',
    relatedTerms: ['sensitivity', 'scanning-pattern', 'gain', 'reference-standard'],
    category: 'methods',
  },
  {
    slug: 'sensitivity',
    term: 'Sensitivity',
    definition: 'The ability of an NDT method to detect discontinuities of a specified minimum size under defined conditions. Higher sensitivity means smaller defects can be detected. Sensitivity is affected by material properties, transducer characteristics, equipment settings, and technique. Standards specify minimum sensitivity requirements for different applications. Establishing sensitivity through reference standards ensures consistency and reliability of inspections.',
    relatedTerms: ['scanning-sensitivity', 'resolution', 'reference-standard', 'gain'],
    category: 'methods',
  },
  {
    slug: 'slag-inclusion',
    term: 'Slag Inclusion',
    definition: 'Nonmetallic material (typically oxide-based) entrapped in a weld deposit or at the fusion boundary. Slag inclusions occur when the welder fails to properly remove slag from previous passes or uses improper welding parameters. They are readily detected by radiography and ultrasonic testing. Slag inclusions weaken welds and are generally unacceptable in critical applications. Proper welding technique and interpass slag removal are essential to prevent slag inclusions.',
    relatedTerms: ['inclusion', 'weld-defect', 'lack-of-fusion', 'penetration'],
    category: 'defects',
  },
  {
    slug: 'snells-law',
    term: "Snell's Law",
    definition: 'The fundamental physics law governing refraction of ultrasonic waves at material boundaries, stating that incident angle and refracted angle are related by the ratio of sound velocities. In angle-beam testing, Snell\'s law is used to calculate the correct transducer angle to achieve desired beam angles within the test material. Understanding refraction is essential for proper shear-wave and angle-beam ultrasonic inspections.',
    relatedTerms: ['refraction', 'angle-beam', 'velocity', 'transmission-angle'],
    category: 'physics',
  },
  {
    slug: 'sound-velocity',
    term: 'Sound Velocity',
    definition: 'The speed at which ultrasonic waves propagate through a material, varying with material type, density, and stiffness. Longitudinal wave velocities typically range from 2,000 to 7,000 m/s; shear waves travel at 40-60% of longitudinal velocity. Sound velocity is used to calculate distances from time-of-flight measurements. Different materials have different velocities, requiring velocity input for accurate thickness measurements and flaw depth calculations.',
    relatedTerms: ['longitudinal-wave', 'shear-wave', 'time-of-flight', 'acoustic-impedance'],
    category: 'physics',
  },
  {
    slug: 'transducer',
    term: 'Transducer',
    definition: 'A piezoelectric device that converts electrical energy into ultrasonic waves and vice versa. Transducers are the heart of ultrasonic equipment, with characteristics like frequency, element size, and damping affecting beam quality and sensitivity. Transducers are mounted in probes with backing and damping materials. Proper transducer selection based on material, geometry, and required sensitivity is critical for effective ultrasonic inspections.',
    relatedTerms: ['piezoelectric', 'probe', 'frequency', 'coupling'],
    category: 'equipment',
  },
  {
    slug: 'undercut',
    term: 'Undercut',
    definition: 'A groove or depression at the toe of a weld where the base metal has been melted away but not properly filled by weld metal. Undercut reduces cross-sectional area and creates stress concentration, making it a critical weld defect. It is readily detected by visual inspection and NDT methods. Acceptance criteria vary by application; critical applications typically reject any undercut, while less critical applications allow limited undercut.',
    relatedTerms: ['weld-defect', 'weld-toe', 'crack-initiation', 'visual-testing'],
    category: 'defects',
  },
  {
    slug: 'weld-profile',
    term: 'Weld Profile',
    definition: 'The external geometry of a weld including reinforcement height, width, and contour. Proper weld profile is essential for stress distribution and fatigue resistance. Excess reinforcement increases stiffness but is wasteful; insufficient reinforcement may be unacceptable. Visual inspection and measurement of weld profile is the first NDT step. Profile defects like undercut and irregular surface must be detected and evaluated per acceptance standards.',
    relatedTerms: ['weld', 'undercut', 'reinforcement', 'visual-testing'],
    category: 'defects',
  },
  {
    slug: 'x-ray-tube',
    term: 'X-Ray Tube',
    definition: 'An electronic device that generates X-rays by accelerating electrons from a heated cathode toward a metal anode target, where sudden deceleration produces X-ray radiation. X-ray tubes are central to industrial radiography equipment. Tube operating voltage (kV) determines X-ray penetrating power; higher voltage penetrates thicker materials but with reduced contrast. Different anode materials (tungsten, molybdenum) affect X-ray spectrum.',
    relatedTerms: ['radiographic-testing', 'x-ray', 'anode', 'cathode'],
    category: 'equipment',
  },
  {
    slug: 'yoke',
    term: 'Yoke (Magnetic Particle Testing)',
    definition: 'A portable electromagnet device used for magnetic particle testing, shaped like an inverted U. The yoke magnetizes the test area between its two poles. Yokes are convenient for field inspection as they are portable and require only 110V power. Yoke lift-off capability determines magnetization quality. Different yoke designs accommodate various component geometries and space constraints.',
    relatedTerms: ['magnetic-particle-testing', 'electromagnet', 'magnetization', 'portable'],
    category: 'equipment',
  },

  // Additional Essential Terms
  {
    slug: 'angle-beam-testing',
    term: 'Angle Beam Testing',
    definition: 'Ultrasonic testing technique using transducers mounted on wedges at specific angles (typically 45° or 60°) to generate shear waves that travel at angles through the material. Angle beams are essential for detecting defects perpendicular to surfaces and inspecting welds from one side. The angle is calculated using Snell\'s law to achieve the desired refracted angle. Proper angle selection and beam geometry verification are critical to inspection effectiveness.',
    relatedTerms: ['shear-wave', 'wedge', 'snells-law', 'weld-inspection'],
    category: 'methods',
  },
  {
    slug: 'compression-wave',
    term: 'Compression Wave (Longitudinal Wave)',
    definition: 'Ultrasonic wave where particle motion is parallel to the direction of wave propagation, also called longitudinal or P-waves. Compression waves travel at higher velocity than shear waves and are preferred for thickness measurement and detecting laminations. They are excellent for detecting defects perpendicular to the transducer surface. Compression waves are generated by straight-contact transducers.',
    relatedTerms: ['longitudinal-wave', 'shear-wave', 'transducer', 'propagation'],
    category: 'physics',
  },
  {
    slug: 'contact-testing',
    term: 'Contact Testing',
    definition: 'Ultrasonic testing method where the transducer is placed directly in contact with the test surface using a couplant. Contact testing is the most common ultrasonic technique and is simple to perform. It is suitable for flat and slightly curved surfaces. The transducer must maintain consistent pressure and coupling for accurate measurements. Contact testing cannot be used on very rough surfaces or through heavy corrosion.',
    relatedTerms: ['immersion-testing', 'couplant', 'transducer', 'coupling'],
    category: 'methods',
  },
  {
    slug: 'corrosion-allowance',
    term: 'Corrosion Allowance',
    definition: 'Additional wall thickness specified in design to account for anticipated corrosion during the service life of a component. Components are fabricated at nominal thickness plus corrosion allowance. During inspection, actual thickness is compared to the nominal value; when actual thickness decreases below nominal thickness minus corrosion allowance, the component is considered unfit for continued service. Corrosion allowance depends on operating environment and expected service life.',
    relatedTerms: ['nominal-thickness', 'thickness-measurement', 'corrosion-monitoring'],
    category: 'standards',
  },
  {
    slug: 'side-drilled-hole',
    term: 'Side-Drilled Hole',
    definition: 'A small hole (typically 1-3mm diameter) drilled horizontally into a calibration block from the side, perpendicular to the scanning surface. Side-drilled holes are used in IIW and other reference standards to simulate point-source reflectors for ultrasonic equipment calibration and evaluation. They simulate small internal flaws and are excellent for establishing sensitivity and resolution. Proper positioning of side-drilled holes at different depths ensures full-thickness coverage verification.',
    relatedTerms: ['reference-standard', 'iiw-block', 'calibration', 'sensitivity'],
    category: 'equipment',
  },
  {
    slug: 'discontinuity',
    term: 'Discontinuity',
    definition: 'Any break in the structural continuity of material, including internal (cracks, porosity, inclusions) and surface discontinuities. Not all discontinuities are defects; some are acceptable per applicable standards. Discontinuities must be detected, characterized, and evaluated to determine acceptability. The terms "discontinuity," "defect," and "flaw" are sometimes used interchangeably, though technically discontinuity is the broadest term.',
    relatedTerms: ['defect', 'flaw', 'indication', 'acceptance-criteria'],
    category: 'defects',
  },
  {
    slug: 'fatigue-crack',
    term: 'Fatigue Crack',
    definition: 'A crack initiated and propagated by repeated cyclic loading below the static yield strength of material. Fatigue cracks typically initiate at stress concentrations (welds, notches) and propagate gradually until sudden failure occurs. NDT methods like eddy current and liquid penetrant are excellent for detecting surface fatigue cracks. Early detection is critical in fatigue-critical applications like aircraft and rotating machinery.',
    relatedTerms: ['crack', 'stress-concentration', 'cyclic-loading', 'propagation'],
    category: 'defects',
  },
  {
    slug: 'immersion-testing',
    term: 'Immersion Testing (Ultrasonic)',
    definition: 'Ultrasonic testing method where both the transducer and test piece are immersed in water or other liquid couplant. Immersion testing provides excellent coupling and allows for automated scanning and precise positioning. It is ideal for detailed inspection of complex geometries and batch inspection of similar parts. The liquid couplant provides superior coupling compared to gel couplants but requires more equipment.',
    relatedTerms: ['contact-testing', 'couplant', 'automated-scanning', 'water-coupling'],
    category: 'methods',
  },
  {
    slug: 'lack-of-fusion',
    term: 'Lack of Fusion',
    definition: 'A weld defect where fusion did not occur between the weld and base metal (at the sides of the weld) or between weld passes. Lack of fusion creates a linear discontinuity parallel to the weld surface. It significantly reduces weld strength and is a critical rejectable defect. Lack of fusion is best detected by angle-beam ultrasonic testing from the side. Proper arc voltage and technique prevent lack of fusion.',
    relatedTerms: ['weld-defect', 'fusion-boundary', 'incomplete-penetration', 'crater'],
    category: 'defects',
  },
  {
    slug: 'longitudinal-wave',
    term: 'Longitudinal Wave',
    definition: 'An ultrasonic wave where particles vibrate parallel to the direction of wave propagation. Longitudinal waves are also called compression waves or P-waves. They travel faster than shear waves and are preferred for most inspections. Longitudinal waves are generated by normal-incidence transducers and readily transmitted into materials through a couplant. Most thickness measurement and flaw detection is accomplished with longitudinal waves.',
    relatedTerms: ['shear-wave', 'compression-wave', 'transducer', 'propagation'],
    category: 'physics',
  },
  {
    slug: 'nonlinear-scan',
    term: 'Non-Linear Scan',
    definition: 'A scanning pattern in ultrasonic testing that follows material geometry rather than straight parallel paths. Used on cylindrical pipe welds, circumferential scans follow the pipe circumference. Non-linear scans may follow weld contours for complex components. The key is maintaining consistent technique and beam angles throughout the scan. Data from non-linear scans must be properly referenced and interpreted.',
    relatedTerms: ['parallel-scan', 'scan-pattern', 'circumferential-scan', 'technique'],
    category: 'methods',
  },
  {
    slug: 'piezoelectric',
    term: 'Piezoelectric (Effect)',
    definition: 'The property of certain crystalline materials (like lead zirconate titanate) to generate electrical charge when mechanically deformed, or conversely, to mechanically deform when subjected to electrical fields. Piezoelectric transducers exploit this effect to convert electrical signals to ultrasonic vibrations and back. Piezoelectric elements are at the heart of ultrasonic NDT and medical imaging systems.',
    relatedTerms: ['transducer', 'crystal', 'ultrasonic-generation'],
    category: 'physics',
  },
  {
    slug: 'propagation',
    term: 'Propagation (Wave)',
    definition: 'The travel of ultrasonic waves through material from the source (transducer) to the target (defect or back wall) and return. Propagation path length is calculated from time-of-flight and material velocity. Understanding propagation geometry is critical for determining transducer angles, beam paths, and flaw depths. Wave propagation follows the laws of physics including reflection, refraction, and diffraction.',
    relatedTerms: ['wave', 'reflection', 'refraction', 'time-of-flight'],
    category: 'physics',
  },
  {
    slug: 'pulse-length',
    term: 'Pulse Length',
    definition: 'The duration of the ultrasonic transmission pulse generated by the transducer, measured in microseconds. Shorter pulse lengths provide better resolution of closely-spaced defects and reduce dead zone thickness. Pulse length is determined by transducer damping and bandwidth. Modern equipment allows control of pulse length to optimize resolution versus penetration for specific applications.',
    relatedTerms: ['dead-zone', 'resolution', 'frequency', 'bandwidth'],
    category: 'methods',
  },
  {
    slug: 'refraction',
    term: 'Refraction (Ultrasonic)',
    definition: 'The bending of ultrasonic waves when traveling from one material to another with different acoustic properties, following Snell\'s law. When waves cross material boundaries at an angle, the refracted angle is different from the incident angle based on velocity ratios. Refraction is exploited in angle-beam testing to achieve desired shear wave angles. Understanding refraction is essential for proper wedge angles and beam path geometry.',
    relatedTerms: ['snells-law', 'angle-beam-testing', 'transmission-angle', 'wedge'],
    category: 'physics',
  },
  {
    slug: 'reflection',
    term: 'Reflection (Ultrasonic)',
    definition: 'The return of ultrasonic waves from boundaries or defects back toward the transducer. Strong reflections occur at material boundaries with large acoustic impedance differences. Internal defects reflect waves based on their size and orientation. The amplitude and time-of-flight of reflected waves are used to detect and characterize flaws. Proper interpretation of reflections is fundamental to ultrasonic flaw detection.',
    relatedTerms: ['echo', 'back-wall-echo', 'acoustic-impedance', 'boundary'],
    category: 'physics',
  },
  {
    slug: 'resolution',
    term: 'Resolution (Ultrasonic)',
    definition: 'The ability to distinguish between two closely-spaced reflectors as separate indications. Axial resolution (along the beam) is determined by pulse length and frequency. Lateral resolution (across the beam) is determined by beam width and transducer size. Higher frequencies and shorter pulses provide better resolution but reduced penetration. Proper transducer selection balances resolution needs with material penetration requirements.',
    relatedTerms: ['frequency', 'pulse-length', 'penetration', 'sensitivity'],
    category: 'methods',
  },
  {
    slug: 'shear-wave',
    term: 'Shear Wave (Transverse Wave)',
    definition: 'An ultrasonic wave where particle motion is perpendicular to the direction of wave propagation, also called transverse or S-waves. Shear waves travel slower than longitudinal waves and are used in angle-beam testing for detecting defects oriented perpendicular to surfaces. Shear waves cannot propagate in liquids. They are generated by angled transducers mounted on wedges.',
    relatedTerms: ['longitudinal-wave', 'angle-beam-testing', 'transverse-wave', 'wedge'],
    category: 'physics',
  },
  {
    slug: 'stress-concentration',
    term: 'Stress Concentration',
    definition: 'A localized region of elevated stress caused by material discontinuities or geometric features (notches, holes, welds). Stress concentrations are initiation points for fatigue cracks and brittle fracture. Defects at stress concentration zones are more critical and may have lower acceptance limits. Weld toe defects like undercut create significant stress concentrations. NDT is particularly important for detecting defects in high-stress regions.',
    relatedTerms: ['stress-riser', 'fatigue-crack', 'undercut', 'weld-toe'],
    category: 'materials',
  },
  {
    slug: 'thickness-measurement',
    term: 'Thickness Measurement (Ultrasonic)',
    definition: 'Using ultrasonic echoes to measure material or wall thickness. The time delay between the initial pulse and back-wall echo is used with the material sound velocity to calculate thickness using: thickness = (velocity × time) / 2. Ultrasonic thickness measurement is non-destructive and requires access from only one side. It is the primary method for monitoring corrosion and erosion in vessels and piping.',
    relatedTerms: ['back-wall-echo', 'sound-velocity', 'time-of-flight', 'corrosion-monitoring'],
    category: 'methods',
  },
  {
    slug: 'time-of-flight',
    term: 'Time-of-Flight',
    definition: 'The elapsed time for an ultrasonic wave to travel from the transducer to a reflector and return. Time-of-flight is used with sound velocity to calculate the distance (depth) to the reflector: distance = (velocity × time-of-flight) / 2. Accurate time-of-flight measurement is critical for precise defect depth determination. Digital systems measure time-of-flight with high precision, enabling accurate flaw characterization.',
    relatedTerms: ['echo', 'sound-velocity', 'distance-amplitude-correction', 'thickness'],
    category: 'methods',
  },
  {
    slug: 'transmission',
    term: 'Transmission (Wave)',
    definition: 'The passage of ultrasonic waves through material without significant loss. High transmission efficiency requires good acoustic impedance matching between transducer, couplant, and material. Poor transmission (due to air gaps, rough surfaces, or mismatched impedance) results in weak signals and missed flaws. Maximum transmission is achieved when the transducer is perpendicular to the surface with proper couplant application.',
    relatedTerms: ['acoustic-impedance', 'couplant', 'coupling', 'reflection'],
    category: 'physics',
  },
  {
    slug: 'weld',
    term: 'Weld',
    definition: 'A joint produced by fusion of metals, created by welding processes like SMAW (stick), GMAW (MIG), FCAW (flux-core), or GTAW (TIG). Welds are common in structures, vessels, and pipelines and are frequent sources of defects. Proper weld inspection using multiple NDT methods is standard practice to ensure quality. Welds must meet composition, mechanical properties, and surface quality requirements for safe service.',
    relatedTerms: ['weld-defect', 'welding-process', 'heat-affected-zone', 'fusion-zone'],
    category: 'materials',
  },
  {
    slug: 'weld-defect',
    term: 'Weld Defect',
    definition: 'Any discontinuity in a weld that reduces its strength or fitness for service. Common weld defects include cracks, porosity, slag inclusions, lack of fusion, incomplete penetration, and undercut. Detection and evaluation of weld defects are critical aspects of quality assurance in fabrication and in-service inspection. Standards like AWS D1.1 and ASME Section V define acceptance criteria for various weld defects.',
    relatedTerms: ['weld', 'crack', 'porosity', 'slag-inclusion', 'lack-of-fusion'],
    category: 'defects',
  },
  {
    slug: 'wedge',
    term: 'Wedge (Angle Beam)',
    definition: 'A plastic or composite plastic device placed between an angle-beam transducer and test surface to tilt the transducer at a specific angle. Wedges are designed with specific angles (typically 45°, 60°, or 70°) to generate shear waves at desired angles within the material. Wedge quality and coupling are critical to achieving consistent angle-beam results. Standard wedge geometries ensure reproducibility across inspections.',
    relatedTerms: ['angle-beam-testing', 'shear-wave', 'transducer', 'snells-law'],
    category: 'equipment',
  },
  {
    slug: 'wall-thickness-measurement',
    term: 'Wall Thickness Measurement',
    definition: 'The use of ultrasonic testing to measure the remaining wall thickness in vessels, piping, and other components to detect corrosion or erosion. Regular thickness measurements track the rate of wall loss and determine when components must be retired from service. Comparison of actual thickness to minimum required thickness (based on design and corrosion allowance) determines fitness for continued operation. Ultrasonic thickness measurement is fast, non-destructive, and cost-effective.',
    relatedTerms: ['thickness-measurement', 'corrosion-monitoring', 'ultrasonic-testing'],
    category: 'methods',
  },
  {
    slug: 'acceptance-criteria',
    term: 'Acceptance Criteria',
    definition: 'Established limits and requirements that define whether an indication or defect is acceptable for continued service or must be repaired/rejected. Acceptance criteria are specified in standards like ASME Section V, AWS D1.1, API 510/570/653, and ISO standards. Criteria vary based on material, component function, defect type, and safety criticality. Proper application of acceptance criteria ensures consistent decisions and safe operation.',
    relatedTerms: ['rejection-criteria', 'rejectable-indication', 'inspection-standard', 'fitness-for-service'],
    category: 'standards',
  },
  {
    slug: 'fitness-for-service',
    term: 'Fitness-For-Service Assessment',
    definition: 'Engineering evaluation determining whether a component with detected defects can continue to operate safely under specified conditions. FFS assessments combine NDT results, material properties, operational conditions, and fracture mechanics analysis to determine safe operation or necessity for repair/replacement. Standards like API 579 provide methods for systematic FFS evaluation. FFS allows safe operation of components with minor defects.',
    relatedTerms: ['defect-evaluation', 'fracture-mechanics', 'remaining-life-assessment', 'api-579'],
    category: 'standards',
  },
  {
    slug: 'cbr-calibration',
    term: 'CBR Calibration',
    definition: 'Computer-Aided Based Reporting (CBR) system for standardizing ultrasonic calibration procedures and reducing operator variability. CBR systems automate the establishment of reference levels, gain settings, and measurement procedures. They provide documented calibration records ensuring traceability and repeatability. CBR is increasingly used for automated data collection and reporting in modern ultrasonic systems.',
    relatedTerms: ['reference-standard', 'gain', 'automated-inspection', 'digital-reporting'],
    category: 'methods',
  },
  {
    slug: 'api-510-code',
    term: 'API 510 Code (Pressure Vessel Inspection)',
    definition: 'American Petroleum Institute standard for pressure vessel inspection, maintenance, repair, and rerating. API 510 mandates NDT inspection requirements for in-service pressure vessels including ultrasonic thickness monitoring, radiography of welds, and fitness-for-service assessments. Compliance with API 510 is required in the petroleum and chemical industries. Regular inspections per API 510 extend safe service life.',
    relatedTerms: ['api-standards', 'pressure-vessel', 'inspection-standard', 'ndt-requirements'],
    category: 'standards',
  },
  {
    slug: 'api-570-pipeline',
    term: 'API 570 Code (Pipeline Inspection)',
    definition: 'American Petroleum Institute standard for in-service inspection, maintenance, repair, and rerating of pipelines. API 570 requires periodic pigging (internal inspection), external ultrasonic thickness measurements, visual inspection, and radiography of repairs. Compliance with API 570 is required in the oil and gas industry for safe pipeline operation. API 570 is essential for preventing pipeline failures.',
    relatedTerms: ['api-standards', 'pipeline-inspection', 'pigging', 'thickness-measurement'],
    category: 'standards',
  },
  {
    slug: 'asme-section-v',
    term: 'ASME Section V (Non-Destructive Examination)',
    definition: 'ASME Boiler and Pressure Vessel Code Section V provides requirements and procedures for all nondestructive examination methods including UT, RT, MT, PT, ET, and VT. It is the primary NDT standard for pressure vessels and power generation equipment. ASME Section V specifies technique parameters, acceptance criteria, and qualification requirements for NDT procedures and personnel. Most commercial NDT specifications reference ASME Section V.',
    relatedTerms: ['asme-code', 'ndt-standard', 'qualification', 'procedure'],
    category: 'standards',
  },
  {
    slug: 'aws-d1-1-welding',
    term: 'AWS D1.1 (Structural Welding Code)',
    definition: 'American Welding Society standard for structural steel welding including qualification requirements, welding procedures, inspection, and acceptance criteria. AWS D1.1 is the primary standard for welding in building and bridge construction. It mandates NDT inspections of welds using ultrasonic testing and radiography. Welders and inspectors working on structural projects must be qualified per AWS D1.1.',
    relatedTerms: ['welding-standard', 'inspection-standard', 'weld-acceptance', 'welder-qualification'],
    category: 'standards',
  },
  {
    slug: 'iso-9712-certification',
    term: 'ISO 9712 Certification (NDT Personnel)',
    definition: 'International standard for qualification and certification of NDT personnel at Level 1, 2, and 3 in ultrasonic, radiographic, magnetic particle, penetrant, and eddy current testing. ISO 9712 defines training hours, examination requirements, and experience criteria for each level. Many countries and industries require ISO 9712 certification for NDT work. Certification demonstrates competence and knowledge of NDT methods and standards.',
    relatedTerms: ['ndt-qualification', 'level-1-2-3', 'competence', 'certification'],
    category: 'certifications',
  },
  {
    slug: 'asnt-certification',
    term: 'ASNT Certification (American Society for Nondestructive Testing)',
    definition: 'Certification program in ultrasonic, radiographic, magnetic particle, penetrant, and eddy current testing offered by the American Society for Nondestructive Testing (ASNT). ASNT certification requires passing written exams and meeting training/experience requirements at Level 1, 2, and 3. ASNT is the primary certification body in North America. Many companies require ASNT certification as credential for NDT work.',
    relatedTerms: ['ndt-certification', 'qualification-standard', 'competence', 'certification-exam'],
    category: 'certifications',
  },
  {
    slug: 'ndt-training',
    term: 'NDT Training',
    definition: 'Formal education and hands-on training in nondestructive testing methods, standards, procedures, and safety. Comprehensive NDT training covers theory, equipment operation, defect recognition, standard requirements, and practical inspection experience. Training is provided by universities, technical schools, NDT service companies, and certification bodies. Quality training is essential for developing competent NDT technicians and inspectors.',
    relatedTerms: ['qualification', 'certification', 'competence', 'education'],
    category: 'certifications',
  },
  {
    slug: 'radiation-safety',
    term: 'Radiation Safety',
    definition: 'Procedures and practices for protecting people from harmful effects of ionizing radiation in radiographic testing. Safety measures include maintaining distance from radiation sources, using shielding, limiting exposure time, using dosimeters, and establishing controlled exclusion zones. Training in radiation safety is mandatory for radiographic technicians. Regulatory agencies enforce strict safety standards for industrial radiography.',
    relatedTerms: ['radiographic-testing', 'dose-limit', 'exclusion-zone', 'shielding'],
    category: 'safety',
  },
  {
    slug: 'chemical-safety-pt',
    term: 'Chemical Safety (Penetrant Testing)',
    definition: 'Safe handling of hazardous chemicals in liquid penetrant testing including dyes, solvents, cleaners, and developers. Penetrant chemicals may be flammable, toxic, or cause skin irritation. Proper safety procedures include adequate ventilation, personal protective equipment (PPE), spill prevention, and waste disposal. Material Safety Data Sheets (MSDS) must be available for all chemicals. Chemical safety training is mandatory for PT operators.',
    relatedTerms: ['penetrant-testing', 'chemical-handling', 'ventilation', 'personal-protective-equipment'],
    category: 'safety',
  },
  {
    slug: 'ergonomics-ndt',
    term: 'Ergonomics in NDT',
    definition: 'Proper work techniques and equipment setup to prevent musculoskeletal injuries in NDT operators. Repetitive scanning, reaching overhead, and sustained gripping can cause strain injuries. Proper ergonomics includes correct posture, regular breaks, equipment design, and job rotation. Many NDT companies implement ergonomic programs to reduce worker injury and improve productivity. Ergonomic training is increasingly recognized as important for long-term worker health.',
    relatedTerms: ['safety', 'occupational-health', 'work-technique', 'prevention'],
    category: 'safety',
  },
  {
    slug: 'equipment-maintenance',
    term: 'Equipment Maintenance (NDT)',
    definition: 'Regular inspection, calibration, and servicing of NDT equipment to ensure proper function and accurate results. Maintenance includes calibration verification, battery replacement, probe inspection, software updates, and component replacement. Well-maintained equipment reduces downtime, improves reliability, and extends equipment life. Maintenance schedules should follow manufacturer recommendations and company procedures.',
    relatedTerms: ['equipment-verification', 'calibration', 'qualification', 'traceability'],
    category: 'methods',
  },
  {
    slug: 'data-documentation',
    term: 'Data Documentation and Records',
    definition: 'Complete documentation of NDT inspection data, results, procedures, and personnel involved in inspections. Documentation includes equipment used, calibration data, procedure followed, defect locations, measurements, photographs, and inspector certification. Proper documentation provides traceability, supports fitness-for-service decisions, and can be required by regulators or customers. Digital data management systems are increasingly used for efficient storage and retrieval.',
    relatedTerms: ['quality-assurance', 'procedure', 'traceability', 'record-keeping'],
    category: 'methods',
  },
  {
    slug: 'phased-array',
    term: 'Phased Array Ultrasonic Testing',
    definition: 'Advanced ultrasonic method using multi-element transducers controlled electronically to steer and focus beams without moving the probe. Phased array provides superior imaging, faster scanning, and reduced operator dependence compared to conventional UT. It is becoming the standard method for critical weld inspection in aerospace and power generation. Training and equipment costs are higher but quality benefits justify the investment.',
    relatedTerms: ['ultrasonic-testing', 'electronic-scanning', 'real-time-imaging', 'weld-inspection'],
    category: 'methods',
  },
  {
    slug: 'tofd-defect-sizing',
    term: 'Time-of-Flight Diffraction (TOFD)',
    definition: 'Advanced ultrasonic technique using diffracted waves from flaw tips to accurately determine defect height and through-wall extent. TOFD is highly effective for weld crack detection and sizing. It provides objective sizing with minimal operator dependence. TOFD is often used in combination with PAUT for comprehensive weld inspection. Training and experience are required for proper TOFD application and interpretation.',
    relatedTerms: ['ultrasonic-testing', 'crack-sizing', 'weld-inspection', 'diffraction'],
    category: 'methods',
  },
];

export function getGlossaryTermBySlug(slug: string): GlossaryTerm | undefined {
  return glossaryTerms.find(term => term.slug === slug);
}

export function getAllGlossarySlugs(): string[] {
  return glossaryTerms.map(term => term.slug);
}

export function getGlossaryTermsByCategory(category: GlossaryTerm['category']): GlossaryTerm[] {
  return glossaryTerms.filter(term => term.category === category);
}

export function getTermsByAlphabet(): Record<string, GlossaryTerm[]> {
  const grouped: Record<string, GlossaryTerm[]> = {};
  glossaryTerms.forEach(term => {
    const firstLetter = term.term.charAt(0).toUpperCase();
    if (!grouped[firstLetter]) {
      grouped[firstLetter] = [];
    }
    grouped[firstLetter].push(term);
  });
  return grouped;
}
